### ISSUE TITLE
Multiple viewers on page seem to be using a cache

### ISSUE THREAD

**Issue by kfujita-cohere** [react-pdf-viewer/react-pdf-viewer#1000]
We are using the pdf viewer to display a fax in our app. We then give our users the ability to send a fax back by presenting a modal preview of what the fax will look like. However, if the incoming fax viewer is showing 1 page, that page will override the first page on the viewer in the modal. If we close the modal and reopen then the appropriate first page is displayed.

Right now I've hacked into our react code a setTimeout that basically changes the fileUrl quickly and then resets it. I'm unsure exactly what is going on and I wasn't able to fully figure it out in the code, but my suspicion is that maybe [this line of code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/src/loader/DocumentLoader.tsx#L103) is evaluating to false on the first render of the second modal so it's pulling from a cache somehow.

Any help would be much appreciated!

**Comment by shuluster** [comment]
Experiencing a similar issue. We show two pdf viewer side by side and load different documents into them. They end up showing the same document. The document shown seems to be random, could be from either react viewer.

**Comment by kfujita-cohere** [comment]
> Experiencing a similar issue. We show two pdf viewer side by side and load different documents into them. They end up showing the same document. The document shown seems to be random, could be from either react viewer.
> 
> We see correct react states for the container as well as the DocumentLoader (fileUrl is correct). I wonder if there is some singleton related to the worker that is causing this issue.

The hack we put in place for the time being (which I hate) is:
```const [currentUrl, setCurrentUrl] = useState<string>(pdfUrl);
  useEffect(() => {
    setTimeout(() => {
      setCurrentUrl(pdfUrl + "'");
      setTimeout(() => {
        setCurrentUrl(pdfUrl);
      }, 0);
    }, 1000);
  }, [pdfUrl, setCurrentUrl]);
  ```
This causes a 1 second glitch (could be shorter but since we didn't want to rely on consumer machines). I don't know if this will fully solve your issue but hope it provides inspiration until the issue is resolved here

**Comment by shuluster** [comment]
Yep. We tried the same work around and 500ms worked fine for us

**Comment by phuoc-ng** [comment]
@shuluster I can't reproduce the issue with the latest version v3.1.0.
What's the version of `@react-pdf-viewer` you're using?

**Comment by shuluster** [comment]
Upgrading to 3.1.0 solves the problem.

Another issue seems to arise. The loaded document will not render until
there is some interaction with the component. Will investigate further

**Comment by kfujita-cohere** [comment]
Same!, 3.1.0 solves the issue except now we have to put a patch in because we are hitting https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1005
