### ISSUE TITLE
Wrapped scroll mode problem with horizontal pages

### ISSUE THREAD

**Issue by katrinewi** [react-pdf-viewer/react-pdf-viewer#1001]
In the newest update there are something wrong with the wrapped scroll mode. If the PDF has a combination of  "vertical" and "horizontal" pages, the "horizontal" pages will be cut in the middle in this scroll mode. 

![Skjermbilde 2022-02-10 kl  17 40 22](https://user-images.githubusercontent.com/26788204/153454106-a9ca5254-1fd2-408d-89f0-0108701d34fc.png)

**Comment by aymanxdev** [comment]
Can you share part of the code that you are having issues with?

**Comment by phuoc-ng** [comment]
This is a bug. It will be fixed in the next version!

**Comment by phuoc-ng** [comment]
Updated: It was fixed in the latest code, and will be included in the next release.

![Screen Shot 2022-02-16 at 17 42 02](https://user-images.githubusercontent.com/57786711/156177883-aca85de2-afd4-410b-8560-45f2a58a3dc6.png)

**Comment by phuoc-ng** [comment]
[v3.1.1](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
