### ISSUE TITLE
ScrollModePluginProps Type Error Running v 3.1.0

### ISSUE THREAD

**Issue by SQuady-cohere** [react-pdf-viewer/react-pdf-viewer#1005]
I haven't seen any other posts regarding this issue. My company is currently using v 3.0.0 of react-pdf-viewer/core, react-pdf-viewer/default-layout, and react-pdf-viewer/search. When going through the process to upgrade those three dependencies to v 3.1.0, I'm seeing the following type error:

`node_modules/@react-pdf-viewer/toolbar/lib/index.d.ts:35:5 - error TS2305: Module '"@react-pdf-viewer/scroll-mode"' has no exported member 'ScrollModePluginProps'`

Checking in on the modules, there is indeed a missing export

Thank you for you attention to the matter

**Comment by phuoc-ng** [comment]
@SQuady-cohere @mbedeker @FdjNL 
The issue was fixed in [v3.1.2](https://react-pdf-viewer.dev/updates/). Please upgrade.
