### ISSUE TITLE
File Name Not Working On Download

### ISSUE THREAD

**Issue by thekennysong** [react-pdf-viewer/react-pdf-viewer#1006]
When trying to download a file the file saves as something such as `6a908420-cac3-4797-9360-9afdb724c741.pdf`. Any suggestions to get the file name to save correctly on download?

**Comment by rbideau** [comment]
Hi,

On the [Get File plugin](https://react-pdf-viewer.dev/plugins/get-file/), there is an option `fileNameGenerator` that should allow you to set the file name to save on download.

However, this options doesn't work when the download button is in the toolbar, see #897

**Comment by phuoc-ng** [comment]
@thekennysong You can use the `fileNameGenerator` option as mentioned in this [example](https://react-pdf-viewer.dev/examples/customize-the-name-of-download-file/).

@rbideau it's not a bug. I updated the comment in [#897](https://github.com/react-pdf-viewer/react-pdf-viewer/issues/897#issuecomment-1113970295)
