### ISSUE TITLE
Can't return error when "Cannot load document"

### ISSUE THREAD

**Issue by lytrankieio123** [react-pdf-viewer/react-pdf-viewer#1007]
Environment:
- react: 17.0.1
- @react-pdf-viewer/core: 3.1.0
- pdfjs-dist: 2.4.456

How to reproduce:
- Pass an invalid `fileUrl` (not exist file) in component `Viewer`

![image](https://user-images.githubusercontent.com/76729908/154021891-f54b6c18-52e4-4386-981f-c27113848309.png)

![image](https://user-images.githubusercontent.com/76729908/154021939-51004f16-8983-40eb-a734-5b28157f2208.png)

**Comment by phuoc-ng** [comment]
Please upgrade `pdfjs-dist` to the latest version.
Passing a not-found document will display an error message as following

![Screen Shot 2022-03-05 at 11 28 38](https://user-images.githubusercontent.com/57786711/156867737-9e26bcda-61df-43f0-a41a-c2216ec3400b.png)

**Comment by wqudhqdh** [comment]
same question ，Which version can be resolved @phuocng @lytrankieio123
