### ISSUE TITLE
Shortcuts for search popup

### ISSUE THREAD

**Issue by flowsni** [react-pdf-viewer/react-pdf-viewer#1008]
Hello!

Are there any shortcuts to jump to the next/previous match by pressing the down/up arrow?
If not, it whould be nice to have them.
Also, cmd+f not working properly. It works only when I clicked on left sidebar buttons

**Comment by flowsni** [comment]
@phuoc-ng any updates on this?
cmd+f is not working even in your examples in documentation :(
I've tried to debug, and faced that the document.activeElement almast always is document
Maybe we should to find out is current position of mouse over the Viewer element instead of check for `[containerEle.contains(document.activeElement)](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/bd8c105a6468ae761e6e8d11e3e06cf9ac962c18/packages/search/src/ShortcutHandler.tsx#L29)`, what do you think?

**Comment by phuoc-ng** [comment]
[v3.2.0](https://react-pdf-viewer.dev/updates/) supports `Cmd + F` shortcuts when the mouse is inside the viewer container. Please upgrade.
The similar feature, #1072, will be supported in the next version.
