### ISSUE TITLE
PDF Viewer loads pdf but blank on initial load

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [react-pdf-viewer/react-pdf-viewer#1010]
# Issue:
I have several PDFs that when the initial page is loaded that they will not display. 

Example of what it looks like
![blank-pdf-on-load](https://user-images.githubusercontent.com/6002111/154098858-c2075a68-e7f7-41d0-a973-70ca3f9d4dd2.png)

Example 2 with multiple pages
![blank-pdf-on-load-ex2](https://user-images.githubusercontent.com/6002111/154098878-c01cafcf-b128-46c5-9595-4fbea84202db.png)

## To reproduce
1. Put the pdfs in the project
2. Ensure that all packages are up to date
3. Come to the page
4. React pdf viewer will initially be blank until you scroll or manipulate the PDF viewer

After you scroll or pull out the pages it will display
![pdf-loaded-after-scroll](https://user-images.githubusercontent.com/6002111/154098813-f78e79d1-26a2-4da7-ae1a-42e9b3d92902.png)

## Additional:
I searched for issues and the only thing I found similar was #909, so in response I have upgraded all packages for the project.
![nothing-to-update](https://user-images.githubusercontent.com/6002111/154096841-85d375d1-2cf2-42e3-91f0-808404cfee99.png) 

I have used multiple browsers and found the same issue. I am using Vivaldi but most of my team is using Chrome or Edge.

Example PDF that is not working for me
[NOT_LOADING.pdf](https://github.com/react-pdf-viewer/react-pdf-viewer/files/8072526/NOT_LOADING.pdf)

Thanks in advance
Will

**Comment by teberl** [comment]
We have a very similar issue.
When opening the PDF the page stays blank until scrolling or any interaction.
Also what we observed it seems to happen only on specific screen sizes. For example my 4k Display i couldn't reproduce the issue but the client has it all the time.

We bought the license last week and planned to ship it this week.
@phuoc-ng do you think you could have a look into this issue.

**Comment by phuoc-ng** [comment]
@teberl Yes, I am working on the fix.

**Comment by mbedeker** [comment]
Hi, we are looking to start using the pdf viewer, but during our development phase we are getting this issue also.
Any idea on when you will be able to fix this?

**Comment by phuoc-ng** [comment]
@mbedeker 
I am trying to reproduce the issue on macOS and Window 10/11. Can you let me know the operating system, the browser name (including version)?

**Comment by ZinkNotTheMetal** [comment]
I’m using Windows 11, and Vivaldi as my browser. Business folks are reporting the same issue with the latest version of Chrome

**Comment by mbedeker** [comment]
I'm using these versions:
Windows 10 Pro (Version: 21H1, Build: 19043.1526)
Chrome version: 98.0.4758.102 (64-bits)

I'm getting the same result on the example link in the other issue (#988) 
https://codesandbox.io/s/react-pdf-viewer-sample-forked-xhvqm

**Comment by mbedeker** [comment]
I have to say, for our local development we are using version 3.0.0, because we are getting the error from #1005 during our build.

But the version on the example link (3.1.0) above also gives the blank page on initial load

**Comment by ZinkNotTheMetal** [comment]
@mbedeker I'm also debating downgrading if we don't have a fix soon. We are looking to go to production soon and it's not a great look when none of the PDFs load initially

**Comment by joshkay** [comment]
Having the same issue on my end, although the bug is tough to reproduce consistently.  It never happens on my machine in dev or production, but consistently happens on client's machines.

Any updates would be much appreciated!

**Comment by phuoc-ng** [comment]
@teberl @joshkay @mbedeker @ZinkNotTheMetal 
[v3.1.1](https://react-pdf-viewer.dev/updates/) is just released, and it should fix the issue. Please upgrade!

**Comment by teberl** [comment]
@phuoc-ng just updated the version and i can verify that the bug is fixed.
Thanks a lot 💪
