### ISSUE TITLE
Missing content in PDF view when load a PDF with multi pages (~ > 300pages)

### ISSUE THREAD

**Issue by lytrankieio123** [react-pdf-viewer/react-pdf-viewer#1011]
**Environment:**
- react: 17.0.1
- @react-pdf-viewer/core: 3.1.0
- pdfjs-dist: 2.4.456

**Description:**
- Load a pdf file with multi pages (~ >300 pages) ([Use this example](http://localhost:3006/pdf?url=https://enos.itcollege.ee/~jpoial/oop/naited/Clean%20Code.pdf))
- Content is missing (missing height)

![image](https://user-images.githubusercontent.com/76729908/154215657-359db079-2b3a-4cb6-9b1e-ddf7142b00f5.png)

**Comment by phuoc-ng** [comment]
The issue should be fixed in [v3.1.1](https://react-pdf-viewer.dev/updates/). Please upgrade.
