### ISSUE TITLE
Full screen on load

### ISSUE THREAD

**Issue by marek-broda** [react-pdf-viewer/react-pdf-viewer#1012]
I'd like to automatically go to "Full Screen" mode when the document has finished loading within the viewer. Is it possible to trigger full screen programmatically? 

Ideally something like : 
```
const { enterFullScreen } = useEnterFullScreen();
const handleDocLoad = () => {
    enterFullScreen();
} 

<Viewer fileUrl={fileURL} onDocumentLoad={handleDocLoad} />
```

Thanks in advance!

**Comment by mooyg** [comment]
You can make use of the [FullScreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) and [Example](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#simple_fullscreen_usage) is included in the docs as well.

**Comment by phuoc-ng** [comment]
> Is it possible to trigger full screen programmatically?

It's not possible. We can't enter the full screen mode without a user interaction (such as clicking a button, for example).
The browser will throw the following message in the _Console_ when we do that

```shell
Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
```

For more information, see this [page](https://javascript.plainenglish.io/user-gesture-restricted-web-apis-d794454453f7).
