### ISSUE TITLE
BUG: Search jumpToMatch() does not properly highlight keyword when page is not in virtual list

### ISSUE THREAD

**Issue by sirkrisp** [react-pdf-viewer/react-pdf-viewer#1013]
`jumpToMatch()` function does not add class `rpv-search__highlight--current` when corresponding page is not in virtual list.

I created a video that shows the problem based on the demo here: https://react-pdf-viewer.dev/examples/show-search-results-in-a-sidebar/

https://www.youtube.com/watch?v=Y8qdTnrckpc

**Comment by phuoc-ng** [comment]
That's a nice catch, @sirkrisp ❤️ 
I will fix it.

**Comment by phuoc-ng** [comment]
@sirkrisp 
The issue was fixed in [v3.1.2](https://react-pdf-viewer.dev/updates/). Please upgrade.
