### ISSUE TITLE
Does this support large pdf range render?

### ISSUE THREAD

**Issue by MurakamiKennzo** [react-pdf-viewer/react-pdf-viewer#1014]
since it uses pdf.js, I think It's maybe can, but I can't find any api or demo.

<img width="368" alt="Jietu20220218-182340@2x" src="https://user-images.githubusercontent.com/28294081/154664853-ff4d0e2e-4c99-40b0-9247-571f87a3e0de.png">

any tips?

**Comment by phuoc-ng** [comment]
@MurakamiKennzo You can use the `transformGetDocumentParams` option https://react-pdf-viewer.dev/docs/options/

**Comment by MurakamiKennzo** [comment]
> @MurakamiKennzo You can use the `transformGetDocumentParams` option https://react-pdf-viewer.dev/docs/options/

maybe, but I'm not familiar width pdf.js, It;s not working when I try it.
