### ISSUE TITLE
Scroll Issue on Mobile

### ISSUE THREAD

**Issue by thekennysong** [react-pdf-viewer/react-pdf-viewer#1018]
When I try to scroll vertically there is a ton of extra width on the pdf with whitespace making the mobile experience pretty poor. Is there anyway to get rid of the extra white space? Screenshot provided below.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/5256555/155464638-988276dd-612b-4886-862e-a2eca17d74e6.png">

**Comment by phuoc-ng** [comment]
@thekennysong Can you give me the sample document?

**Comment by phuoc-ng** [comment]
@thekennysong Any update on this for me?
