### ISSUE TITLE
How to get position of search matches?

### ISSUE THREAD

**Issue by baptistefkt** [react-pdf-viewer/react-pdf-viewer#1019]
Hi, is there a way to get search match position with search plugin? (I guess yes, since position is used to highlight them and for jumpToMatch)

My use case is that I would like to add a link on the keyword that is matched.

Thanks.

PS: sorry for opening issue for a question, did you consider enabling github discussion for this?

**Comment by baptistefkt** [comment]
Hi, is someone able to help me? how to get search matches position? Any input would be appreciated 🙏

**Comment by phuoc-ng** [comment]
@baptistefkt I am here! Sorry for replying late.
How do you add/insert a link on the match? As I imagine, you probably want to add a popover/tooltip on each highlight item, and then include the link inside the popover/tooltip?

**Comment by baptistefkt** [comment]
@phuoc-ng yes exactly that 🙂

**Comment by baptistefkt** [comment]
Wow, I wasn't expecting that! It's exactly what I needed. Thank you so much @phuoc-ng !

**Comment by phuoc-ng** [comment]
Update: The feature was implemented, and will be available in the next release.

**Comment by phuoc-ng** [comment]
@baptistefkt 
[v3.5.0](https://react-pdf-viewer.dev/updates/).
I also created a [live example](https://react-pdf-viewer.dev/examples/customize-the-search-highlighted-elements/) for you.

Let me know if you need anything else.
