### ISSUE TITLE
Question: Can I override / append on Rotate functionality

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [react-pdf-viewer/react-pdf-viewer#1024]
Does this viewer support overriding the functionality of the rotate plugin?

I am needing to save the document (per rotation), or have some sort of save button in order to save the new rotation state on the server. I found the following documentation related to it but nothing specifically found where I can do what I'm asking.

Documents Related:
https://react-pdf-viewer.dev/examples/customize-the-rotate-buttons/

https://react-pdf-viewer.dev/plugins/rotate/

**Comment by phuoc-ng** [comment]
@ZinkNotTheMetal 
The next version v3.2.0 will provide new `onRotate` callback which is executed when users rotate the document
(It was implemented in the latest code).

```js
<Viewer
    onRotate={({ doc, rotation }) => {
        // `doc` is the current document
        // `rotation` is the latest rotation value
    }}
/>
```

Is it enough for you?

**Comment by ZinkNotTheMetal** [comment]
That should solve my issue. Thanks for letting me override that function.

**Comment by phuoc-ng** [comment]
@ZinkNotTheMetal Thanks for getting back to me.
Just note that [v3.2.0 is released](https://react-pdf-viewer.dev/updates/).
