### ISSUE TITLE
Viewer not working on Firefox

### ISSUE THREAD

**Issue by jdentan** [react-pdf-viewer/react-pdf-viewer#1032]
The PDF viewer is not working (not event loading) on Firefox.

- Firefox ESR 78.3.1 (link to download it : https://www.npackd.org/p/org.mozilla.FirefoxESR/78.3.1)

Even the example website doesn't work on this browser (https://react-pdf-viewer.dev/)

The error is the following : `Uncaught SyntaxError: expected expression, got '='`
This seems to be an issue with the logical OR assignement (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment)

Is there a quick fix around this issue without having to upgrade the browser version ?

**Comment by phuoc-ng** [comment]
@jdentan Please upgrade the Firefox. The latest version is 97.0.1 at the time of writing this comment.

**Comment by jdentan** [comment]
Unfortunately upgrading is not an option for our clients right now.
They are tied to a certain version of the Browser due to the software they use.

That is why I opened this issue in the first place. We tried to fix it on our own but were not successfull

**Comment by phuoc-ng** [comment]
The issue is caused by `pdf-js`. The recent versions of `pdfjs-dist` uses more modern syntax that are only supported by latest browsers.
In your case, you can configure your Webpack to use the legacy build of `pdfjs-dist`.

Please take a look at this page http://localhost:3000/examples/support-internet-explorer-11/
The webpack configuration should look like

```js
// webpack.config.js
const path = require('path');

module.exports = {
    resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        alias: {
            'pdfjs-dist': path.join(__dirname, './node_modules/pdfjs-dist/legacy/build/pdf'),
        },
    },
};
```

**Comment by phuoc-ng** [comment]
Here is the screenshot that proves it works on Firefox 78.3.1 with the custom Webpack settings:

<img width="624" alt="firefox-78" src="https://user-images.githubusercontent.com/57786711/156867582-4356c752-3a6d-449b-bdc4-666f96dd035a.PNG">

**Comment by phuoc-ng** [comment]
Update: Add new documentation page https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/
