### ISSUE TITLE
DefaultLayoutPlugin causes an exception on instanciation using React 17

### ISSUE THREAD

**Issue by byhisdeeds** [react-pdf-viewer/react-pdf-viewer#1040]
I'm trying the most basic example to have the toolbar:

import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";

const defaultLayoutPluginInstance = defaultLayoutPlugin();

function Test() {
  return (
    <div style={{ height: "720px" }}>
      <Viewer fileUrl={'/test.pdf'} plugins={[defaultLayoutPluginInstance]} />
    </div>
  );
}

I get an error whenever I include the line "const defaultLayoutPluginInstance = defaultLayoutPlugin();". If I omit this line it works, but I want the toolbar. Is there an issue with React 17.

**Comment by phuoc-ng** [comment]
@byhisdeeds Can you fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut)?

**Comment by byhisdeeds** [comment]
Ok so it works if it is the main App using React 17. So that's not the
issue. However I use it inside a Component in a SPA and the error when
trying to instantiate the defaultLayoutPluginInstance is the following:

*Invalid hook call. Hooks can only be called inside of the body of a
function component. This could happen for one of the following reasons: 1.
You might have mismatching versions of React and the renderer (such as
React DOM) 2. You might be breaking the Rules of Hooks 3. You might have
more than one copy of React in the same app See
https://reactjs.org/link/invalid-hook-call
<https://reactjs.org/link/invalid-hook-call> for tips about how to debug
and fix this problem.*

*Not sure how to get around this.*

*John*

**Comment by john-preston-uwimona** [comment]
OK. Got it working. I can't use the plugins inside a class component. It has not be used in a function component and you pass the pdf source to that component, and all is well. The viewer works ok in either type of component, just the plugins seem to not work.
