### ISSUE TITLE
SyntaxError: Unexpected token '||='

### ISSUE THREAD

**Issue by paul-vd** [react-pdf-viewer/react-pdf-viewer#1041]
I'm running into the following issue,

![image](https://user-images.githubusercontent.com/39598117/157211530-bf855b20-4ee4-4514-b1a0-65df707de333.png)

I suspect I should update the alias in webpack to point to the legacy version, but this is strange encountering such issues in a brand new project, eg nextjs.

**Comment by phuoc-ng** [comment]
@paul-vd
1. Try to upgrade NodeJS to the latest stable version
2. Point the `pdfjs-dist` to its legacy version.
If you're using nextjs, then you can see the similar config [here](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/next.config.js#L7)

I will add a documentation page for this and similar issues.

**Comment by paul-vd** [comment]
So issue currently comes in, if you use a setup where you can not replace paths, e.g if you use [SWC from nextjs](https://nextjs.org/docs/advanced-features/compiler) then you can't really do that because you don't have the same webpack config capabilities.

Seeing as this is a really common and recurring issue, would it not be worth implementing a prop to target different versions from pdfjs-dist instead? like add `legacy` to the [vendors](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/be26a2a3f9155be6645f3bf696c90a9a86f57b93/packages/core/src/vendors/PdfJsApi.ts) and then allow to target it via a prop in core?

**Comment by phuoc-ng** [comment]
@paul-vd Can you create a minimum starter that uses SWC, so I can take a look?

**Comment by ivanquirino** [comment]
I'm also having this issue, same thing. I'm thinking in setting up an external webpack build to make a separate bundle and load it using an iframe.

**Comment by phuoc-ng** [comment]
@ivanquirino Does this [guide](https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/) help you?

**Comment by phuoc-ng** [comment]
@ivanquirino This [settings](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/next.config.js#L7) might be useful to you.

**Comment by phuoc-ng** [comment]
I don't try SWC yet. It is great if you can create a minimum/simple project with SWC enabled, so I can take a look to see if is compatible.

**Comment by ivanquirino** [comment]
Next uses SWC for compiling by default from version 12, so the question is if that config is going to disable it and use webpack instead.

**Comment by ivanquirino** [comment]
> I'm using the module alias, but still getting the same error, in the stack trace it still points to the same file as OP's image.

Even though the config is in place, when react-pdf-viewer requires pdfjs-dist, it gets the default version: `node_modules/pdfjs-dist/build/pdf.js`

**Comment by kpotter-m2** [comment]
> > I'm using the module alias, but still getting the same error, in the stack trace it still points to the same file as OP's image.
> 
> Even though the config is in place, when react-pdf-viewer requires pdfjs-dist, it gets the default version: `node_modules/pdfjs-dist/build/pdf.js`

FWIW you're not alone, I've got a similar setup and are encountering the same issue as you even with the following config:

```
 webpack: function (config, env) {
            config.resolve.alias['pdfjs-dist'] = path.join(__dirname, '../node_modules/pdfjs-dist/legacy/build/pdf');
            config.externals.push({
                canvas: 'canvas',
            });

            return config;
        },
```

**Comment by dmudro** [comment]
[Vercel / AWS Lambda have now made Node.js v16 available](https://vercel.com/changelog/node-js-16-lts-is-now-available) which in my experience provides the ultimate fix for the issue here.

I am not sure about the discussion around SWC here as my assumption was the fail was caused by using logical or assignment operator in the recent versions of `pdfjs-dist` package and [that was not supported by Node prior v15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility); hence the server side issues and unexpected token issue.

**Comment by dmudro** [comment]
following up on the source of this issue, updating to latest pdfjs-dist creates more syntax error issues, this time client side in older browsers as their bundle uses private field operators not working on Safari < 14.1 for example:

https://github.com/mozilla/pdf.js/issues/14912

**Comment by gelintonx** [comment]
Hi @paul-vd I solved this issue updating my NodeJS version I was using Node 14 and I found same error then I updated to Node 16 and now it's working fine.

Regards

**Comment by paul-vd** [comment]
> Hi @paul-vd I solved this issue updating my NodeJS version I was using Node 14 and I found same error then I updated to Node 16 and now it's working fine.
> 
> Regards

Thanks for the info, will give it a try.

**Comment by dmudro** [comment]
regarding my earlier suggestion and some others here, you can totally get around the latest JS syntax and Node js version by simply importing the legacy version i. e. `pdfjs-dist` source that is backwards compatible with older js runtime envs.

it's all documented as per [earlier comment](https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1041#issuecomment-1088772653):
https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/

in fact you should really take this approach as either the browser or node will always play a catch up game with latest js syntax which will always be in the non legacy `pdfjs-dist` bundle.
