### ISSUE TITLE
Display reading progress at the top - not work....

### ISSUE THREAD

**Issue by cordoba3030** [react-pdf-viewer/react-pdf-viewer#1046]
Display reading progress at the top - not work....

**Comment by cordoba3030** [comment]
I mean... Last time I saw this feature was warked in demo in your site. But now ti is notwork...

**Comment by phuoc-ng** [comment]
@cordoba3030 
The issue is fixed. The example now works properly https://react-pdf-viewer.dev/examples/display-reading-progress-at-the-top/

![Screen Shot 2022-03-13 at 10 05 17](https://user-images.githubusercontent.com/57786711/158043334-4a953d52-6b56-40ca-a6e5-554cc408d819.png)

**Comment by cordoba3030** [comment]
Ok. Works for only vertical scrolling, but does not work for
horizontal scrolling....

вс, 13 мар. 2022 г. в 08:11, phuoc-ng ***@***.***>:
