### ISSUE TITLE
Create-React-App: Support for the experimental syntax 'classPrivateProperties' isn't currently enabled 

### ISSUE THREAD

**Issue by appcoders** [react-pdf-viewer/react-pdf-viewer#1048]
Bought react-pdf-viewer today. Using CRA and getting the following error:

```
./node_modules/pdfjs-dist/build/pdf.js
SyntaxError: ../node_modules/pdfjs-dist/build/pdf.js: Support for the experimental syntax 'classPrivateProperties' isn't currently enabled (2495:3):
```

Tried both

pdfjs-dist@2.12.313 (like in CRA example)

and

pdfjs-dist@2.13.216

Same error.

**Comment by appcoders** [comment]
Found the solution here: https://github.com/react-pdf-viewer/starter/tree/main/create-react-app-v4
Docs should be updated :-)

**Comment by phuoc-ng** [comment]
@appcoders 
I just added new documentation page here https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/

**Comment by appcoders** [comment]
Thanks! :-)
