### ISSUE TITLE
[Support request] Toggling bookmarks from toolbar

### ISSUE THREAD

**Issue by siwood** [react-pdf-viewer/react-pdf-viewer#1050]
Hi there - I was hoping to get some guidance on using the bookmark plugin without the whole sidebar/default layout. Ideally I would like to add a button to the toolbar that toggles the bookmarks open and closed.

Does anyone have any pointers for how to go about this? I see documentation on adding a custom toolbar button. But all functionality for toggling the bookmarks panel seems to be within the sidebar plugin, which is inside the default layout. So I'm not quite sure how to take advantage of it without using the whole sidebar.

**Comment by phuoc-ng** [comment]
It's possible. I will create an example for you.

**Comment by phuoc-ng** [comment]
@siwood The example is now available at
https://react-pdf-viewer.dev/examples/add-a-button-to-the-default-toolbar-to-toggle-the-bookmarks/

![Screen Shot 2022-03-21 at 13 18 40](https://user-images.githubusercontent.com/57786711/159213274-9bdc910f-82cd-4fbd-bac3-c153e3147f26.png)
