### ISSUE TITLE
Incompatible with Remix react version?

### ISSUE THREAD

**Issue by vedantroy** [react-pdf-viewer/react-pdf-viewer#1053]
Hi,

I purchased a copy of this component. I'm using remix.run to build a website, and I noticed that it has a peer dep of react 16.8 while remix runs on react 17+.

I think I can still install the package with `--force`, but there are a bunch of warnings. Is there any way to suppress these warnings / should I just ignore them?

**Comment by phuoc-ng** [comment]
@vedantroy First of all, thanks for making the purchase.
The packages have the peer dependencies

```
"peerDependencies": {
  "react": "^16.8.0 || ^17.0.0",
   "react-dom": "^16.8.0 || ^17.0.0"
 }
```

So, it is compatible with React 17+.
