### ISSUE TITLE
The different options are located on the left side of the toolbar #bug

### ISSUE THREAD

**Issue by michaeljsvs** [react-pdf-viewer/react-pdf-viewer#1075]
The error is in "Create a toolbar with different slots for the default layout", where the different options are located on the left side of the toolbar
https://react-pdf-viewer.dev/examples/create-a-toolbar-with-different-slots-for-the-default-layout/
![image](https://user-images.githubusercontent.com/54175563/163117011-76cf147f-2e1c-42fa-92ad-3440525d7846.png)

**Comment by phuoc-ng** [comment]
@michaeljsvs Thanks for reporting the issue.
The [example](https://react-pdf-viewer.dev/examples/create-a-toolbar-with-different-slots-for-the-default-layout/) and [its sample code](https://github.com/react-pdf-viewer/examples/blob/main/default-layout/ToolbarSlotsExample.tsx) are updated.

![Screen Shot 2022-04-16 at 17 18 32](https://user-images.githubusercontent.com/57786711/163671233-055dc8ed-9256-455e-ba39-ed76e68d2e15.png)

**Comment by michaeljsvs** [comment]
Thanks
