### ISSUE TITLE
customization of search popover

### ISSUE THREAD

**Issue by JSurquin** [react-pdf-viewer/react-pdf-viewer#108]
Hi @phuoc-ng , i want to create my own search function and my own search modal or popover

Actually there is a solution already implemented to customize it or is it planned ?

I want to make an other search , responsive and not block the view of user (the popover exceeds from the viewer)

it is not an issue but rather a question

Edit : and whole words search have not the effect exepected , in french we have many accents (é, à ...) i would rather like if we can search with no accents in whole words 

**Example**

République => 1 match case 
république => 1 whole words
republique => nothing.

Have a good day :)

**Comment by phuoc-ng** [comment]
@JSurquin 

Supporting custom search control is implemented and will be released in 2.2.0.

You can see the demo in the following GIF:

![search](https://user-images.githubusercontent.com/57786711/97712959-bd483a80-1af1-11eb-84fc-6befd481826c.gif)

I'll update here when 2.2.0 is released.

**Comment by phuoc-ng** [comment]
@JSurquin 
v2.2.0 was [released](https://react-pdf-viewer.dev/updates/). Please upgrade!
