### ISSUE TITLE
help with pdf reader

### ISSUE THREAD

**Issue by goravsoni** [react-pdf-viewer/react-pdf-viewer#1081]
I get the following errors when I try uploading a file
![image](https://user-images.githubusercontent.com/49302341/163648823-91360d50-df32-427b-a5c8-c9493d31798d.png)

**Comment by phuoc-ng** [comment]
@goravsoni Please give me the steps to reproduce the issue! You can fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut).
