### ISSUE TITLE
Search plugin does not highlight words when selecting whole words option #BUG

### ISSUE THREAD

**Issue by michaeljsvs** [react-pdf-viewer/react-pdf-viewer#1088]
1. Go to https://react-pdf-viewer.dev/examples/use-the-default-button-to-show-the-search-popover/
2. We look for the word "that", and see if it highlights the words found
![image](https://user-images.githubusercontent.com/54175563/163701590-c72a9de9-d20a-401c-a367-23ac49752438.png)
3. Now we select the "whole words" option and it does not highlight the words
![image](https://user-images.githubusercontent.com/54175563/163701681-1a8ab853-a047-4614-b645-5132ef8a9b74.png)
![image](https://user-images.githubusercontent.com/54175563/163701687-6963a5a3-9925-4440-a6b0-f05d1a538393.png)

**Comment by phuoc-ng** [comment]
Thanks for reporting the issue, @michaeljsvs 👍 
The bug was fixed in the latest code, and will be included in the next v3.3.0.

![Screen Shot 2022-04-17 at 21 14 57](https://user-images.githubusercontent.com/57786711/163719681-e5943880-bcc3-460b-9d67-f1ffe02f875d.png)

**Comment by michaeljsvs** [comment]
Thank you @phuoc-ng

**Comment by phuoc-ng** [comment]
@michaeljsvs 
[v3.3.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!

**Comment by michaeljsvs** [comment]
Perfect @phuoc-ng!
Thanks for letting me know, now I'll update it
