### ISSUE TITLE
The text ".rpv-core__text-layer-text" in the layer ".rpv-core__text-layer" does not match in some PDFs #BUG

### ISSUE THREAD

**Issue by michaeljsvs** [react-pdf-viewer/react-pdf-viewer#1089]
The text ".rpv-core__text-layer-text" in the layer ".rpv-core__text-layer" does not match in some PDFs, it sticks out of the layer
1. In this screenshot, there is the PDF with its text correctly
![image](https://user-images.githubusercontent.com/54175563/163703476-a97ae7aa-46e4-4cfd-b6d6-f0756f800d19.png)

2.But in the following image, when displaying the text of the ".rpv-core__text-layer" layer, it sticks out
![image](https://user-images.githubusercontent.com/54175563/163703487-17a66262-a5f8-497e-be24-949d33972737.png)

This is a mistake? How can I do so that in all the PDFs the text does not sticks out in any of them? Is there any CSS code I can put in?

**Comment by phuoc-ng** [comment]
@michaeljsvs Can you give me a sample document?

**Comment by michaeljsvs** [comment]
Hi @phuoc-ng , I cancel the issue, because the error appeared with a previous version of pdfjs-dist (I had not updated it)
I updated to version pdfjs-dist@2.13.216 and I don't see the error in any book
Thank you

**Comment by michaeljsvs** [comment]
I cancel the issue, because the error appeared with a previous version of pdfjs-dist (I had not updated it)
I updated to version pdfjs-dist@2.13.216 and I don't see the error in any document

**Comment by phuoc-ng** [comment]
Thanks you, @michaeljsvs ❤️
