### ISSUE TITLE
React v18 doesn't support react-pdf-viewer

### ISSUE THREAD

**Issue by Sampath539** [react-pdf-viewer/react-pdf-viewer#1098]
React v18 doesn't support react-pdf-viewer, it was giving "visibility" error.

**Comment by phuoc-ng** [comment]
@Sampath539 
Supporting React 18 is only available in the latest version, 3.3.0.

Please fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-g1y62m), and let me know the steps to reproduce the issue.
The sample project works with the latest version of React v18 and `react-pdf-viewer` 3.3.0.

**Comment by phuoc-ng** [comment]
Same as #1099

**Comment by Sampath539** [comment]
@phuoc-ng Thanks, 3.3.0 works good

**Comment by phuoc-ng** [comment]
Fixed in [v3.3.1](https://react-pdf-viewer.dev/updates/)
