### ISSUE TITLE
body dir="rtl" is causing the wrong render 

### ISSUE THREAD

**Issue by galz-ct** [react-pdf-viewer/react-pdf-viewer#1102]
Hi - Im having issues using the library on rtl mode -
Found related issue in pdf.js -
https://github.com/mozilla/pdf.js/issues/12081

Thanks

![image](https://user-images.githubusercontent.com/99596413/165539643-654411bf-3bde-456c-b821-2cca3466bd5e.png)

**Comment by galz-ct** [comment]
Found some workaround for now;
Im using the customCanvasPlugin plugin to set attribute back to ltr and it seems to work.
Ill be happy for better solution (:

**Comment by phuoc-ng** [comment]
Does the [TextDirection](https://react-pdf-viewer.dev/examples/use-a-rtl-language/) option help?

**Comment by galz-ct** [comment]
Seems to be an issue with rtlcss - ignoring the pdf viewer component + using text direction seems to solve my issues. Thanks!
