### ISSUE TITLE
Highlight the entire page when selecting between lines

### ISSUE THREAD

**Issue by Attiley** [react-pdf-viewer/react-pdf-viewer#1103]
It seems that if I don't move the mouse into space between lines it works fine. But if it happens, the entire page will get selected.
Is this purposely designed or a bug?
The selection behavior on Chrome - 100.0.4896.127
![screen shot](https://user-images.githubusercontent.com/30063889/165596775-67bc5815-6511-4e4d-89dd-d24e9e1d9fc5.png)

**Comment by phuoc-ng** [comment]
It's a bug. Thanks for reporting the issue.

**Comment by phuoc-ng** [comment]
@Attiley 
[v3.5.0](https://react-pdf-viewer.dev/updates/) is released. It fixes the issue. Please upgrade!
