### ISSUE TITLE
Show only first page

### ISSUE THREAD

**Issue by HovhannesMkoyan** [react-pdf-viewer/react-pdf-viewer#1104]
Hello,

I went through the docs but still could not find a way to show only the first page of a pdf. 
So, say a PDF is 100 pages long, but in the case of some users, I want them to see only the first page.
Is there a way to do so?

Thanks!

**Comment by phuoc-ng** [comment]
@HovhannesMkoyan You can use the [Cover component](https://react-pdf-viewer.dev/examples/display-the-thumbnail-of-a-given-page/).
