### ISSUE TITLE
License Inquiry

### ISSUE THREAD

**Issue by mariachakhtoura** [react-pdf-viewer/react-pdf-viewer#1105]
As per #586 , nothing on the react component should be updated once the license is purchased.
I don't understand how you will be able to validate the authenticity of the usage if the license and component are separate?
I have read (https://react-pdf-viewer.dev/license/) but still think I am missing something.

Any help is appreciated, thanks!

**Comment by phuoc-ng** [comment]
@mariachakhtoura Thanks for the question.
Currently, there's no license verification, but it will be there on v4. Basically you don't have to put the license key in the code directly, but it will be requested in the package installation.
