### ISSUE TITLE
Display multiple pdf files as one

### ISSUE THREAD

**Issue by RadomirNowak** [react-pdf-viewer/react-pdf-viewer#1108]
Is there a possibility to display multiple pdfs files as one? For example I have a few documents that I'd like to display as one, with one scroll and with plugins like zoom or pageNavigation.

So in my case it would mean, that I can scroll through all documents with one scroll, I can see total pages as the sum of all pdfs pages, and when I invoke ZoomIn action, then all pages from all documents are zoomed in.

I saw the example with multiple `<Viewer />` components, but in the example they all use different `zoomPluginInstance`, and when I tried to reproduce the example and pass the **same** `zoomPluginInstance`, then it works only for once document.

Thanks in advance!
Radomir

**Comment by phuoc-ng** [comment]
It's not possible. There are many issues that can happen such as navigating between bookmarks/annotation link.
