### ISSUE TITLE
initialPage not working

### ISSUE THREAD

**Issue by mm105** [react-pdf-viewer/react-pdf-viewer#1115]
Viewer renders first page, not page provided in `initialPage` prop.

code: 

```
<Viewer
    fileUrl={`${process.env.PUBLIC_URL}/sample.pdf`}
    initialPage={2}
/>
````

dependencies: 

```
"@react-pdf-viewer/core": "^3.3.1",
"pdfjs-dist": "^2.13.216",
"react": "^18.1.0",
"react-dom": "^18.1.0",
```

**Comment by mm105** [comment]
for some reason, I have this issue only in my local environment, when I deploy application it works as expected

**Comment by phuoc-ng** [comment]
I can confirm that bug. It only happens with React 18's Strict mode.

**Comment by phuoc-ng** [comment]
Update: The bug was fixed in the latest code, and will be included in the next version.

**Comment by mm105** [comment]
great, thanks!

**Comment by phuoc-ng** [comment]
@mm105 
[v3.3.2](https://react-pdf-viewer.dev/updates/) was released. Please upgrade!
Let me know if you have any issues/suggestions/feature requests.

**Comment by Mathiasfx** [comment]
Hi, is not working for me, i have v.3.4.1 and started in page 0 whatever number you put on the parameter

**Comment by Mathiasfx** [comment]
Hi Again, i fix it , just add a heigt div container for example:
`<div style={{height:"700px"}}>
<Viewer initialPage={currentPage}></Viewer>
</div>`

**Comment by Mathiasfx** [comment]
`<div style={{height:'700px'}}>
<Viewer initialPage={currentPage}></Viewer>
</div>`
