### ISSUE TITLE
rendering a list of pdfs

### ISSUE THREAD

**Issue by YasineNifa** [react-pdf-viewer/react-pdf-viewer#1118]
Hello guys !
Is there an other way to render a list of pdfs one after the other
I wrote this code. 
```
pagePDF.map((url,index) => {
            return(
                <div id={'main-'+(index+1)} key={index}>
                    <Worker workerUrl= 'https://unpkg.com/pdfjs-dist@2.12.313/build/pdf.worker.js'>
                        <div style={{ overflow: 'hidden', height:'700px' }}>
                            <Viewer
                            fileUrl={url}
                            key={index}
                            />
                        </div>
                    </Worker>
                </div>
            )
        })
```
It keeps displaying only one page nth time (where n is the length of the list)
pagePDF contains the url of all pdf file I want to display (I make sure that there is no duplica in the list)

**Comment by phuoc-ng** [comment]
That's fine as long as you don't use any plugin. If you use plugin(s), then be aware of [this](https://react-pdf-viewer.dev/examples/use-multiple-viewers-in-the-same-page/)

**Comment by YasineNifa** [comment]
The problem is that it keeps showing only one pdf multiple of time

**Comment by phuoc-ng** [comment]
@YasineNifa Here is a simple [project](https://codesandbox.io/s/react-pdf-viewer-multiple-pdfs-m4jfc1?file=/src/App.tsx) that displays multiple PDFs.
