### ISSUE TITLE
flickery side effect on zooming in/out (when using page navigation)

### ISSUE THREAD

**Issue by zurabarata** [react-pdf-viewer/react-pdf-viewer#1124]
hej,

we are trying to implement a smooth scroll when using page navigation.
after applying `scroll-behavior: smooth` to `.rpv-core__inner-pages`
we have a flickery side effect on zooming in/out (when using page navigation):

https://user-images.githubusercontent.com/57256959/167592408-f3c741f9-5ae4-4ff8-98c6-07a6ca643d74.mov

steps to reproduce:
  1. apply `scroll-behavior: smooth` to `.rpv-core__inner-pages`
  2. open a document with multiple pages
  2. scroll down the second page
  4. click zoom in (or zoom out) button

**Comment by zurabarata** [comment]
related issue: 
https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1107

**Comment by adamklepacz** [comment]
I'm also having that issue ☝🏻

**Comment by RadomirNowak** [comment]
The issue seems to be related to [`packages/core/src/layouts/Inner.tsx` line 348:](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/291d7c5207405c6660ef9aadccadfde5d917df24/packages/core/src/layouts/Inner.tsx#L348)

Using the build in `scrollTo` instead of `scrollTop` and `scrollLeft` methods, we can set the behavior to `instant` so that it does not flicker:
```
// behavior: 'instant' needs to be cast to any because of https://github.com/microsoft/TypeScript/issues/47441
pagesEle.scrollTo({
    top: (pagesEle.scrollTop * updateScale) / stateRef.current.scale,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    behavior: 'instant' as any,
});
```

I think it's a fairly trivial change and does not affect any other parts of features. What do you think @phuoc-ng - is it possible to merge it?

**Comment by zurabarata** [comment]
@phuoc-ng would we get any support for this issue if we purchase the license? 📦

**Comment by phuoc-ng** [comment]
This will be supported in the next version.

Here are some demos.

## Navigate between previous/next pages

https://user-images.githubusercontent.com/57786711/172016851-217fc778-3c15-454d-a087-11bc5b782102.mp4

## Jump to a given page 

https://user-images.githubusercontent.com/57786711/172016868-570ca72b-b432-43d0-b621-b8b1316259a6.mp4

## Click a bookmark

https://user-images.githubusercontent.com/57786711/172016874-d7bde55b-a78b-450c-9ec8-c59a1b4bacc0.mp4

## Click a thumbnail

https://user-images.githubusercontent.com/57786711/172016887-7ef7a86e-ddc3-4e15-9934-30e7c58890e1.mp4

## Jump between search results

https://user-images.githubusercontent.com/57786711/172016907-5d4a5b19-2155-43a9-85ce-69dd6e65f5d5.mp4

**Comment by phuoc-ng** [comment]
[v3.4.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
