### ISSUE TITLE
Automatically scroll to the thumbnail of initial page when it's set

### ISSUE THREAD

**Issue by phuoc-ng** [react-pdf-viewer/react-pdf-viewer#1125]
Thanks for the great suggestion, @mm105 👍

**Comment by mm105** [comment]
Similar can be done for bookmarks. Assuming that bookmarks are initially collapsed, if there is initialPage set, expand bookmark of that page.

**Comment by phuoc-ng** [comment]
@mm105 The improvement is available in the [v3.3.3](https://react-pdf-viewer.dev/updates/)
