### ISSUE TITLE
A page does not render #BUG

### ISSUE THREAD

**Issue by michaeljsvs** [react-pdf-viewer/react-pdf-viewer#1128]
I attach a video:
https://user-images.githubusercontent.com/54175563/168461815-0e8cb539-f5c0-42eb-9ac1-f3d3aed2f3bb.mp4

**Comment by phuoc-ng** [comment]
Please fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) and let me know the steps to reproduce the issue.

**Comment by michaeljsvs** [comment]
Hi @phuoc-ng
I didn't need to edit or fork the sample project, because the steps to reproduce the problem are:
1) Click several times on Zoom in or Zoom out
2) Change the page with the scrollbar or the "Previous Page" or "Next Page" buttons, until you find the page that does not render
3) Toggle between steps 1 and 2

I attach an image where you can see that, for example, in my case, it was with Zoom= 70% and CurrentPage= 4:
![image](https://user-images.githubusercontent.com/54175563/168685280-bd5ebcf0-8599-4276-b4ea-533342b95261.png)

**Comment by michaeljsvs** [comment]
As an extra fact: the problem seems to appear mostly the first time the page is reloaded
![image](https://user-images.githubusercontent.com/54175563/168687187-de35ba11-15f9-4833-8a69-e1fe13b0b5e4.png)

**Comment by michaeljsvs** [comment]
Hi @phuoc-ng,
were you able to find the error by reproducing the steps I mentioned?

**Comment by adamthewan** [comment]
Also facing this bug

**Comment by phuoc-ng** [comment]
Please upgrade to [v3.3.3](https://react-pdf-viewer.dev/updates/). I hope this version fixes the issue.
