### ISSUE TITLE
Why am I getting this error in my highlight plugin code?

### ISSUE THREAD

**Issue by michaeljsvs** [react-pdf-viewer/react-pdf-viewer#1129]
The object is possibly "undefined":
![image](https://user-images.githubusercontent.com/54175563/168462030-997da6ce-ce41-4ab3-a2a7-f6a40341cefc.png)

What is the solution?

**Comment by phuoc-ng** [comment]
You can get rid of the warning as

```tsx
const noteEle = noteEles.get(note.id);
if (nodeEle && ...) {
  notesContainer.scrollTop = noteEle.getBoundingClientRect().top;
}
```

**Comment by michaeljsvs** [comment]
OK thank you @phuoc-ng
