### ISSUE TITLE
The text might not be selectable if a plugin registers renderPageLayer

### ISSUE THREAD

**Issue by phuoc-ng** [react-pdf-viewer/react-pdf-viewer#1131]

**Comment by MattWNaimuri** [comment]
We're experiencing an issue with searching text in our PDF and just wanted to double check this is the same open issue. 
Seems to be an issue with resizing the PDF/ browser whilst searching text. 

We're getting hit with the error: "An error ocurred: Failed to execute 'setStart' on 'Range': The offset 14 is larger than the node's length (1)."

Along with this in the console:

<img width="628" alt="Screenshot 2022-05-25 at 10 14 51" src="https://user-images.githubusercontent.com/106235646/170227845-8c9b48e0-7b43-4e28-9fde-7aefcbd69321.png">

Also, here are the plugins we are using: 
<img width="927" alt="Screenshot 2022-05-25 at 10 17 48" src="https://user-images.githubusercontent.com/106235646/170228235-0bdf2534-62d2-4701-b24b-c3891b1db992.png">

**Comment by phuoc-ng** [comment]
@MattWNaimuri It is a different issue. Can you create a new issue for that?

**Comment by MattWNaimuri** [comment]
No Problem.

**Comment by phuoc-ng** [comment]
Done.
