### ISSUE TITLE
Missing dependency '@pdf-viewer$react-pdf-viewer/core@3.3.2/lib/styles/index.css

### ISSUE THREAD

**Issue by neilsrg** [react-pdf-viewer/react-pdf-viewer#1134]
Hi,
I am trying to use your library to run this simple code to display a PDF file, 

```
// Core viewer
import { Viewer } from '@react-pdf-viewer/core';

// Plugins
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';

// Import styles
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';

// Create new plugin instance
const defaultLayoutPluginInstance = defaultLayoutPlugin();

<Viewer
    fileUrl='https://www.appsloveworld.com/wp-content/uploads/2020/01/SamplePdf1_12mb_6pages.pdf'
    plugins={[
        // Register plugins
        defaultLayoutPluginInstance
    ]}
/>
```

Here is my package.json
```
{
	"dependencies": {
		"@babel/parser": "^7.17.12",
		"@babel/runtime": "^7.17.9",
		"@react-pdf-viewer/core": "^3.3.2",
		"@react-pdf-viewer/default-layout": "^3.3.2",
		"pdfjs-dist": "^2.14.305",
		"react": "^16.14.0",
		"react-dom": "^16.14.0",
		"react-pdf": "^5.7.2",
		"typescript": "^4.6.4"
	},
	"devDependencies": {
		"@babel/cli": "^7.17.10",
		"@babel/core": "^7.17.12",
		"@babel/preset-env": "^7.17.12",
		"@babel/preset-react": "^7.17.12",
		"liferay-npm-bundler": "2.18.2"
	},
	"main": "lib/index.es.js",
	"name": "pdf-viewer",
	"scripts": {
		"build": "babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources && liferay-npm-bundler"
	},
	"version": "1.0.0"
}
```

But it always returns these 2 errors:

- Missing dependency '@pdf-viewer$react-pdf-viewer/core@3.3.2/lib/styles/index.css
- Missing dependency '@pdf-viewer$react-pdf-viewer/default-layout@3.3.2/lib/styles/index.css

Any clue why?
Do I need to purchase the library before I can use it?

Cheers,
Neil
​

**Comment by phuoc-ng** [comment]
> Do I need to purchase the library before I can use it?

You don't have to. It's free to try it.

**Comment by phuoc-ng** [comment]
I am not familiar with `liferay-npm-bundler`. Maybe Liferay uses another way to import the CSS files.
You should look at the Liferay documentations.

**Comment by neilsrg** [comment]
It returns Missing Dependencies on this 2 lines

// Import styles
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';

I check the node_modules it does have the module required
![Screen Shot 2022-05-20 at 11 58 30 am](https://user-images.githubusercontent.com/17398376/169433449-7a198f7e-164b-4a07-8ab6-37f193396bb8.png)

any clue why?

**Comment by neilsrg** [comment]
Where is the node_modules config located? how the system knows to you use which node_modules folder if more than one modules existed?

**Comment by phuoc-ng** [comment]
I think you should look at [liferay-npm-bundler-loader-css-loader](https://github.com/izaera/liferay-frontend-projects/tree/master/maintenance/projects/js-toolkit/packages/liferay-npm-bundler-loader-css-loader), so the bundler will know how to process CSS imports.
