### ISSUE TITLE
online pdf link not working 

### ISSUE THREAD

**Issue by rlucky469** [react-pdf-viewer/react-pdf-viewer#1136]
online file
![Untitled](https://user-images.githubusercontent.com/77981064/169961556-aa0cacb2-9812-427e-ad83-9d6f4b79cbf3.png)
 link not working

**Comment by phuoc-ng** [comment]
Please make sure that you are able to access the direct PDF (You can try by pasting the document URL in a browser tab in the _Icognito_ mode).
If the document requires any authentications, please use the [`httpHeaders` option](https://react-pdf-viewer.dev/docs/options/).

**Comment by rlucky469** [comment]
thanks for your reply @phuoc-ng
