### ISSUE TITLE
Searching text in PDF is erroring while in strict mode with React 18

### ISSUE THREAD

**Issue by MattWNaimuri** [react-pdf-viewer/react-pdf-viewer#1137]
We're experiencing an issue with searching text in our PDF with Strict mode enabled, in React 18 @react-pdf-viewer/core@3.3.2

We're getting hit with the error: "An error ocurred: Failed to execute 'setStart' on 'Range': The offset 14 is larger than the node's length (1)." when searching a term in the PDF.

Along with this in the console:
<img width="628" alt="Screenshot 2022-05-25 at 10 14 51" src="https://user-images.githubusercontent.com/106235646/170273321-ec6408e0-8324-4570-bb44-b7a95a34e4eb.png">

Also, here are the plugins we are using:
<img width="927" alt="Screenshot 2022-05-25 at 10 17 48" src="https://user-images.githubusercontent.com/106235646/170273358-52313681-df89-4bb5-89e8-e9ea9820c904.png">

**Comment by phuoc-ng** [comment]
@MattWNaimuri Does the issue happen when you search for any keyword? or just specific keyword?
Also, looking at your sample code, the default layout plugin also registers the search plugin automatically.

```tsx
// Before
<Viewer plugins={[defaultLayoutPluginInstance, searchPluginInstance, highlightPluginInstance]} />

// After
<Viewer plugins={[defaultLayoutPluginInstance, highlightPluginInstance]} />
```

**Comment by MattWNaimuri** [comment]
@phuoc-ng Yes this happens with any keyword. It seems to correctly work on the initial search of a key word, but when scrolling through the PDF or skipping to the next highlighted term it will fail and throw the error above.

**Comment by phuoc-ng** [comment]
I can't reproduce the issue with the way you mentioned. Can you let me know the steps to reproduce the issue by forking this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut)?

**Comment by MattWNaimuri** [comment]
@phuoc-ng 
Ive tried to replicate what we current have set up to throw the error. 
Please see: https://codesandbox.io/s/react-pdf-viewer-sample-forked-70ddbh?file=/src/App.ts

As you can see on line 41, I'm hardcoding the keyword 'and' for this demonstration.  The quickest way to get the error to throw is to play around with the zoom in and out buttons at the top of the PDF to resize. This tends to throw the error fairly reliably.

**Comment by phuoc-ng** [comment]
I can reproduce the issue with the project you created. Thanks a lot.
I will fix the issue.

**Comment by phuoc-ng** [comment]
@MattWNaimuri 
[v3.5.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade! It fixes the issue.
