### ISSUE TITLE
Open links in new tab not working as per example on the site

### ISSUE THREAD

**Issue by qwertyvipul** [react-pdf-viewer/react-pdf-viewer#1139]
Hi,

I was trying out [this example](https://react-pdf-viewer.dev/examples/find-and-replace-links-found-in-each-page/), and have created a codesandbox reproducer [here](https://codesandbox.io/s/react-pdf-viewer-open-links-in-new-tab-3djnst). The first link in the reproducer sometimes opens in new tab, sometimes it doesn't and the second link does not work at all. Could you please provide with a suggestion/solution?

Thanks!

**Comment by vipul-sharma-deshaw** [comment]
Yes, I tried that already, the links do open but not in new tab. My requirement is - the links should open in new tab.

**Comment by phuoc-ng** [comment]
The page has the following structure

```html
<div class="rpv-core__text-layer">
   <span class="rpv-core__text-layer-text">
     <a href="https://www.google.com/" style="color: red; text-decoration: none;" target="_blank">https://www.google.com/</a>
   </span>

  <span class="rpv-core__text-layer-text">Google</span>
</div>
```

It means that the plugin can find the links and add `target="_blank"` attributes.
However, the document in the example is special. The links you see actually are annotations which are rendered as 

```html
<div class="rpv-core__annotation-layer">
  <div class="rpv-core__annotation rpv-core__annotation--link">
    <a href="https://www.google.com/" rel="noopener noreferrer nofollow" title="https://www.google.com/"></a>
  </div>
  <div class="rpv-core__annotation rpv-core__annotation--link">
     <a href="https://www.google.com/" rel="noopener noreferrer nofollow" title="https://www.google.com/"></a>
  </div>
</div>
```

In order to add `target="_blank"` to those link annotations, you can modify the plugin:

```tsx
const findLinksPlugin = () => {
  const findLinks = (e) => {
    ...
  };

  const findLinksAnnotations = (e) => {
    e.container
      .querySelectorAll(".rpv-core__annotation--link a")
      .forEach((link) => {
        link.setAttribute("target", "_blank");
      });
  };

  return {
    onTextLayerRender: findLinks,
    onAnnotationLayerRender: findLinksAnnotations
  };
};
```

Here is the working projects:
* https://codesandbox.io/s/react-pdf-viewer-open-links-in-new-tab-forked-rxk5i5
* Demo: https://rxk5i5.csb.app/

**Comment by vipul-sharma-deshaw** [comment]
Thanks @phuoc-ng! This is exactly what I was look for.
