### ISSUE TITLE
some pdf files are rendered in a flipped way when using SVG layer and using blob for fileUrl

### ISSUE THREAD

**Issue by wonjunkang** [react-pdf-viewer/react-pdf-viewer#114]
<img width="921" alt="Screen Shot 2020-04-15 at 7 42 12 PM" src="https://user-images.githubusercontent.com/58698642/79399768-35825080-7f52-11ea-8869-b0c842879c39.png">

This is how the original pdf file is rendered when I use SVG layer. The text is upside down and also flipped right to left. 
When I download the file, it gives me the correct file. 

Here is the original file. 

[4831d300-4b33-4098-857d-bf7321b407b6.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4484202/4831d300-4b33-4098-857d-bf7321b407b6.pdf)

**Comment by phuoc-ng** [comment]
Thanks for reporting the issue. I can confirm that it's a bug. It happens only with the SVG layer.

**Comment by phuoc-ng** [comment]
The SVG renderer of [pdf.js](https://github.com/mozilla/pdf.js/tree/master/examples/svgviewer) isn't stable at the moment.

<img width="1038" alt="Screen Shot 2020-04-16 at 23 55 48" src="https://user-images.githubusercontent.com/57786711/79684882-e0e71a00-825e-11ea-9019-58fec5a67fe5.png">

I don't think we can't do anything at the moment.

**Comment by wonjunkang** [comment]
@phuoc-ng 
Got it. Thanks for your quick response. 
Is there anyway we can improve the fuzzy fonts in canvas mode instead of svg until this issue is solved?

**Comment by phuoc-ng** [comment]
Closed. Will be tracked by #418
