### ISSUE TITLE
Select text from image PDF

### ISSUE THREAD

**Issue by IvanCoronado** [react-pdf-viewer/react-pdf-viewer#1147]
I have noticed that I can select or search text from some PDFs when they are images (even works with handwriting text).

Which library is doing this in the codebase? Can we modify this o creating a plugin for improving the algorithm?

**Comment by phuoc-ng** [comment]
We're using [pdf.js](https://github.com/mozilla/pdf.js/) as the library of parsing and rendering layers. You should add a GitHub issue to [pdf.js repos](https://github.com/mozilla/pdf.js/issues)
