### ISSUE TITLE
Add shortcuts for page navigation

### ISSUE THREAD

**Issue by kdv24** [react-pdf-viewer/react-pdf-viewer#1158]
I see there are shortcuts available for print, zoom, and other toolbar items. Would you also be able to add them for page navigation? Thank you!

**Comment by phuoc-ng** [comment]
Update: The feature was implemented and will be available in the next version.

**Comment by kdv24** [comment]
Thank you so much for implementing this, @phuoc-ng! Sorry I didn't see your question earlier.

**Comment by phuoc-ng** [comment]
@kdv24 [v3.5.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!
