### ISSUE TITLE
SVG layer problems on Safari

### ISSUE THREAD

**Issue by eduardofcgo** [react-pdf-viewer/react-pdf-viewer#117]
When using the SVG layer, scrolling is very laggy on Safari. The same does not happen in Chrome.
(Tested on MacBook Air Retina display)
Thanks!

**Comment by eduardofcbg** [comment]
Also on Safari this pdf is not rendered correctly

[sample.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4513276/sample.pdf)

<img width="374" alt="image" src="https://user-images.githubusercontent.com/7091654/79930014-4db90a80-843f-11ea-828c-fda809ce3aad.png">

**Comment by eduardofcbg** [comment]
Both of these problems do not happen in pdfjs on safari. Since react-pdf-viewer uses pdfjs why is this happening?
Thanks

**Comment by phuoc-ng** [comment]
The SVG rendering supported by pdfjs isn't stable. We should use the canvas layer instead.

**Comment by phuoc-ng** [comment]
Closed. Will be tracked by #418
