### ISSUE TITLE
Doesn't show up images included in the PDF

### ISSUE THREAD

**Issue by eugen-admortgage** [react-pdf-viewer/react-pdf-viewer#1188]
There is problem with images, instead of them showing blank area

sample: [https://i.imgur.com/14duClG.png](https://i.imgur.com/14duClG.png)

if that PDF doc open in chrome or acrobat reader that images are showed

**Comment by eugen-admortgage** [comment]
signatures doesn't show up too, may be this update pdf with signatures to last pdf.js verion ? now i can't test react-pdf dist with signatures because is too old for 3 version

**Comment by phuoc-ng** [comment]
@eugen-admortgage Can you give me the sample document?

**Comment by eugen-admortgage** [comment]
@phuoc-ng yeah, i sent to your email

**Comment by phuoc-ng** [comment]
Got it. Thanks @eugen-admortgage

**Comment by phuoc-ng** [comment]
I tried to open the document with [pdf.js viewer](https://mozilla.github.io/pdf.js/web/viewer.html), but I can't see the image (on page 6) and signature (on page 8).
So I guess it's a pdf.js issue. 
Can you file an issue for it on [pdf.js repository](https://github.com/mozilla/pdf.js/issues)?

**Comment by eugen-admortgage** [comment]
i opened that pdf in google chrome, and i see signatures on 6 page, and image on 12 page and so on, ok i try write that issue to pdf.js
