### ISSUE TITLE
Replace ambiguous/confusing download and upload icons in the toolbar

### ISSUE THREAD

**Issue by vipul-sharma-deshaw** [react-pdf-viewer/react-pdf-viewer#1189]
Hi, 

The current toolbar download and upload icons and their placement causes ambiguity as users sometimes confuse them for page navigation buttons.

Could we replace them with something more meaningful? For e.g. I have tried to come up with the following -
![image](https://user-images.githubusercontent.com/106318082/175918121-e34649a1-127d-485d-9d52-f1cfc583c4c6.png)

The SVG codes for these would be -
Upload icon - `M 12.5 4.5 L 12.5 19.5 M 18 10 L 12.5 4.5 L 7 10 M 7 20 H 18`
Download icon - `M 11.5 19.5 L 11.5 5 M 17 14 L 11.5 19.5 L 6 14 M 6 20 H 17`

Thanks!

**Comment by phuoc-ng** [comment]
Thanks for the suggestion. I am going to replace them with the following one

![Screen Shot 2022-06-27 at 18 48 11](https://user-images.githubusercontent.com/57786711/175934386-cd160aab-5177-416c-b45e-91acdb16e44c.png)

What do you think?

**Comment by vipul-sharma-deshaw** [comment]
Should we have horizontal bars at the bottom of the two icons, as when you google search for [download icon](https://www.google.com/search?q=download+icon&rlz=1C1GCEA_enIN986IN986&sxsrf=ALiCzsYBbLvGL_ROAO14GUVfBBUT25jPUg:1656331941696&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjO7o6ozc34AhXQ7HMBHa5RDfwQ_AUoAXoECAEQAw&biw=2560&bih=1297) and [upload icon](https://www.google.com/search?q=upload+icon&sxsrf=ALiCzsaOMUaHlDuUuCQMiKerhpmzPi55rQ:1656331914127&source=lnms&tbm=isch&sa=X&ved=2ahUKEwihnfyazc34AhW3ldgFHQYXAAQQ_AUoAXoECAEQAw&biw=2560&bih=1297), it is common to see some form of horizontal bar at the bottom of the two icons. Since this is common, this will add visible context for the users. What do you think?

**Comment by phuoc-ng** [comment]
Here are other options

![Screen Shot 2022-06-27 at 19 25 30](https://user-images.githubusercontent.com/57786711/175942556-921ecb29-e774-426e-9df1-7644cdcf9119.png)

![Screen Shot 2022-06-27 at 19 26 55](https://user-images.githubusercontent.com/57786711/175942562-303d488e-dbc1-4f75-8813-28d8a606c8f7.png)

**Comment by phuoc-ng** [comment]
![Screen Shot 2022-06-27 at 19 34 31](https://user-images.githubusercontent.com/57786711/175942931-74436e90-4ba7-40f0-a408-9307472c9e05.png)

**Comment by phuoc-ng** [comment]
![Screen Shot 2022-06-27 at 19 40 01](https://user-images.githubusercontent.com/57786711/175943883-01249e26-efe8-4db5-a540-ee90dd0fe7d6.png)

**Comment by vipul-sharma-deshaw** [comment]
I personally like this one -
![image](https://user-images.githubusercontent.com/106318082/175958163-133f2991-f4d4-49c8-b709-fd608ce3ecd2.png)

**Comment by mohsinulhaq** [comment]
+1 on @vipul-sharma-deshaw 's choice

**Comment by mohsinulhaq-deshaw** [comment]
+1 on @vipul-sharma-deshaw 's choice

**Comment by phuoc-ng** [comment]
@vipul-sharma-deshaw @mohsinulhaq-deshaw 
[v3.6.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade to see the changes.

**Comment by vipul-sharma-deshaw** [comment]
Thanks @phuoc-ng!
