### ISSUE TITLE
Search popover shows up even if PDF is not in focus/mouseenter

### ISSUE THREAD

**Issue by mohsinulhaq** [react-pdf-viewer/react-pdf-viewer#1193]
There's no way to trigger the browser's default find menu once a `react-pdf-viewer` is mounted.

This is due to a stale closure caused due to usage of the state variable here: https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/search/src/ShortcutHandler.tsx#L38

This can be solved by using a `ref` instead of the state so as to always get the latest value.

**Comment by phuoc-ng** [comment]
Thanks you! The fix will be included in the next release.

**Comment by phuocng** [comment]
Released in [v3.7.0](https://react-pdf-viewer.dev/updates/).
