### ISSUE TITLE
[Highlight plugin] "jumpToHighlightArea" does not work correctly with a certain book

### ISSUE THREAD

**Issue by michaeljsvs** [react-pdf-viewer/react-pdf-viewer#1195]
DESCRIPTION:
For the attached book "Alice_in_Wonderland.pdf", clicking on a sidebar note to jump to highlight area, does not jump to the correct page.

STEPS TO REPRODUCE THE PROBLEM:
1- Run the application
2- Go to page 2 of the book Alice_in_Wonderland
3- Highlight the word "ALICIA"
4- Add a note for the highlighted word
5- Click on Sidebar Notes, to view the added note
6- Go to page 5 of the book Alice_in_Wonderland
7- Click on the added note for the word "ALICIA", to jump to the highlighted area

BOOK:
[Alice_in_Wonderland.pdf](https://github.com/react-pdf-viewer/react-pdf-viewer/files/9073937/Alice_in_Wonderland.pdf)

ATTACHED A VIDEO:
https://user-images.githubusercontent.com/54175563/178041015-e0e2f487-27f9-4ab2-a492-bf92d1b7b410.mp4

ATTACHED VIDEO OF ANOTHER EXAMPLE:
https://user-images.githubusercontent.com/54175563/178041108-4c2eb0b5-8568-4eb7-91e5-0be24da297ca.mp4

**Comment by phuoc-ng** [comment]
@michaeljsvs 
Can you create a sample project based on [this one](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) that I can see the issue there?

**Comment by phuocng** [comment]
@michaeljsvs 
Update: The bug is fixed in the latest code, and I will include the fix in the next v3.8.0.

## Demo

https://user-images.githubusercontent.com/57786711/200154296-ac08f2de-6b88-4762-a4f9-9b060a95bba8.mp4

**Comment by phuocng** [comment]
@michaeljsvs 
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.

**Comment by vishvasartechnolabs** [comment]
Hi, I am currently encountering the same issue with the "jump-to-highlightarea" functionality not working in version 3.11

For reference, here is the repository: https://github.com/vishvasartechnolabs/pdf-viewer-react-01.git 
@phuocng 



https://github.com/user-attachments/assets/b67880b2-407c-4008-8948-34a53e8b004e

**Comment by higashi04** [comment]
> Hi, I am currently encountering the same issue with the "jump-to-highlightarea" functionality not working in version 3.11
> 
> For reference, here is the repository: https://github.com/vishvasartechnolabs/pdf-viewer-react-01.git @phuocng
> 
>  test.pdf.viewer.mp4

were you able to solve this? I am facing the same issue in ver 3.12.0
