### ISSUE TITLE
Build Error in Next.js application in production mode

### ISSUE THREAD

**Issue by choudhary-ankit** [react-pdf-viewer/react-pdf-viewer#1198]
I have a next.js project with pdf viewer. In development mode it looks fine, but on production it gives error.
This is the dependencies in my package.json:

    "@react-pdf-viewer/core": "^3.0.0",
    "@react-pdf-viewer/default-layout": `"^3.0.0",`
    "pdfjs-dist": "^2.12.313",

**This is the build error:**
![Selection_333](https://user-images.githubusercontent.com/61105107/178656745-2d0a9791-a343-4888-8110-3ba6d6756093.png)

**component**
![Selection_332](https://user-images.githubusercontent.com/61105107/178656841-d3187966-99c8-47a7-bdae-82fc35994912.png)

**Comment by abhinayar** [comment]
Is this a similar dependency issue to what exists  in `pdf-viewer-reactjs`? 
[https://github.com/ansu5555/pdf-viewer-reactjs/issues/85](url)

**Comment by choudhary-ankit** [comment]
@abhinayar I think that issues is closed, I can't find that 
issue through your link.

**Comment by phuoc-ng** [comment]
@choudhary-ankit Try to upgrade nodejs.
See https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/
