### ISSUE TITLE
Page navigation buttons not working

### ISSUE THREAD

**Issue by dimazaetc** [react-pdf-viewer/react-pdf-viewer#1200]
``` 
const toolbarPluginInstance = toolbarPlugin();
  const { Toolbar } = toolbarPluginInstance;

  return (
    <div>
      <Toolbar />
      <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.14.305/build/pdf.worker.min.js">
        <Viewer plugins={[toolbarPluginInstance]} fileUrl={fileUrl} />
      </Worker>
    </div>
  );
```

this id my package.json :
"pdfjs-dist": "^2.14.305",
    "@react-pdf-viewer/core": "^3.6.0",
    "@react-pdf-viewer/default-layout": "^3.6.0",
    "@react-pdf-viewer/page-navigation": "^3.6.0",
    "@react-pdf-viewer/rotate": "^3.6.0",
    
Page navigation buttons not working
 Nothing happens

**Comment by phuoc-ng** [comment]
@dimazaetc 
Can you fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) and reproduce the issue there?

**Comment by abettke** [comment]
I ran into this same issue recently. My problem was not setting a fixed height for the container of the Viewer.

#1260

**Comment by afrad** [comment]
Fixing the height of the container of the viwer fixes the issue, but is there a way to allow for relative height?

**Comment by phuocng** [comment]
> but is there a way to allow for relative height

It's not supported at the moment.
