### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by noorqidam** [react-pdf-viewer/react-pdf-viewer#1212]
Hello I get an error when installing
@react-pdt-viewer/core: 3.6.0
@react-pdf-viewer/default-layout: 3.6.0
pdfjs-dist: 2.6.347

the error message is as follows
![error](https://user-images.githubusercontent.com/45481403/182587072-289e0e05-e1ac-4fa7-b7ef-a2f40739306d.png)

here I am using react version 16.12.0 and webpack version 4, I have also adjusted pdfjs-dist to the latest versions or previous versions but have not found a solution

**Comment by phuocng** [comment]
@noorqidam 
See https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/
