### ISSUE TITLE
Is there a way to tie into the onClick function in bookmarks?

### ISSUE THREAD

**Issue by kdv24** [react-pdf-viewer/react-pdf-viewer#1213]
We'd like to close the bookmark window for mobile or small screen users once they click on a given bookmark. As it is, the bookmarks panel covers the mobile viewport enough that it's hard to have context.

**Comment by phuocng** [comment]
Thanks for your request. I will support it in the next version.

**Comment by kdv24** [comment]
That's fabulous! Thank you!

**Comment by phuocng** [comment]
@kdv24 The feature is implemented in the latest code, and will be included in the next v3.7.0.

## Demo

_Clicking a bookmark item will close the bookmark tab. You can do something else_

https://user-images.githubusercontent.com/57786711/184640544-9a6a1c17-4c53-4184-a133-79f184ba1c66.mp4

## API

You can see the sample code [here](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/default-layout-click-bookmark/index.tsx).

```tsx
const toggleBookmarkTab = () => {
    toggleTab(1);
};

const renderBookmarkItem = (renderProps: RenderBookmarkItemProps) =>
    renderProps.defaultRenderItem(
        renderProps.onClickItem,
        <>
            {renderProps.defaultRenderToggle(<ExpandIcon />, <CollapseIcon />)}
            {renderProps.defaultRenderTitle(() => {
                // ---> Executed when clicking a bookmark item
                renderProps.onClickTitle();
                toggleBookmarkTab();
            })}
        </>
    );

const defaultLayoutPluginInstance = defaultLayoutPlugin({
    ...
});

const { toggleTab } = defaultLayoutPluginInstance;
const bookmarkPluginInstance = defaultLayoutPluginInstance.bookmarkPluginInstance;
const { Bookmarks } = bookmarkPluginInstance;
```

**Comment by kdv24** [comment]
Great! Thank you @phuocng!

**Comment by kdv24** [comment]
@phuocng is this only available with the default layout and not with the bookmark plugin itself?

**Comment by phuocng** [comment]
@kdv24 The example is now available on the official website
https://react-pdf-viewer.dev/examples/execute-a-function-when-users-click-a-bookmark-item/
