### ISSUE TITLE
Be able to change the toggle icon

### ISSUE THREAD

**Issue by phuocng** [react-pdf-viewer/react-pdf-viewer#1216]
Feature requested by @kdv24 ([Comment](https://github.com/react-pdf-viewer/react-pdf-viewer/pull/594#issuecomment-1204268088))

**Comment by phuocng** [comment]
@kdv24 The feature is implemented in the latest code, and will be available to use in v3.7.0.

## Demo

![Screen Shot 2022-08-09 at 21 28 17](https://user-images.githubusercontent.com/57786711/183687764-232679ef-1599-4849-9547-5cac5850e341.png)

## API

We can customize bookmark item with the new `renderBookmarkItem` property:

```jsx
const renderBookmarkItem = (renderProps: RenderBookmarkItemProps) =>
    renderProps.defaultRenderItem(
        renderProps.onClickItem,
        <>
            {renderProps.defaultRenderToggle(<ExpandIcon />, <CollapseIcon />)}
            {renderProps.defaultRenderTitle(renderProps.onClickTitle)}
        </>
    );

<Bookmarks renderBookmarkItem={renderBookmarkItem} />
```

The `ExpandIcon` and `CollapseIcon` components represent the expand and collapse icons:

```jsx
import { Icon } from '@react-pdf-viewer/core';
import * as React from 'react';

const ExpandIcon = () => (
    <Icon size={16}>
        <path d="M.541,5.627,11.666,18.2a.5.5,0,0,0,.749,0L23.541,5.627" />
    </Icon>
);

const CollapseIcon = () => (
    <Icon size={16}>
        <path d="M5.651,23.5,18.227,12.374a.5.5,0,0,0,0-.748L5.651.5" />
    </Icon>
);
```

You can see the full sample code [here](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/bookmark-render-bookmark-item/index.tsx).

**Comment by kdv24** [comment]
Fabulous! Thank you. When do you expect to release v3.7.0?

**Comment by phuocng** [comment]
@kdv24 The example is finally available on its official website
https://react-pdf-viewer.dev/examples/customize-bookmark-items/
