### ISSUE TITLE
Clicking first bookmarks item bug

### ISSUE THREAD

**Issue by makranelhoucine** [react-pdf-viewer/react-pdf-viewer#1224]
Hello 

Clicking on first bookmarks item freezes pdfviewer and browser tab

I must close the current tab and open new one

FYI: Clicking other bookmarks doesn't cause this issue

I tried v3.3.2 and the last v3.6.0

**Comment by phuocng** [comment]
@makranelhoucine The issue is the same as #1218
It is fixed in the latest code, and will be included in the next release.

**Comment by makranelhoucine** [comment]
> @makranelhoucine The issue is the same as #1218 It is fixed in the latest code, and will be included in the next release.


Thank you

**Comment by phuocng** [comment]
Released in [v3.7.0](https://react-pdf-viewer.dev/updates/).
