### ISSUE TITLE
Scroll to position/coordinates in a page

### ISSUE THREAD

**Issue by FatmaAkram** [react-pdf-viewer/react-pdf-viewer#1230]
Is there a way to scroll to a specific position/coordinates in the pdf?

e.g. 
```
position = {
              pageIndex: 1,
              top: 33.0772,
              left: 35.5399,
}
```
or anything similar?

Thanks!

**Comment by phuocng** [comment]
It's possible. I will create an example for you!

**Comment by FatmaAkram** [comment]
@phuocng That would be extremely helpful!

**Comment by FatmaAkram** [comment]
@phuocng Any estimates about this?
I don't mean to rush you but It would be nice If you can suggest where to start and I can figure out the rest myself. I don't want you to do a complete example If that would take much of your time.

**Comment by phuocng** [comment]
@FatmaAkram I am sorry, I was so busy with the new v3.7.0.
Here is a [quick example](https://codesandbox.io/s/react-pdf-viewer-go-to-a-given-coordinate-f6ooyt).

**Comment by FatmaAkram** [comment]
@phuocng Way to go 🚀 👏 

Thanks a lot!

**Comment by Lori10** [comment]
> @FatmaAkram I am sorry, I was so busy with the new v3.7.0. Here is a [quick example](https://codesandbox.io/s/react-pdf-viewer-go-to-a-given-coordinate-f6ooyt).

Hello, this performs only vertical scrolling (based on the x-coordinate). Is it supposed to perform horizontal scrolling using the y-coordinate instead?
