### ISSUE TITLE
initialRotate state

### ISSUE THREAD

**Issue by RSharma-cohere** [react-pdf-viewer/react-pdf-viewer#1240]
For Viewer component we have initialPage as props, how can we have the same functionality for the initialRotate for eg. if we want to documents to be rotated in 270 direction?

**Comment by phuocng** [comment]
That's a good suggestion, @RSharma-cohere. I will support this request!

**Comment by alpfreda** [comment]
Yes, I agree with you, it's an important feature. 👏🏼 💯

**Comment by phuocng** [comment]
Update: The option is implemented in the latest code, and will be available in the next v3.8.0

```tsx
<Viewer initialRotation={90} />
```
