### ISSUE TITLE
[Bug] Safari-15.3 with pdfjs-dist-2.15.349 Crashing

### ISSUE THREAD

**Issue by alex-doculink** [react-pdf-viewer/react-pdf-viewer#1241]
**Environment:** 

"@react-pdf-viewer/core": "^3.7.0",
"@react-pdf-viewer/default-layout": "^3.7.0",
"next": "12.2.3",
"pdfjs-dist": "^2.15.349",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-redux": "^8.0.2"

**How to Replicate:**

> Open Safari (Version 15.3 (17612.4.9.1.8))
> Load Page w/ React PDF Viewer 

**Error/Call Stack:**

Unhandled Runtime Error
TypeError: key.split("+").at is not a function. (In 'key.split("+").at(-1)', 'key.split("+").at' is undefined)

Call Stack
<unknown>

webpackUniversalModuleDefinition@
eval

[native code]
./node_modules/pdfjs-dist/build/pdf.js

file:///Users/alex/Desktop/workplace/doculink-ux/.next/static/chunks/pages/dashboard/viewer/%5BdocumentId%5D.js (23050:5)
<unknown>

/_next/static/chunks/webpack.js (713:35)
__webpack_require__

file:///Users/alex/Desktop/workplace/doculink-ux/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@react-pdf-viewer/core/lib/cjs/core.js

/_next/static/chunks/pages/dashboard/viewer/%5BdocumentId%5D.js (17794:5)
<unknown>

**Sample Code:**
```
            <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.15.349/build/pdf.worker.js">
                <div style={{height: '100%'}}>
                    <Viewer
                        fileUrl={document}
                        plugins={[
                            defaultLayoutPluginInstance,
                        ]}
                        renderError={renderError}
                    />
                </div>
            </Worker>
```

Note: Downgrading to 2.12.313 fixes the issue.

**Comment by phuocng** [comment]
It is a pdf.js issue. See https://github.com/mozilla/pdf.js/issues/15007
pdfjs uses the Array's `at()` function which [isn't supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) in Safari 14.

There are two workarounds:

* Polyfill the `at()` function:

You can include the following script at the top of your page

```js
Array.prototype.at =  Array.prototype.at || function at(n) {
	// ToInteger() abstract op
	n = Math.trunc(n) || 0;
	// Allow negative indexing from the end
	if (n < 0) n += this.length;
	// OOB access is guaranteed to return undefined
	if (n < 0 || n >= this.length) return undefined;
	// Otherwise, this is just normal property access
	return this[n];
}
```
See [this page](https://github.com/tc39/proposal-relative-indexing-method#polyfill) for more information.

* Use the legacy build of pdf.js.
See the [Use the legacy path](https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/) section.

**Comment by melloware** [comment]
looks like PDF.js 2.16.105 just came out https://github.com/mozilla/pdf.js/releases/tag/v2.16.105

**Comment by phuocng** [comment]
Using the legacy version will fix the issue.
