### ISSUE TITLE
Current page keeps changing and resetting on page resize if defaultScale is 'SpecialZoomLevel.PageFit'

### ISSUE THREAD

**Issue by kdv24** [react-pdf-viewer/react-pdf-viewer#1245]
We have long pdfs (2000 pages) and for some reason if the defaultScale is set to PageFit, when we resize the browser window the current page input box and the percentage shown will update to different sizes.  Resizing the window to its original size will not return to the original page number.  I am not seeing this same thing with other defaultScale or with a fixed percent.

@phuocng thank you!

**Comment by kdv24** [comment]
@phuocng you can test this:

- drop a lengthy pdf into the demo viewer
- change the scale to 'Page fit'
- resize the window to a large size, then to very small, then back
- watch the current page input value change in the toolbar navigation
- repeat until you see the page number change

**Comment by Mohammad-aleik** [comment]
Same issue here

**Comment by kdv24** [comment]
Yes, @Mohammad-aleik I'm seeing it in vertical scrolling mode. Thanks for clarifying that.

**Comment by kdv24** [comment]
@phuocng is this something you are working on fixing right now? It feels like a significant issue.

**Comment by aldrichdev** [comment]
It is the `SpecialZoomLevel.PageFit` property, not just `PageFit` - maybe update your title and description, it confused me

**Comment by kdv24** [comment]
Okay. Thanks @aldrichdev. I updated the title. Does anyone know if this is likely to be addressed?

**Comment by phuocng** [comment]
The issue was fixed in the latest code and will be included in the next release.

# Before

https://user-images.githubusercontent.com/57786711/202852843-b293f1d9-e7d8-49e4-a7bb-da6d92dea7bb.mp4

## After

https://user-images.githubusercontent.com/57786711/202852980-bd82a2ec-c7b3-48b2-bb1e-80caffe0548d.mp4

**Comment by kdv24** [comment]
Thank you @phuocng! That's fabulous! 🎉

**Comment by phuocng** [comment]
Fixed in [v3.9.0](https://react-pdf-viewer.dev/updates/)
