### ISSUE TITLE
Bookmarks able to remember expanded/collapsed state individually within a session

### ISSUE THREAD

**Issue by kdv24** [react-pdf-viewer/react-pdf-viewer#1247]
The use case we have is our pdfs have many nested layers within the bookmarks.  If a user expands a number of bookmarks in order to get to one that's nested, it's an unpleasant experience to close the bookmarks then have to go through that same process to get back to the nested content. It seems like it should be possible to tie into the `isExpanded` or `isBookmarkExpanded` props and have the state of each tracked individually. I have been unable to do this from my end due to only certain pieces of the API being exposed for us. 

Is this an update you can make or am I missing a way we can do this from our end?  Thanks again for all your work on this @phuocng!

**Comment by phuocng** [comment]
@kdv24 
This feature request is implemented in the latest code and will be included in the next v3.8.0.
You don't have to do anything.

## Demo

https://user-images.githubusercontent.com/57786711/197550412-4b2e2dc6-5963-4441-bf37-f74e2053a865.mp4

The expanded/collapsed states are also kept when you switch to another tab and switch back to the Bookmark tab:

https://user-images.githubusercontent.com/57786711/197550550-ceb27e00-4a76-4da3-bb05-f1eda4c8f988.mp4

**Comment by kdv24** [comment]
That's fantastic! Thank you @phuocng.

**Comment by phuocng** [comment]
@kdv24 
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
