### ISSUE TITLE
Documentation: Add another option for keeping PDF.JS in sync

### ISSUE THREAD

**Issue by melloware** [react-pdf-viewer/react-pdf-viewer#1249]
You could add this to your documentation as another way of keeping versions in sync....

```ts
import package_json from '../package.json';

<Worker workerUrl={`https://unpkg.com/pdfjs-dist@${package_json.dependencies['pdfjs-dist']}/build/pdf.worker.js`}>
```

**Comment by phuocng** [comment]
@melloware Thanks a lot for the suggestion ❤️ 
I added a new [guide](https://react-pdf-viewer.dev/examples/keep-the-worker-version-in-sync-with-pdfjs-dist-version/).
