### ISSUE TITLE
Setting up fake worker failed: "Cannot load script at: http://localhost:3000/_next/static/chunks/pages/index.worker.js?ts=1663944878124".

### ISSUE THREAD

**Issue by burn-c** [react-pdf-viewer/react-pdf-viewer#1258]
Does anyone know this error?
![image](https://user-images.githubusercontent.com/54965836/191992067-1046210e-dec4-407b-93ad-b22c509f74ce.png)

Environment:
- @react-pdf-viewer/core": "^3.7.0"
- @react-pdf-viewer/default-layout": "^3.7.0
- pdfjs-dist": "^2.16.105"
- next": "^12.0.7"

**Comment by phuocng** [comment]
Please create a repos for that based on this https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut and [NextJS starter](https://github.com/react-pdf-viewer/starter/tree/main/nextjs/)
