### ISSUE TITLE
Getting Uncaught TypeError: Cannot read properties of null (reading 'useMemo') when trying to use a plugin  with create react app

### ISSUE THREAD

**Issue by afrad** [react-pdf-viewer/react-pdf-viewer#1265]
I'm using 3.7.0 
Using the code below 
```
const highlightPluginInstance = highlightPlugin({ trigger: Trigger.TextSelection });
const PdfViewer = () => {
    const defaultLayoutPluginInstance = defaultLayoutPlugin();

    return (
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.15.349/build/pdf.worker.js">
            <div
                style={{
                    height: '100%',
                    width: '100%',
                    marginLeft: 'auto',
                    marginRight: 'auto',
                }}
            >
                <Viewer
                    theme={{
                        direction: TextDirection.RightToLeft,
                    }}
                    fileUrl={`${process.env.PUBLIC_URL}/pdf-open-parameters.pdf`}
                    plugins={[defaultLayoutPluginInstance]}
                />
            </div>
        </Worker>
    );
};

export default PdfViewer;
```
I'm getting the following error bwlow. It works however when I remove the line 
`const highlightPluginInstance = highlightPlugin({ trigger: Trigger.TextSelection });`

react.development.js:1650 Uncaught TypeError: Cannot read properties of null (reading 'useMemo')
    at Object.useMemo (react.development.js:1650:1)
    at highlightPlugin (highlight.js:487:1)
    at ./src/PdfViewer.tsx (PdfViewer.tsx:25:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/App.tsx (bundle.js:18:68)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1

what I'm doing wrong?

**Comment by Heilemann** [comment]
I'm having this error. Since this was closed, was there a fix, @afrad?

**Comment by MikhailNarkevich** [comment]
@Heilemann in my case, moving the line below inside the component helped
```
// Create new plugin instance
const defaultLayoutPluginInstance = defaultLayoutPlugin();
```
