### ISSUE TITLE
Cover component doesn't rotate the corresponding rotated page

### ISSUE THREAD

**Issue by Vixan** [react-pdf-viewer/react-pdf-viewer#1266]
Greetings 👋. 

I'm trying to implement a couple of actions on individual document pages, such as move using drag and drop, deletion and rotation. I've managed to render pages using the `<Cover>` component and the custom plugin [approach illustrated here](https://react-pdf-viewer.dev/examples/display-the-thumbnail-of-a-given-page/), but I'm not sure how to render rotated pages properly.
I've noticed that some page data can be accessed by calling `doc.getPage(i)` in the `renderViewer` function of the plugin, but I don't know how to use it.

I know that using the `<Thumbnails>` component, rotated pages are displayed as expected, but I have no control over what pages are displayed before the document is actually updated on the backend as a result of the user actions. 
E.g. Let's say I want to move a page from a document to the end of another document. Using  `<Thumbnails>`, the newly dropped page will not be displayed as the original document does not contain it. This is the reason I'm using the `<Cover>` component with the custom plugin.

I've created a [CodeSandbox example](https://codesandbox.io/s/react-pdf-viewer-arrange-and-rotate-9jwxe6) of the implementation that I'm working on. Here you can see that the rotated thumbnail images are rendered with the correct sizes, but the content does not take rotation into account. 

![image](https://user-images.githubusercontent.com/35898772/194882711-6b98b03c-c7f4-416d-aaf4-9719e55bae4d.png)

Is there a way to have the `<Cover>` rotated as expected using the custom plugin or can you recommend me another approach? Thank you in advance.

**Comment by phuocng** [comment]
@Vixan 
It's a bug. Thanks for letting me know. The `Cover` component doesn't render properly a page that is already rotated.
I fixed it in the latest code and will include it in the next version v3.8.0.

## Before

<img width="738" alt="Screen Shot 2022-10-16 at 09 43 13" src="https://user-images.githubusercontent.com/57786711/196017270-0373b8a2-40f5-4744-8344-5e1b14256140.png">

## After

<img width="684" alt="Screen Shot 2022-10-16 at 10 01 13" src="https://user-images.githubusercontent.com/57786711/196017296-cf927dd5-14db-4724-847c-dfd681220daf.png">

**Comment by Vixan** [comment]
Thank you, @phuocng. Will try it out!

**Comment by Vixan** [comment]
@phuocng, is there an approximate release date for v3.8.0?

**Comment by phuocng** [comment]
Update: Cover one more use case where the `Cover` must be rotated when users rotate the corresponding page.

## Demo

https://user-images.githubusercontent.com/57786711/196223659-932b8b11-d52c-4a52-b1ce-06f21ef445f1.mp4

**Comment by Vixan** [comment]
Thank you. It would help me to know an approximate release date, but I will close this issue and try the changes when they're released.

**Comment by phuocng** [comment]
@Vixan [v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please update.

**Comment by Vixan** [comment]
> @Vixan [v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please update.

Thank you!
