### ISSUE TITLE
Blank screen on IOS 14.2 browsers

### ISSUE THREAD

**Issue by tomideso** [react-pdf-viewer/react-pdf-viewer#1268]
This Viewer causes entire screen to go blank in IOS 14.2 browsers

**Comment by tomideso** [comment]
![image](https://user-images.githubusercontent.com/83241016/195799771-0aac59f6-c2c2-4872-b53b-3d533d38e671.png)
it appears this is also happening on firefox browser on PC. i have attached the error in the console.

**Comment by phuocng** [comment]
Thanks you for reporting the issue, @tomideso 👍 
I don't have iOS 14.2 right now. 
- Does the issue happen on the latest version of iOS?
- Without any integrations, can you let me know if the issue happens with this sample example https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut on iOS 14.2?

**Comment by tomideso** [comment]
The issue is also happening on PC using firefox browser. Please check the screenshot I included.
My setup is with React CRA

**Comment by phuocng** [comment]
@tomideso 
I can see the example https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut works properly on Firefox

<img width="1792" alt="Screen Shot 2022-10-16 at 07 59 32" src="https://user-images.githubusercontent.com/57786711/196013032-5f37c28d-ff44-4eda-b27b-53fa24dd57d5.png">

Can you fork the example above and give me the steps to reproduce the issue?

**Comment by tomideso** [comment]
Here is the error i'm getting on Firefox 78.14.0esr
![image](https://user-images.githubusercontent.com/83241016/196184361-2303e31f-d27b-4d62-b65e-a94f6ef02d02.png)
![image](https://user-images.githubusercontent.com/83241016/196184699-3c4b8606-b0b8-4cf4-bec3-a2996df711e3.png)

**Comment by tomideso** [comment]
Thanks. it worked
