### ISSUE TITLE
Log warnings: Deprecated API usage: `title`-property on annotation, please use `titleObj` instead.

### ISSUE THREAD

**Issue by lucasgadams** [react-pdf-viewer/react-pdf-viewer#1296]
My console is filled with these warning messages from pdfjs:
```Deprecated API usage: `title`-property on annotation, please use `titleObj` instead.```

This happens every time I scroll the pdf. I'm wondering if I can either 1) fix the thing it is warning about or 2) suppress these warnings so they don't clog up my console. Is it possible to configure the pdfjs log level?

**Comment by phuocng** [comment]
@lucasgadams Can you give me the sample document?

**Comment by phuocng** [comment]
@lucasgadams Thanks for reporting the issue.
I can reproduce the issue

![Screenshot 2022-10-31 at 18 28 45](https://user-images.githubusercontent.com/57786711/198999025-9ada2880-2858-4afc-920e-585277599b41.png)

It was fixed in the latest code, and the warnings will disappear from the next v3.8.0.

**Comment by phuocng** [comment]
@lucasgadams 
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
