### ISSUE TITLE
Printing of multiple pages PDF not working

### ISSUE THREAD

**Issue by matteocorvaro** [react-pdf-viewer/react-pdf-viewer#1297]
Hi,
I cannot manage to print a PDF (loaded from byte array) that is composed by multiple pages.

It is displayed and also downloaded correctly. When I click at print i have only the first page.

I've checked the old issue #833 and the relative position trick did not help me.

I'm using the latest version of pdfjs and I'm displaying the Viewer inside a Material UI modal dialog.

What can be the cause? Is there a workaround?

Thanks

**Comment by phuocng** [comment]
@matteocorvaro Please fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) and let me know the steps to reproduce the issue.

**Comment by phuocng** [comment]
I can't reproduce the issue with your sample repos (See the screenshot below):

![Screenshot 2022-11-19 at 18 43 36](https://user-images.githubusercontent.com/57786711/202849083-35a203d0-0588-4fb6-b7b6-3065d5c27fc8.png)

It's worth taking a look at this [note](https://react-pdf-viewer.dev/examples/hide-unnecessary-elements-when-printing-a-document/) as well.
