### ISSUE TITLE
Checkboxes in search popup doesn't show pointer-hand icon on hover.

### ISSUE THREAD

**Issue by utkarsh22garg** [react-pdf-viewer/react-pdf-viewer#1298]
Hi,

When we hover over checkboxes present in search popup, they doesn't show pointer-hand icon. This feels odd from user interaction point of view. Can we make the pointer show hand icon on hover of checkboxes ?

![image](https://user-images.githubusercontent.com/31355903/198953476-c3cde59c-dec1-4d41-9a63-98a917c62f58.png)

[Codesandbox](https://codesandbox.io/s/react-pdf-viewer-forked-w7w5yb)

**Comment by phuocng** [comment]
Thanks, @utkarsh22garg for another great suggestion 👍.
I fixed it and will include the fix in the next v3.8.0.

**Comment by phuocng** [comment]
@utkarsh22garg 
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
