### ISSUE TITLE
Open file dialogue box does not allow to filter only .pdf files

### ISSUE THREAD

**Issue by utkarsh22garg** [react-pdf-viewer/react-pdf-viewer#1299]
Hi,

When we use open file dialogue box from the viewer toolbar, it list all the files, but selecting any file other than .pdf (like .pptx, .xlsx) fails with unknown error and does not give user a visual feedback. Can we add .pdf filter when open file dialogue box is opened ?

[Codesandbox](https://codesandbox.io/s/react-pdf-viewer-forked-w7w5yb)

**Comment by phuocng** [comment]
@utkarsh22garg 
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
