### ISSUE TITLE
Search popover should set keyword based on initial keyword

### ISSUE THREAD

**Issue by phuocng** [react-pdf-viewer/react-pdf-viewer#1304]
Setting the keyword initially highlights it on all pages

```js
const searchPluginInstance = searchPlugin({
  keyword: '...',
})
```

However, the search popover doesn't use the keyword and applies the conditions (_match case_ and _whole words_).
The _Previous_ and _Next_ match buttons don't navigate to the corresponding match.

**Comment by phuocng** [comment]
Expected behavior:

https://user-images.githubusercontent.com/57786711/199050778-10e8b257-6dfc-4254-91f5-2d0115d6dc80.mp4

**Comment by phuocng** [comment]
Done.

**Comment by mnakka9** [comment]
> Done.

Awesome thanks!

**Comment by kavitasingh1993** [comment]
any update on this
