### ISSUE TITLE
Support PDF Dist 3.0.279

### ISSUE THREAD

**Issue by melloware** [react-pdf-viewer/react-pdf-viewer#1305]
3.0.279 is now out and I think you need to change the package.json to support both.

```js
"pdfjs-dist": "^2.16.105 || ^3.0.279",
```

https://github.com/mozilla/pdf.js/releases/tag/v3.0.279

**Comment by phuocng** [comment]
Thanks @melloware 👍 
pdfjs 3.0.279 will be supported in the next version v3.8.0.

**Comment by phuocng** [comment]
@melloware 
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
