### ISSUE TITLE
pdfjs 2.15.349 issue: Errors encountered while trying to parse file: "Semi-colon expected"

### ISSUE THREAD

**Issue by qazwsxpawel** [react-pdf-viewer/react-pdf-viewer#1307]
Using the recommended `"version": "2.15.349"`, results in:
 
```
Errors encountered while trying to parse file
<elided...>/node_modules/pdfjs-dist/build/pdf.js
{:line 2118, :column 9, :message "Semi-colon expected"}
```

(`npm install pdfjs-dist@2.15.349`, as per https://react-pdf-viewer.dev/docs/getting-started/)

Please let advise or let me know if more info required!

Thanks!

**Comment by phuocng** [comment]
@qazwsxpawel 
1. Try to update NodeJS and Webpack 5
2. Try to use the legacy version
See https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/
