### ISSUE TITLE
The annotation link always navigates to next page

### ISSUE THREAD

**Issue by gzhanuo** [react-pdf-viewer/react-pdf-viewer#1311]
For example, when i click **solutions finder**, it should jump to page 15, but instead it jumps to page 16, you can see it on this site: [solution finder](https://ads.tiktok.com/business/creativecenter/doc/solution)
https://user-images.githubusercontent.com/46067632/200509456-ee3b018c-81a9-465d-8272-2cd08178b185.mp4

**Comment by phuocng** [comment]
Thanks @gzhanuo 👍 
I can reproduce the issue.

**Comment by phuocng** [comment]
@gzhanuo 
Update: The bug is fixed in the latest code, and will be included in the next v3.8.0.

## Demo

https://user-images.githubusercontent.com/57786711/200576484-f317c9f2-ed65-4f97-8093-3f4047f61570.mp4

**Comment by phuocng** [comment]
@gzhanuo 
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
