### ISSUE TITLE
Remove buttons from "Default Layout plugin"

### ISSUE THREAD

**Issue by Snotax** [react-pdf-viewer/react-pdf-viewer#1312]
Is it possible to remove certain features like "Download / Upload" from the Defaul Layout plugin without configuring each plugins and component for itself ?

**Comment by phuocng** [comment]
@Snotax 
Yes, it's possible. See this example https://react-pdf-viewer.dev/examples/create-a-toolbar-with-different-slots-for-the-default-layout/

**Comment by Snotax** [comment]
Awesome! Thank you very much.
