### ISSUE TITLE
[Question] Hightlight the first keyword on document load

### ISSUE THREAD

**Issue by mnakka9** [react-pdf-viewer/react-pdf-viewer#1318]
I have predefined keyword and once the PDF is loaded, I want to jump to first keyword that matched with the predefined one. How can I do this? my viewer is below, I have renderPage & docLoad -- I tried putting Highlight method on both of those methods, but it isn't working. Please help.

`<Viewer
                                    fileUrl={link}
                                    plugins={[defaultLayoutPluginInstance, searchPluginInstance]}
                                    renderPage={renderPage}
                                    onDocumentLoad={onDocumentLoad}
                                />`

**Comment by phuocng** [comment]
@mnakka9 I created this example for you
https://react-pdf-viewer.dev/examples/jump-to-the-first-match-of-pre-defined-keywords-automatically/
