### ISSUE TITLE
Note: pdfjs@3.0.279 has issues installing on Mac M1 (fix included)

### ISSUE THREAD

**Issue by lucasgadams** [react-pdf-viewer/react-pdf-viewer#1319]
Just adding this as a FYI. 

pdfjs@3.0.279 adds [canvas](https://github.com/Automattic/node-canvas) as a dependency (though it looks like it might be made [optional in the next release](https://github.com/mozilla/pdf.js/issues/15652)). Canvas doesn't have a native M1 prebuilt binary and so yarn install might break looking for it and trying to built it from source. You can fix it by installing the canvas dependencies manually, read this [thread](https://github.com/Automattic/node-canvas/issues/1733). 

For me I was able to fix it by:
`brew install pkg-config cairo pango libpng jpeg giflib librsvg`
This is a lot of dependencies.. I believe only `pkg-config cairo pango` are required but I just installed them all. 
`brew cleanup`
`brew doctor`
`rm -r node_modules/`
`yarn install`

**Comment by meseven** [comment]
Thank you @lucasgadams, it's works with pkg-config cairo pango packages.

**Comment by phuocng** [comment]
@lucasgadams @meseven 
Thanks a lot. I updated the [installation guide](https://react-pdf-viewer.dev/docs/getting-started/) based on your fix.
