### ISSUE TITLE
Change default Font of PDF Viewer

### ISSUE THREAD

**Issue by Snotax** [react-pdf-viewer/react-pdf-viewer#1320]
Is there a possibility to change the default font of the PDF Viewer. 
I'm using a variation of this example: https://react-pdf-viewer.dev/examples/create-a-toolbar-with-different-slots-for-the-default-layout/

Thanks for the awesome package!

**Comment by phuocng** [comment]
@Snotax React PDF Viewer uses the font inherited from the parent element by default.
It means that it will use the font which is set by your page.
In case you want to override, change it, you can set the `font-family` to the viewer element:

```css
.rpv-core__viewer {
  font-family: ....
}
```
