### ISSUE TITLE
After setting the initialPage, the initialpage is displayed and slides down a bit more than expected

### ISSUE THREAD

**Issue by Hornnie** [react-pdf-viewer/react-pdf-viewer#1321]
![image](https://user-images.githubusercontent.com/55722763/202599149-610b005c-e8dd-4b56-a945-868c08a9b8da.png)

and here is my code:
`<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.min.js">
      <div style={{ height: '100%' }}>
        <Viewer
          fileUrl={fileUrl}
          plugins={[
            getCustomizedLayoutSidebar,
            pageNavigationPluginInstance,
            highlightPluginInstance,
            zoomPluginInstance
          ]}
          initialPage={11}
          defaultScale={0.8}
        />
      </div>
    </Worker>`

so sorry if it is a stupide question

**Comment by Hornnie** [comment]
I have tried to call pageNavigationPluginInstance.jumpToPage(initialPage) in onDocumentLoad function. Its same problem

**Comment by phuocng** [comment]
@Hornnie Can you give me the sample document?
If not, I guess the document has pages with different dimensions. Can you confirm that?

**Comment by Hornnie** [comment]
thanks for your great support~ 
I can't give it to you because of the company's policy.

but I found a interest things, maybe can give you some tips.
![initialPage 12-2](https://user-images.githubusercontent.com/55722763/202879465-35d38ce1-cb09-4e65-94f9-ba748317fad8.png)
![initialPage 12](https://user-images.githubusercontent.com/55722763/202879467-f0a32240-6844-4e18-9b1b-b297f67d3621.png)
![initialPage 12-1](https://user-images.githubusercontent.com/55722763/202879468-02f8b666-80b3-43d0-9029-5fd8dfdf1b8a.png)
![after scroll page to page 10](https://user-images.githubusercontent.com/55722763/202879469-77b4c86b-a36d-4863-a6d1-03dc3467d782.png)

**Comment by Hornnie** [comment]
after i scroll page or click the previous page/next page ,the height is normal

**Comment by phuocng** [comment]
The issue could happen with a document whose pages have different dimensions. I fixed it in the latest code and will include it in the next v3.9.0.

**Comment by Hornnie** [comment]
Great!!!
When v3.9.0 happen ?

**Comment by Hornnie** [comment]
hi @phuocng ,I have other question about the onDocumentLoad function.
This is the document load when the breakpoint is hit onDocumentLoad func, so look like the textLayer or canvasLayer its not fully loaded..........

![image](https://user-images.githubusercontent.com/55722763/202889627-3924c1f9-1eae-4a84-93b6-104bbe0ba2cd.png)

**Comment by phuocng** [comment]
1. If you have another question, please create a new issue.
2. The `onDocumentLoad` event is triggered when the document is loaded (the document instance, `doc`, is available, so we can do something with it).
It doesn't have anything related to the text/canvas layer.
If you want to do something when the text/canvas is rendered, you have to create a custom plugin.

**Comment by phuocng** [comment]
Fixed in [v3.9.0](https://react-pdf-viewer.dev/updates/)
