### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by NrmlPtl** [react-pdf-viewer/react-pdf-viewer#1329]
Can I create a custom theme or edit colors of existing themes?

**Comment by phuocng** [comment]
All colors, and spacings are defined by CSS variables:

<img width="602" alt="Screenshot 2022-11-21 at 21 09 04" src="https://user-images.githubusercontent.com/57786711/203075550-a4caf887-cb85-46e4-a400-5b8de99fe889.png">

You can override these variables to create a custom theme.
