### ISSUE TITLE
The Viewer keeps scrolling and resetting when we upload a PDF document

### ISSUE THREAD

**Issue by mridul037-actyv** [react-pdf-viewer/react-pdf-viewer#1332]
`import { Viewer, Worker, SpecialZoomLevel } from '@react-pdf-viewer/core';`

<img width="926" alt="Screenshot 2022-11-22 at 1 05 22 PM" src="https://user-images.githubusercontent.com/110530495/203253323-f40d6cce-e2e7-403e-ad7e-b014ce65f8c7.png">

**Comment by phuocng** [comment]
@mridul037-actyv Can you fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) and let me know the steps to reproduce the issue?
