### ISSUE TITLE
Can't find variable: structuredClone - Safari (14.1.2)

### ISSUE THREAD

**Issue by meseven** [react-pdf-viewer/react-pdf-viewer#1334]
**Environment**

```json

"dependencies": {
  "@react-pdf-viewer/core": "^3.8.0",
  "@react-pdf-viewer/default-layout": "^3.8.0",
  "pdfjs-dist": "^3.0.279",
  "react": "^18.2.0"
}
```

**How to Replicate**
Open Safari (Version 14.1.2 (16611.3.10.1.6))
Load Page w/ React PDF Viewer

**Error Object**
```json
{
  "message": "Can't find variable: structedClone",
  "name": "ReferenceError"
}
```

How can i fix this?

**Comment by phuocng** [comment]
@meseven See this guide 
https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/
