### ISSUE TITLE
How to apply license key?

### ISSUE THREAD

**Issue by alex-i-web** [react-pdf-viewer/react-pdf-viewer#1335]
@phuocng Hello
I try to find out how to use the license key (we purchased Organizations license) but I don't see property or config in the code to apply for the license on my production server. Could you please details this moment?

Thank you

**Comment by phuocng** [comment]
@alex-i-web The license key will be required, starting from v4.x.
You will see the notification via GitHub/email when it comes.

**Comment by alex-i-web** [comment]
Thanks!
