### ISSUE TITLE
Is it possible to use fileUrl from remote resource?

### ISSUE THREAD

**Issue by alex-i-web** [react-pdf-viewer/react-pdf-viewer#1338]
Hello, @phuocng 

I have my own amazon bucket with agreements documents
Now I get an error "Failed to fetch" on the pdf viewer component if I use this link (even using property withCredentials={true})

I am getting a 200 status code in the browser when loading this resource, but have an error on component

**Comment by phuocng** [comment]
@alex-i-web @paulosjunior7
I just created this guide for you
https://react-pdf-viewer.dev/examples/view-documents-from-remote-servers/
