### ISSUE TITLE
Cors problem with remote pdf

### ISSUE THREAD

**Issue by lillogoal** [react-pdf-viewer/react-pdf-viewer#1339]
Hi,

i'm using latest version of react-pdf-viewer and all plugins.

  "pdfjs-dist": "^3.0.279",
  "@react-pdf-viewer/core": "3.8.0",
    "@react-pdf-viewer/default-layout": "3.8.0",
    "@react-pdf-viewer/drop": "3.8.0",
    "@react-pdf-viewer/full-screen": "3.8.0",
    "@react-pdf-viewer/highlight": "3.8.0",
    "@react-pdf-viewer/locale-switcher": "^3.8.0",
    "@react-pdf-viewer/locales": "^1.0.0",
    "@react-pdf-viewer/open": "3.8.0",
    "@react-pdf-viewer/page-navigation": "3.8.0",
    "@react-pdf-viewer/print": "3.8.0",
    "@react-pdf-viewer/scroll-mode": "^3.8.0",
    "@react-pdf-viewer/search": "3.8.0",
    "@react-pdf-viewer/toolbar": "3.8.0",
    "@react-pdf-viewer/zoom": "3.8.0",

And i'm using this library with react version: "^17.0.1"

This problem doesn't happen to all of my clients, but to 2 people in particular. We tried to clean the cache etc... I contacted digital ocean who made me do these tests, as well as verifying the configuration of the courses on the server and everything is ok.
It may be that you make a fetch request without putting the header:
Access-Control-Allow-Origin ?

![IMG_20221114_163258](https://user-images.githubusercontent.com/4365815/205070577-d1bed7f2-c8ce-4fca-a166-72c0b019c1b5.jpeg)

**Comment by paulosjunior7** [comment]
I have the same problem

**Comment by phuocng** [comment]
@lillogoal @paulosjunior7 
Please see this guide
https://react-pdf-viewer.dev/examples/view-documents-from-remote-servers/

**Comment by phuocng** [comment]
@lillogoal You have to enable CORS on the server side.

Follow the guides below if you are using their services
 
* Amazon S3: https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html
* Asuze Storage: https://learn.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services

If you are using DigitalOcean Space, then follow its guide
https://docs.digitalocean.com/products/spaces/how-to/configure-cors/

**Comment by lillogoal** [comment]
Yes i contacted my provider (Digital ocean), they didn't have any problem. I checked my configuration and it is ok.
the only thing they told me to check the presence of that parameter in the request header. ---> Access-Control-Allow-Origin : "*"  @phuocng

**Comment by phuocng** [comment]
@lillogoal Can you give me the full URL of the document?
If it has some private information, can you upload a sample document to your DigitalOcean, and I can give it a try?

**Comment by lillogoal** [comment]
Sorry but it is private. the problem is that I can't reproduce it, while one of my clients is like in the screenshots. He also tried with multiple different browsers (chrome, firefox)

**Comment by lillogoal** [comment]
@phuocng any updates ? Thank you

**Comment by HasanYousef** [comment]
i have the same issue
