### ISSUE TITLE
PDF is not displayed on some recent modern browsers because of private fields support

### ISSUE THREAD

**Issue by fmigot** [react-pdf-viewer/react-pdf-viewer#1342]
Hey @phuocng,

Thanks again for your amazing work :D

We are now using you lib in our different applications and it's already in production 💪 
Unfortunately, some of our customers have encountered some issues and after investigation we found the root cause in your lib.

### ℹ️  Context/Need

Display a PDF on modern browsers thanks to your lib that is based on *pdfjs-dist*.

### 🐛  Issue

Our application fails to display a PDF **on certain version of modern browsers**, and we simply reproduce the error on your own following [page](https://react-pdf-viewer.dev/docs/basic-usage/) on Firefox 89.
You can find the error log into the console:

![image (1)](https://user-images.githubusercontent.com/15667911/205887674-97ee67b5-1095-4463-81d9-8f72d5386fd7.png)

### 🔥 Reason of the issue

The error comes from the library *pdfjs-dist* which is using private fields (#) but if you check [caniuse](https://caniuse.com/?search=private%20fields),  you can notice that private fields are not supported on recent modern browsers such as Firefox 89 (2021) or Safari 14.4 on iOS (2021) which is mostly used by our customers.

This is one of the reason for which it exists a legacy version of pdf.js of *pdfjs-dist* and it's of course maintained!

#### ♻️  Use the legacy version in your code

You refer to *pdfjs-dist* in *core.js* as `var PdfJsApi = require('pdfjs-dist')`.
If you use instead: `var PdfJsApi = require('pdfjs-dist/legacy/build/pdf.js')`, it will work. We tested it with a JS stop execution 👍 

That solution is simple because the purpose of the legacy version of *pdfjs-dist* is to be used to support up to 1 to 3 years of modern browsers.

#### 📦  Provide a specific build

Based on your application build system. It might be interested to provide in the same way as *pdfjs-dist* does a legacy version of your project where the difference will only be that require in *core.js*.

#### 🤷‍♂️  Else...

I hope that everything is clear! Let me now otherwise :)

**Note**: in the meantime, we may consider forking your lib just to fix the require call as mentioned in the first solution but we really don't want to come to this for several logical reasons ^^

Let's keep in touch,
Florian

**Comment by JClackett** [comment]
Yes please, getting so many messages from customers with this exact error

**Comment by phuocng** [comment]
@fmigot @JClackett 
Please follow this guide to use the legacy version https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/

**Comment by fmigot** [comment]
Awesome!! Thanks for pointing me the documentation, I will try out your fix proposal 🤞

**Comment by fmigot** [comment]
All right! Everything is good on my side, I did something a little bit different from your [doc](https://react-pdf-viewer.dev/examples/compile-and-set-the-worker-source-with-webpack/) because I'm getting also the legacy worker from the lib *pdfjs-dist* on my own.

If this can help anyone, please find below my files:

webpack.config.js
```js
const paths = require('./paths')

module.exports = webpackEnv => {
  return {
    [...],
    plugins: [
      // Replace `pdfjs-dist` request from `@react-pdf-viewer/core/lib/cjs/core.js`
      // by the legacy one to keep the app running on not so old recent browsers (..., 2020, 2021)
      new webpack.NormalModuleReplacementPlugin(
        /^pdfjs-dist$/,
        resource => {
          resource.request = paths.legacyPdfJs;
        },
      ),
    ]
  }
}
```

paths.js
```js
const fs = require('fs')
const path = require('path')

const appDirectory = fs.realpathSync(process.cwd())
const resolvePath = relativePath => path.resolve(appDirectory, relativePath)

module.exports = {
  appPath: resolvePath('.'),
  legacyPdfJs: resolvePath('node_modules/pdfjs-dist/legacy/build/pdf.js'),
  [...]
};
```

ContractViewer.tsx
```tsx
import React from 'react'
import pdfjsWorker from 'pdfjs-dist/legacy/build/pdf.worker.entry'

const ContractViewer = (props: ContractViewerProps) => {

  [...]

  return (
    <div className="contract-viewer">
      <Worker workerUrl={pdfjsWorker}>
        [...]
      </Worker>
    </div>
  )
}

export default ContractViewer
```

I close the issue!

Thanks again for you quickly answer 💯
