### ISSUE TITLE
Safari "TypeError c.split("+").at is not a function." Problem (URGENT)

### ISSUE THREAD

**Issue by BerkD145** [react-pdf-viewer/react-pdf-viewer#1352]
While the app is launching on older versions of the safari (v15 and below)  I'm getting this error and whole page is not visible. Whole app is crashing and not displaying anything.

`TypeError: c.split("+").at is not a function. (In 'c.split("+").at(-1)', 'c.split("+").at' is undefined)`

Stacktrace is indicating the problem coming from pdf.js. 
I was using this : 

` <Worker workerUrl="https://unpkg.com/pdfjs-dist@3.1.81/build/pdf.worker.min.js">`

I found on one of the threads they are suggesting using a legacy version of the pdf worker and I moved my implementation on the index.tsx and change it to a legacy like this : 

`<Worker workerUrl="https://unpkg.com/pdfjs-dist@3.1.81/legacy/build/pdf.worker.min.js">`

but that didn't solve my problem.

**Comment by phuocng** [comment]
@BerkD145 
You have to use the legacy version by adjusting your Webpack configuration as well.

See the __Use the legacy path__ section in https://react-pdf-viewer.dev/examples/how-to-solve-the-syntax-error-unexpected-token-issue/
