### ISSUE TITLE
Invalid PDF Structure

### ISSUE THREAD

**Issue by pedroriosg** [react-pdf-viewer/react-pdf-viewer#1354]
Hi, i cant solve this problem yet, any ideas to fix it?

![Captura de pantalla de 2022-12-17 19-06-05](https://user-images.githubusercontent.com/69609154/208267659-f0409d59-689a-47ab-bfc4-c20367dc3cf5.png)
![Captura de pantalla de 2022-12-17 19-05-36](https://user-images.githubusercontent.com/69609154/208267660-7b73388c-2b8d-4365-83fa-265f08cfa2e4.png)
![Captura de pantalla de 2022-12-17 19-05-25](https://user-images.githubusercontent.com/69609154/208267661-f08aa3c1-6bc9-4a72-9193-13e316358114.png)

Thanks!

**Comment by phuocng** [comment]
Can you give me the document?
