### ISSUE TITLE
Change visual design protected document

### ISSUE THREAD

**Issue by timur-pimkin-finsight** [react-pdf-viewer/react-pdf-viewer#1386]
I want to change the visual design protected document. I need to add a new text block and other visual changes. place on the screenshot. How I can do it?
<img width="399" alt="image" src="https://user-images.githubusercontent.com/72605191/210765041-b3753e70-e131-4a1c-a539-1e53386fc6d4.png">

**Comment by phuocng** [comment]
That's a great question. I will support it in the next version.

**Comment by phuocng** [comment]
Update: The request was implemented in the latest code.

## Demo

https://user-images.githubusercontent.com/57786711/214283651-7b08e313-160f-4a89-8229-071f3a062f7e.mp4

## API

```tsx
import { RenderProtectedViewProps, Viewer } from '@react-pdf-viewer/core';

const ProtectedView: React.FC<RenderProtectedViewProps> = ({ passwordStatus, verifyPassword }) => {
    ...
};

<Viewer renderProtectedView={ProtectedView} />
```

You can see the sample code [here](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/core-render-protected-view/index.tsx).

**Comment by timur-pimkin-finsight** [comment]
Thx for your work.

**Comment by phuocng** [comment]
Please upgrade to the [v3.11.0](https://react-pdf-viewer.dev/updates/). Here is the live example
https://react-pdf-viewer.dev/examples/customize-the-protected-view/
