### ISSUE TITLE
Navigation not working on single page JS react app

### ISSUE THREAD

**Issue by Jeremy-Stocktake** [react-pdf-viewer/react-pdf-viewer#1391]
[Archive.zip](https://github.com/react-pdf-viewer/react-pdf-viewer/files/10402747/Archive.zip)

I have been investigating various ways to view PDF files in react, and have come across an issue I cannot resolve. Whilst your demos are all using Typescript, I am using JavaScript and I wonder if that is the reason for the issue I am seeing. Attached is a minimal react app showing the problem.

If you run it, then the scrolling by page doesn't work, you simply see all the pages of the PDF in one go, so the 'next/previous page' buttons don't work. I really want the single page view, using the page navigation to navigate the document.

Thanks

**Comment by phuocng** [comment]
It's a known issue, if you don't place `Viewer` inside a container with fixed height.

```tsx
<div style={{ height: '750px' }}>
  <Viewer ... />
</div>
```

**Comment by Jeremy-Stocktake** [comment]
Wonderful, thanks. I must have missed that when reviewing the docs/samples.
