### ISSUE TITLE
Pdf worker problem

### ISSUE THREAD

**Issue by lillogoal** [react-pdf-viewer/react-pdf-viewer#1421]
Hi,

i'm using this version of react-pdf-viewer and all plugins:

"pdfjs-dist": "^3.0.279",
"@react-pdf-viewer/core": "3.8.0",
"@react-pdf-viewer/default-layout": "3.8.0",
"@react-pdf-viewer/drop": "3.8.0",
"@react-pdf-viewer/full-screen": "3.8.0",
"@react-pdf-viewer/highlight": "3.8.0",
"@react-pdf-viewer/locale-switcher": "^3.8.0",
"@react-pdf-viewer/locales": "^1.0.0",
"@react-pdf-viewer/open": "3.8.0",
"@react-pdf-viewer/page-navigation": "3.8.0",
"@react-pdf-viewer/print": "3.8.0",
"@react-pdf-viewer/scroll-mode": "^3.8.0",
"@react-pdf-viewer/search": "3.8.0",
"@react-pdf-viewer/toolbar": "3.8.0",
"@react-pdf-viewer/zoom": "3.8.0",

And i'm using this library with react version: "^17.0.1"

I have a problem with pdf.worker from today.

Setting up fake worker failed: "Cannot load script at: https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js"

I need your help.
THanks

**Comment by phuocng** [comment]
Please fork this [repos](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) so I can try it.

**Comment by lillogoal** [comment]
So do i need to update pdf.js dist and worker ?

**Comment by phuocng** [comment]
Please update your versions in the `package.json` of forked repo.

**Comment by lillogoal** [comment]
now it works with the original (post) version, i don't know why

**Comment by phuocng** [comment]
Thank you!
