### ISSUE TITLE
Doesn't render new pages

### ISSUE THREAD

**Issue by timur-pimkin-finsight** [react-pdf-viewer/react-pdf-viewer#1425]
Hello, I have two problems:
1) After the scroll first pages, I don't have any updates to the pages
2) Doesn't work navigation buttons

https://user-images.githubusercontent.com/72605191/217335738-c2c19072-fd61-431f-b76c-74e0fbe56e50.mov

It happens after the update to the 3.10.0 version. Maybe you know how to fix that?
This Video recorded is on the 3.11.0 version.

**Comment by phuocng** [comment]
It's a common issue. See https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1391#issuecomment-1382357981

**Comment by timur-pimkin-finsight** [comment]
I try but It's not helpful for me. I have height under Viewer but I have the same problem. It will be because I use React Portal Wrapper?

**Comment by timur-pimkin-finsight** [comment]
Thx
