### ISSUE TITLE
Worker custom rendering strategy

### ISSUE THREAD

**Issue by AlejandroGutierrezB** [react-pdf-viewer/react-pdf-viewer#1427]
Hi,

Is there a way to increase the amount of pages rendered by the worker? As right now seems to be rendering something like the current page and a couple pages backwards and forward.

I will like to do something like always render the first 30 pages, would that be possible?

**Comment by phuocng** [comment]
It's not possible to customize the number of pre-render pages (that is 6 at the moment). 
I will support your request soon.

**Comment by phuocng** [comment]
@AlejandroGutierrezB 
The request is implemented, and it will be available in the next version (v3.12.0).

```tsx
import type { SetRenderRange, VisiblePagesRange } from '@react-pdf-viewer/core';

const setRenderRange: SetRenderRange = React.useCallback((visiblePagesRange: VisiblePagesRange) => {
    return {
        startPage: visiblePagesRange.startPage - 10,
        endPage: visiblePagesRange.endPage + 10,
    };
}, []);

// Another usage: render the first 30 pages initially
const setRenderRange: SetRenderRange = React.useCallback((visiblePagesRange: VisiblePagesRange) => {
    return {
        startPage: visiblePagesRange.endPage <= 30 ? 0 : visiblePagesRange.startPage - 5,
        endPage:
            visiblePagesRange.startPage <= 30
                ? Math.max(30, visiblePagesRange.endPage + 5)
                : visiblePagesRange.endPage + 5,
    };
}, []);

<Viewer setRenderRange={setRenderRange} />;
```

In the following screenshot, the first 30 pages are rendered initially:

![Screenshot 2023-02-18 at 11 48 12](https://user-images.githubusercontent.com/57786711/219848221-377bb63f-f1d8-4b67-804f-aaca3a752363.png)

**Comment by AlejandroGutierrezB** [comment]
That is awesome thanks a lot!

**Comment by phuocng** [comment]
[v3.12.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!
