### ISSUE TITLE
rendering a single thumbnail with custom width (up to maximum)

### ISSUE THREAD

**Issue by levkany** [react-pdf-viewer/react-pdf-viewer#1428]
i am trying to render a single thumbnail for a page,
the current thumbnail changes when the page number is changed.
this works great, but the image is very blurry and its size is super small, 

is there any way to render it with custom width?
ps, i am using the `<Cover>` component

![image](https://user-images.githubusercontent.com/58599501/217811770-603f37c5-e968-4108-95c5-16a35d245ad3.png)

**Comment by phuocng** [comment]
Currently, the `Cover` component takes the full width of its container.

**Comment by levkany** [comment]
just to understand, if i set its parent style to width: 700px,
the `cover` component will be 700px?

**Comment by phuocng** [comment]
By default, the `Cover` will calculate to fit the thumbnail inside its container.
The next version (3.12.0) will provide new `width` property, so you can explicitly set the width for `Cover`.

For example:

```tsx
<div
    style={{
        minHeight: '20rem',
        width: '20rem',
    }}
>
  <Cover getPageIndex={() => 0} width={300} />
</div>
```

will produce a cover whose width is 300px:

![Screenshot 2023-03-12 at 10 58 14](https://user-images.githubusercontent.com/57786711/224523648-5f830500-2e8f-410e-b233-b12848361c93.png)

Here is the [full sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/thumbnail-cover-width/index.tsx#L33).

**Comment by phuocng** [comment]
[v3.12.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade! The `Cover` component provides new `width` option.
