### ISSUE TITLE
onClick not firing on highlight area

### ISSUE THREAD

**Issue by stmhull** [react-pdf-viewer/react-pdf-viewer#1436]
I can't seem to get onClick to register on a highlight area unless I bump the z-index up, but that interferes with highlighting text to copy/paste if the text to copy starts with a highlight. I can't seem to click on a highlight to jump to a note in the highlight documentation, either, where it's supposed to jump to a note when you click on it. Any help is greatly appreciated, thank you.

**Comment by phuocng** [comment]
@stmhull Yes, it seems a bug with recent changes.
It's not easy to support both triggering the `onClick` and selecting the underline text at the same time. One of the approaches that I use in a production application is to add an icon on the right side of the corresponding page.

The following screenshot will give you an idea:

![Screenshot 2023-02-26 at 18 41 47](https://user-images.githubusercontent.com/57786711/221408596-7a18717a-d3bd-4f1e-b1ec-7a1300e92911.png)

1. I updated the highlight sample code. You can see the most important part [here](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/highlight/index.tsx#L206-L231)

2. If you want the note icon to be displayed fully on the right side, then you have to add this CSS

```css
.rpv-core__page-layer {
  overflow: visible;
}
```

The next v3.12.0 version will do this step for you!

**Comment by phuocng** [comment]
[v3.12.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!
