### ISSUE TITLE
how to custom download button in default plugin layout

### ISSUE THREAD

**Issue by noorqidam** [react-pdf-viewer/react-pdf-viewer#1446]
how to custom download button in default plugin layout
because i want to call api from the click of the button
<img width="340" alt="image" src="https://user-images.githubusercontent.com/45481403/223022117-82f5ebf6-76f1-4500-b3ea-8f24b752daf6.png">

**Comment by phuocng** [comment]
You can replace the _Download_ button in the default toolbar with your own button.
Get to know Toolbar slots:
https://react-pdf-viewer.dev/examples/toolbar-slot/

then take a look at these examples:
https://react-pdf-viewer.dev/examples/customize-the-default-toolbar/
https://react-pdf-viewer.dev/examples/create-a-toolbar-with-different-slots-for-the-default-layout/
