### ISSUE TITLE
Next Page, Previous Page

### ISSUE THREAD

**Issue by bentsen** [react-pdf-viewer/react-pdf-viewer#1452]
Hey I seem to have a problem, i cant get the nextPage and Previous Page onClick to work. It seems to notice page switch with The CurrentPageLabel and the botton also work with the props.isDisabled. I have tried useing the default toolbar and the same problem seems to appear. I have also tried with a simple toolbar setup from your examples. Do you have any idea why this problem occour for me?

https://user-images.githubusercontent.com/78900612/224034626-2e6fb1b8-1a40-4133-9c99-d3269ad7a598.mov

**Comment by bentsen** [comment]
I also have the same problem with the navigation in Search, it dosent move when i click on eg. JumpToNextMatch

**Comment by phuocng** [comment]
If you have a problem with jumping to the next/previous page or searching matches, then the root cause is that you don't place the `Viewer` inside a fixed-height container.

It's mentioned in the docs:

```tsx
<div style={{ height: '700px' }}>
  <Viewer />
</div>
```

**Comment by bentsen** [comment]
yes it solved the problem thank you very much for the help!
