### ISSUE TITLE
Enquiries on Licenses for React PDF Viewer

### ISSUE THREAD

**Issue by whneo97** [react-pdf-viewer/react-pdf-viewer#1473]
Hi, 

I would like to make the following enquiries regarding the available licenses for the React PDF Viewer:

1. What is the difference between the developer, organisational and OEM license? 

2. The end product requires the PDF Viewer to be used as a small component within a larger application for clients (companies) to be able to view PDFs for their own business operations. Would a single organisational license suffice?

3. For the organisational license, would it be correct that the developing team just needs a single one-time license purchased to be able to include the PDF viewer within the end product? 

4. If the clients are businesses (using the application as end users rather than for purposes of further development), would it be correct to say that they do _not_ require licenses to run the application containing the PDF viewer?

5. Package installation aside, will the license/ verification step of the license/ licensed product require any internet connection during the end product's runtime? (The end product may require the PDF React Viewer to function in an environment without internet connection.)

Thank you!

**Comment by youngjunkim-kyj-genesislab** [comment]
how was the follow up ??
