### ISSUE TITLE
I am on v 3.12.0 and i cant create spacing between pages

### ISSUE THREAD

**Issue by netefJustice** [react-pdf-viewer/react-pdf-viewer#1480]
![picture for referance](https://user-images.githubusercontent.com/124575938/227781402-324260c2-4807-4d18-81b0-57aac3d3ca5f.jpg)

this is my code:
const PDFViewer = ({
    onDocumentLoad,
    fileUrl,
    renderPage,
    plugins,
    onZoom,
    renderLoader,
    defaultScale,
    onPageChange,
}) => {
    const pageLayout = {
        buildPageStyles: () => ({
            alignItems: "center",
            display: "flex",
            justifyContent: "center",
        }),
        tranformSize: ({ size }) => ({
            height: size.height + 30,
            width: size.width + 30,
        }),
    };

    return (
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@3.4.120/build/pdf.worker.min.js">
            {fileUrl ? (
                <Viewer
                    pageLayout={pageLayout}
                    defaultScale={defaultScale || 1.0}
                    fileUrl={fileUrl}
                    renderPage={renderPage}
                    onPageChange={onPageChange}
                    plugins={plugins}
                    onDocumentLoad={(doc) => {
                        onDocumentLoad(doc);
                    }}
                    onZoom={onZoom}
                    renderLoader={renderLoader ?? null}
                />
            ) : (
                false
            )}
        </Worker>
    );
};

export default PDFViewer;

why am i getting 0 gap between the pages?

**Comment by phuocng** [comment]
@netefJustice Can you fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut), so I can see the issue?

**Comment by netefJustice** [comment]
hi i changed the code inside so it will match mine, as you can see 
tranformSize: ({ size }) => ({
height: size.height + 30,
width: size.width + 30,
}),
does nothing

**Comment by phuocng** [comment]
Please create a sandbox so I can see the issue.

**Comment by netefJustice** [comment]
https://codesandbox.io/s/react-pdf-viewer-sample-forked-856rnl?file=/src/App.tsx
here you can see that the amount added to the height and width doesn't affect anything, the spacing stays the same between the pages.
const pageLayout = {
  buildPageStyles: () => ({
    alignItems: "center",
    display: "flex",
    justifyContent: "center"
  }),
  tranformSize: ({ size }) => ({
    height: size.height + 300,
    width: size.width + 300
  })
};

**Comment by netefJustice** [comment]
nvm i fixed it there is a typo in the documentation tranformSize is missing an 's' it should be transformSize. now it works
