### ISSUE TITLE
Interact with paragraphs and tables.

### ISSUE THREAD

**Issue by boan-anbo** [react-pdf-viewer/react-pdf-viewer#1481]
I saw a random pdf web browser demo somewhere where it's possible to hover over and "select" a paragraph, like what you can do with selecting a highlighted area, except the paragraph is not highlighted. 

After selecting a paragraph or a table, the user can do multiple things, such as translating it or feeding the text of the selected paragraph somewhere. I wonder if I can do the same with react-pdf-viewer? 

I've looked through the existing examples but cannot find a solution. Please kindly instruct or point to ways that I can implement this myself using the plugin system.

Thanks so much!

**Comment by phuocng** [comment]
@boan-anbo Please take a look at the [highlight plugin](https://react-pdf-viewer.dev/plugins/highlight/).

**Comment by jlia0** [comment]
@boan-anbo Did you find anything?
