### ISSUE TITLE
Provide css modules support

### ISSUE THREAD

**Issue by Sparkenstein** [react-pdf-viewer/react-pdf-viewer#1496]
Hey, I am facing a difficult situation when using react-pdf-viewer. 
I have a common component (pdf viewer obv), that is being used in both nextjs and react client side project

Unfortunately nextjs doesn't allow global CSS as we are already aware from few previous issues

```
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, 
and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. 
Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
```

And as per discussions on nextjs repo they are in no mood to fix this either. 
It'd be great if react-pdf-viewer ships css modules instead of global css.  

Any thoughts on this?

**Comment by Sparkenstein** [comment]
Simplest fix for now could also be something like

```jsx
import styles from '@react-pdf-viewer/default-layout/lib/styles/index.css'

...
<Viewer plugins=[]  styles=[] /> etc
```

Otherwise plugins can also ship their own css.
if you have any other way to fix this let me know. But it'd be really good if you
take this optimization into consideration as anyway it's a better idea to use `css-modules`

**Comment by phuocng** [comment]
Please include the CSS in the entry pages [pages/_app.js](https://github.com/react-pdf-viewer/starter/blob/main/nextjs/pages/_app.js):

```css
// Import the styles provided by the react-pdf-viewer packages
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';
```

See the [NextJS starter](https://github.com/react-pdf-viewer/starter/tree/main/nextjs).

**Comment by Sparkenstein** [comment]
we can't, that's the problem.

as I mentioned above, There's a common PDF module which is being used by both nextjs and react project. 
if I include styles in nextjs `pages/_app` then react project won't get styles, if I include in react `App.js` then 
nextjs project won't receive styles

I have to keep Logic `<Worker><Viewer src={}>`  in common component, but include 2 set of styles one in
React side one is nextjs side so both works. Did you get my problem
I think it's fairly common problem. 

IMO if styles are anyway required by library, library should include them internally

**Comment by Sparkenstein** [comment]
If you are comfortable with PR I can try contributing some.

**Comment by Sparkenstein** [comment]
closing this as I am moving away to different lib
