### ISSUE TITLE
preload PDF before it comes into view

### ISSUE THREAD

**Issue by Sparkenstein** [react-pdf-viewer/react-pdf-viewer#1499]
I am using react-pdf-viewer in an environment where PDF "NEEDS" to be loaded before it's scrolled into the view. 

Currently as I see the source, there's no way to pre-fetch the PDF before it's scrolled into the view. either provide a prop that can be passed to `viewer` or just let User handle the loading and all with react.

![image](https://user-images.githubusercontent.com/24642451/236284635-f5e90ee5-2dd4-421d-ad8d-e45ed2cbad10.png)

**Comment by Sparkenstein** [comment]
closing this as I am moving to different lib

**Comment by finalight** [comment]
> closing this as I am moving to different lib

may I know which library are you going to use? because i also want to preload the PDF from S3
