### ISSUE TITLE
License

### ISSUE THREAD

**Issue by youngjunkim-kyj-genesislab** [react-pdf-viewer/react-pdf-viewer#1506]
i'm trying to purchase organization license, but i have a few questions.

1. if when i use not purchase `react-pdf-viewer` , but still use `react-pdf-viewer` code in some projects. 

--> what happening this project going on ? (for example, code not working.. or and so on)

2. your purchase site write that 'You will get the license' `react-pdf-viewer-license.pdf` 
what's the meaning of this file `react-pdf-viewer-license.pdf`, is this purchase recipt or like apikey .. ??
<img width="418" alt="image" src="https://github.com/react-pdf-viewer/react-pdf-viewer/assets/74170184/c918038e-7da6-4365-b533-1cfdff10e265">

if i have that file, everything is all right ??

i wondering if i purchase this library, what is difference purchasing of not purchasing ?

**Comment by youngjunkim-kyj-genesislab** [comment]
#25

**Comment by phuocng** [comment]
Replied via email!

**Comment by youngjunkim-kyj-genesislab** [comment]
Thank you for response

**Comment by rs-cuongph** [comment]
i have same question.please contact me via email. 
thank you @phuocng phuo

**Comment by pka420** [comment]
I have the same question, none of the other issues about license clear this.
Please reply the same email. 
Thanks
