### ISSUE TITLE
Warning console.log

### ISSUE THREAD

**Issue by maxidelfino** [react-pdf-viewer/react-pdf-viewer#1507]
When the application is started these console.logs appear indicating this warning 

```
Warning: getHexString - ignoring invalid character: 33
Warning: getHexString - ignoring additional invalid characters.
Warning: Indexing all PDF objects.
```
Is there any way to remove these messages or possible solutions?

I put in context the code I am using:
![image](https://github.com/react-pdf-viewer/react-pdf-viewer/assets/89036646/89f1418b-6ff0-4503-9c4f-48277ed24d1d)
![image](https://github.com/react-pdf-viewer/react-pdf-viewer/assets/89036646/a7ca36df-afa1-497c-8d14-ad5798f4253b)

**Comment by phuocng** [comment]
The warnings come from the pdf-js library. It's not possible to remove them.

**Comment by cmolina** [comment]
Is there a way to set `verbosity: 0`? https://github.com/mozilla/pdf.js/blob/72338ce05df18f77746ab256efb71c310db9f45e/web/app_options.js#L309
