### ISSUE TITLE
Meaning of "user" in licenses

### ISSUE THREAD

**Issue by AndreiBlindu** [react-pdf-viewer/react-pdf-viewer#1515]
Hi I'm interested in purchasing a license for your react-pdf-viewer. I was wondering if the "1 user" in the Developer license means that only 1 developer in my organization can use it or that only 1 end-user of my service can use it. I think the former but I would like to have your confirmation to be sure. Please let me know, thanks

**Comment by rl3250** [comment]
same question here. appreciate any clarifications

**Comment by rl3250** [comment]
@phuocng

**Comment by phuocng** [comment]
@AndreiBlindu I am sorry if the term _user_ confuses you. That indicates the number of developers, not the number of customers.
- Developer license is used for a single developer such as a solo developer
- Organization license is used for a team or a company

All licenses can be used in multiple projects, for multiple customers.
In your case, if you are going to use the library in your organization, then the Organization license should be used.

**Comment by AndreiBlindu** [comment]
@phuocng thank you very much for your answer, now it's more clear to me. 
So if I am developing a SaaS for my own company where for the moment I am the only developer in the team I should purchase the Organization license anyways or I can just purchase the Developer license for now until I am alone?

**Comment by phuocng** [comment]
@AndreiBlindu In your specific case, the Developer license is good to go. I always support startups with solo founders.

**Comment by AndreiBlindu** [comment]
@phuocng Ok great, thank you very much.
