### ISSUE TITLE
License, how to use? What it means?

### ISSUE THREAD

**Issue by evertoont** [react-pdf-viewer/react-pdf-viewer#1537]
I have some questions about using the license:

- What is difference purchasing of not purchasing?
- On the website it says I'm going to get the `react-pdf-viewer-license.pdf`, but what does that document mean? Is it a purchase receipt, an api key?
- If I just get this file, can I safely use the library?

@phuocng

**Comment by phuocng** [comment]
* If you want to use it for any reason, you have to purchase it
* The license agreement tells you what you can do with the license, it does NOT contain the license key
* After making the purchase, you will get a license key which will be asked soon (v4.x)

**Comment by evertoont** [comment]
Thanks for the answer!

The third item got confused. Before v4.x version if I get the license (the pdf file), I don't need to do anything else, but after v4.x version release I will need a key, right?

It is worth noting that the license I want to obtain is that of organization.

**Comment by phuocng** [comment]
> Before v4.x version if I get the license (the pdf file), I don't need to do anything else, but after v4.x version release I will need a key, right?

Correct. Please keep the license key after making the purchase, because I plan to integrate the license verification in 4.x.

**Comment by evertoont** [comment]
Perfect, I understand.

Thanks!!

**Comment by buariful** [comment]
> Correct. Please keep the license key after making the purchase, because I plan to integrate the license verification in 4.x.



Can I use the older versions (v3.x) of the library without purchasing a license for personal and client project....?

**Comment by Amrjigga** [comment]
hello,
I purchased the license, where do i put the key that i got? i cant find where

**Comment by priyanshu-kroolo** [comment]
> hello, I purchased the license, where do i put the key that i got? i cant find where

have you got the answer , where to put the licence key ?

**Comment by Amrjigga** [comment]
no
