### ISSUE TITLE
I need to Make annotations and highlighted selected text

### ISSUE THREAD

**Issue by Shahriar-Shakil** [react-pdf-viewer/react-pdf-viewer#1544]
I am looking for a way to contact you before making a purchase. My requirement is to implement annotation and text-highlighting functionality. I would like to save the highlighted or annotated data in my database, allowing users to view their previous notes when they revisit the pdf again. Is this feasible? Please let me know, as I would like to consult with a developer regarding this matter.

**Comment by NikhilKaleGSLab** [comment]
@Shahriar-Shakil: Did you get option for highlights and Annotation?
