### ISSUE TITLE
Displaying the sidebar in fullscreen using defaultLayoutPluginInstance

### ISSUE THREAD

**Issue by Ranecdev** [react-pdf-viewer/react-pdf-viewer#1588]
I have followed the documentation on how to set up fullscreen with the defaultLayout Toolbar. Using following:

```
const defaultLayoutPluginInstance = defaultLayoutPlugin({
        toolbarPlugin: {
            fullScreenPlugin: {
                getFullScreenTarget: (pagesContainer) => pagesContainer.closest('[data-testid="default-layout__body"]'),
                renderExitFullScreenButton: (props) => <></>,
            },
        },
    });
```

But I can't seem to find the sidebars in the full screen mode.
Is there a way to display the sidebar (i.e.: bookmarks or thumbnails tab) in fullscreen mode?

**Comment by enesarsln** [comment]
I have the same problem and I need a solution urgently.

**Comment by phuocng** [comment]
@enesarsln Please take a look at this [sample code](https://github.com/react-pdf-viewer/examples/blob/main/include-the-default-sidebar-in-the-full-screen-mode/IncludeSidebarFullScreenModeDefaultLayoutExample.tsx).

This [guide](https://react-pdf-viewer.dev/examples/include-the-default-toolbar-in-the-full-screen-mode/) explains how its works.

Here is how it looks like:

![Screenshot 2024-01-22 at 21 45 36](https://github.com/react-pdf-viewer/react-pdf-viewer/assets/57786711/f9d7e237-6d64-4bee-8308-72d4e1931b03)
