### ISSUE TITLE
Allow custom file download name 

### ISSUE THREAD

**Issue by sushirat** [react-pdf-viewer/react-pdf-viewer#161]
Currently when downloading a file via the toolbar it is giving a gibberish name. Having the ability to pass in custom file names would be nice.

**Comment by phuoc-ng** [comment]
@sushirat Currently, it uses the name of file. 
Can you tell me what browser/OS that the name of downloaded file isn't the same as the opened one?

**Comment by sushirat** [comment]
I see, I am passing a blob url for the fileUrl and I believe it's using the name from that. Which is the pointer rather than the real file name. I'm using chrome and windows 10 for reference.

**Comment by phuoc-ng** [comment]
@sushirat 
The v2.0.1 was released.
You can use the `fileNameGenerator` option provided by the [Get File](https://react-pdf-viewer.dev/plugins/get-file) plugin.

Note that the `fileNameGenerator` option is also available if you use [Toolbar](https://react-pdf-viewer.dev/plugins/toolbar) or [Default Layout](https://react-pdf-viewer.dev/plugins/default-layout) plugin.

Let me know if you don't know how to use the option when upgrading to 2.0.1.
