### ISSUE TITLE
Scale not being updated correctly for large pdfs

### ISSUE THREAD

**Issue by kdv24** [react-pdf-viewer/react-pdf-viewer#1652]
@phuocng I've found a bug where a page scale set to anything other than PageFit will revert to PageFit whenever a bookmark item is clicked. It appears this is only happening on larger pdfs. Scale is maintained appropriately on page navigation using the toolbar or scrolling. The rescaling bug appears to only be happening relative to the bookmark items. Is it possible the Bookmark plugin is not correctly accessing the updated scale in the Store?

You can test this using your sample pdfs. Specifically, I have found that with your sample `bookmarks-level-3.pdf` the page scale is maintained when clicking on bookmark links. However, using the `5000-of-dummy-optimized`, clicking on a bookmark link always defaults the page scale to PageFit.

_Originally posted by @kdv24 in https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1412#issuecomment-1830792549_

**Comment by devheedoo** [comment]
I have the same issue. I need to keep width, but it goes to PageFit scale.

---

- @react-pdf-viewer/core (3.12.0)
- @react-pdf-viewer/bookmark (3.12.0)

**Comment by phuocng** [comment]
@kdv24 @devheedoo 
Actually, it's not a bug. In certain documents, a bookmark item can contain information about the zoom level. This means that when a user clicks on the bookmark, the document can automatically zoom to a specific level.

Here is the screenshot showing how it works with pdf-js viewer:

<img width="1510" alt="Screenshot 2024-02-07 at 16 20 45" src="https://github.com/react-pdf-viewer/react-pdf-viewer/assets/57786711/d9054166-33ed-4f5b-a6f0-80969289cb5a">

You can [give it a try](https://mozilla.github.io/pdf.js/web/viewer.html) using your document.
