### ISSUE TITLE
Buttons don't showing in toolbar

### ISSUE THREAD

**Issue by DeeSouza** [react-pdf-viewer/react-pdf-viewer#166]
![image](https://user-images.githubusercontent.com/12430887/83150993-58b42a00-a0d2-11ea-8e6a-20a8a751ee4d.png)

![image](https://user-images.githubusercontent.com/12430887/83154437-800cf600-a0d6-11ea-9829-10075951fc61.png)

The class css .viewer-button is duplicated with properties and values differents.

```
import React from 'react';
import Viewer, { Worker } from '@phuocng/react-pdf-viewer';

import '@phuocng/react-pdf-viewer/cjs/react-pdf-viewer.css';

import filePDF from '../../assets/example.pdf';

const DetailsJuridic = () => {
	return (
		<Worker workerUrl="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.3.200/pdf.worker.min.js">
			<div style={{ height: '750px' }}>
				<Viewer fileUrl={filePDF} />
			</div>
		</Worker>
	);
};

export default DetailsJuridic;

```

**Comment by DeeSouza** [comment]
I figured out

**Comment by phuoc-ng** [comment]
I'll add a new guide of how to update the prefix class.
