### ISSUE TITLE
Safari scrolling not working when NOT using the defaultLayoutPlugin

### ISSUE THREAD

**Issue by kgoedecke** [react-pdf-viewer/react-pdf-viewer#1665]
As seen here: https://github.com/react-pdf-viewer/react-pdf-viewer/issues/474#issuecomment-1791060441

We're still experiencing issues with scrolling on Safari when not using the `defaultLayoutPlugin`. Has anyone found a fix for this?

**Comment by phuocng** [comment]
@kgoedecke I can't reproduce the issue. Can you let me know the minimal code to reproduce the issue?
Here is my Safari version:

<img width="396" alt="Screenshot 2024-02-07 at 15 48 07" src="https://github.com/react-pdf-viewer/react-pdf-viewer/assets/57786711/ddf43c29-ae83-4b1f-8a4b-a200b621b6c7">

**Comment by kgoedecke** [comment]
@phuocng I just tested it again and it seems to be fixed, no idea why. Thanks a lot for following up on this, I'll go ahead and close this.

**Comment by phuocng** [comment]
Thank you, @kgoedecke 👍
