### ISSUE TITLE
Rotating the license key for security reasons

### ISSUE THREAD

**Issue by vinceAmstoutz** [react-pdf-viewer/react-pdf-viewer#1698]
@phuocng Is it possible to rotate my license key for security reasons?

**Comment by phuocng** [comment]
We plan to integrate the license verification soon. And you won't have to insert the license key in the codebase. Basically, we'll ask you to put in the environment variable when installing the package.

**Comment by vinceAmstoutz** [comment]
Yes, but what if I want to change it after I've committed it by mistake?

**Comment by vinceAmstoutz** [comment]
@phuocng No way?

**Comment by phuocng** [comment]
It isn't in the roadmap. Currently, if you really want to change it, drop me an email to me@phuoc.ng.
I will check if Gumroad can support changing the license.
