### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by viktorlarsson** [react-pdf-viewer/react-pdf-viewer#1700]
Hello!

While I do think very good of this plugin, and we made a purchase of this plugin maybe 8 months ago. But it almost seems as the development has stopped a bit? Running an old version of pdfjs-dist, we have to add a patch to get higher resolutions to images etc. Are you still maintaining the library?

**Comment by phuocng** [comment]
Yes! I have been busy with supporting custom works, so the development has been delayed for a while. I have been working on v4 with many big refactoring and improvements.
