### ISSUE TITLE
[Questions] Project status & trial

### ISSUE THREAD

**Issue by mauro-ni** [react-pdf-viewer/react-pdf-viewer#1708]
Hi @phuocng,
I'm opening an Issue because I have the following questions:

1. The last release of this library was on March 21, 2023, is this project stil active/maintained?
2. Is there any plan to update the pdfjs library to the new v4 (https://www.npmjs.com/package/pdfjs-dist)?
3. Is there any roadmap for new features?
4. About locales, some entries are missing and only available in the default locale (see 3dots menu in https://react-pdf-viewer.dev/localizations/).
5. Is it possible to have a trial period and deploy an app using your library in production?

Many thanks in advance,
Mauro

**Comment by phuocng** [comment]
1. Yes
2. Yes, I'll support it in the next v4 (see #1659)
3. Currently I focus on [v4](https://github.com/react-pdf-viewer/react-pdf-viewer/milestone/46)
4. I'll take a careful look and update all the translations. It should be done after v4 comes
5. Yes, you can give it a try by following the [official guide](https://react-pdf-viewer.dev/docs/getting-started/)
