### ISSUE TITLE
Module not found: Error: Can't resolve '@react-pdf-viewer/default-layout'

### ISSUE THREAD

**Issue by j-a-a-p** [react-pdf-viewer/react-pdf-viewer#1710]
I thought I would try the viewer before purchasing it (it is not clear to me if it could work before purchase). The entire app however hangs. 

**Error messages**
`Module not found: Error: Can't resolve '@react-pdf-viewer/default-layout'`
and
`Module not found: Error: Can't resolve '@react-pdf-viewer/default-layout/lib/styles/index.css'`

I can see that these files / dirs are indeed not installed.

**Installation**
This is in package.json
```
"@react-pdf-viewer/core": "^3.12.0",
"pdfjs-dist": "^3.4.120",
"react": "^18.2.0",
```

**The Component**

```
import { Viewer, Worker } from '@react-pdf-viewer/core';
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';

import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';

export const PdfViewer = ( {document} ) => {
    return (
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@3.4.120/build/pdf.worker.min.js">
            <Viewer
                fileUrl='/assets/pdf-open-parameters.pdf'
                plugins={[
                    defaultLayoutPlugin,
                ]}
            />
        </Worker>
    );
}

```

**Comment by phuocng** [comment]
@j-a-a-p Did you install the required packages?

```shell
$ npm install @react-pdf-viewer/core
$ npm install @react-pdf-viewer/default-layout
```

They are mentioned in the [starting guide](https://react-pdf-viewer.dev/docs/getting-started/) and the [default layout plugin](https://react-pdf-viewer.dev/plugins/default-layout/)

**Comment by j-a-a-p** [comment]
Hi Phuocng,

Thanks for your response,

I only see these two packages mentioned:
npm install ***@***.***
npm install @***@***.***

I will add the /default-layout, thanks!
