### ISSUE TITLE
Update pdfjs-dist dependency to version 4.0

### ISSUE THREAD

**Issue by vinceAmstoutz** [react-pdf-viewer/react-pdf-viewer#1711]
@phuocng  `pdfjs-dist` can't be updated from 3.11.174 to 4.0.379
![image](https://github.com/react-pdf-viewer/react-pdf-viewer/assets/46444652/321a0ca8-eca1-458a-8f2b-05e0cfb1e33b)

More info [here]( https://www.npmjs.com/package/pdfjs-dist?activeTab=versions) about available  `pdfjs-dist` versions.

**Comment by phuocng** [comment]
@vinceAmstoutz 
See #1659

**Comment by vinceAmstoutz** [comment]
> @vinceAmstoutz See #1659

@phuocng Thanks a lot for everything you've done! I haven't found the release and tag on GitHib and on NPM, maybe soon I guess?
