### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by kilianmu** [react-pdf-viewer/react-pdf-viewer#1725]
Hi, @phuocng ,

As you can see on your example, some Translations are missing on the more actions menu: https://react-pdf-viewer.dev/localizations/

How its possible to add them?

P.S. I bought a dev license today.

**Comment by phuocng** [comment]
@kilianmu Once the v4 is released, the translation packages will be updated to sync with the latest English translation.
Currently, you can create your own translation file as a JSON file, and include it to your page, for example:

```jsx
import { LocalizationMap, Viewer } from '@react-pdf-viewer/core';

// Import your localization file
import de_DE from '/path/to/your/localization/de_DE.json';

const defaultLayoutPluginInstance = defaultLayoutPlugin();

// render function
<Viewer localization={de_DE as unknown as LocalizationMap} />;
```

**Comment by kilianmu** [comment]
@phuocng  Thank you!
