### ISSUE TITLE
Vulnerability issue with pdfjs  

### ISSUE THREAD

**Issue by krucodes** [react-pdf-viewer/react-pdf-viewer#1757]
following this advisory, [https://github.com/advisories/GHSA-wgrm-67xf-hhpq](https://github.com/advisories/GHSA-wgrm-67xf-hhpq) seems like any version <=4.1.392 are affected by this. is it possible to update pdfjs version with the patched in play.

**Comment by krucodes** [comment]
already have a thread for this that I missed.

**Comment by jameswu1991** [comment]
for historical reference for anyone landing on this thread from search engines, the referenced thread is here:
* https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1659
