### ISSUE TITLE
Switch the browser tab and the canvas is emptied

### ISSUE THREAD

**Issue by zyTheGit** [react-pdf-viewer/react-pdf-viewer#1760]
Switch the browser tab, and the drawn canvas is emptied

![switch](https://github.com/react-pdf-viewer/react-pdf-viewer/assets/34878821/ea3b572a-65f9-4e8d-b6b1-ff35a9a8fec4)

**Comment by jkgenser** [comment]
Do you have steps to consistently reproduce this?

**Comment by jkgenser** [comment]
related: https://issues.chromium.org/issues/328755781

**Comment by zyTheGit** [comment]
Okay, thank you, I haven't tried disabling Accelerated 2D Canvas. In the end, I used to listen to the visibilitychange event, modify the canvas zoom ratio when leaving, and restore the zoom ratio when coming back.
