### ISSUE TITLE
_a.cancel is not a function

### ISSUE THREAD

**Issue by greatnonso7** [react-pdf-viewer/react-pdf-viewer#1783]
I get this error whenever the pdf viewer tries to load a pdf or maybe go back to a previous page.

**Comment by AaronWGoh** [comment]
Just for anyone else, seems like the pdf-dist version is strict. I set
```
<Worker
        workerUrl={
          "https://unpkg.com/pdfjs-dist@3.4.120/build/pdf.worker.min.js"
        }
      >
      ```

and in package.json
```
    "@react-pdf-viewer/core": "3.12.0",
    "pdfjs-dist": "3.4.120",
```

If you increase the pdfjs-dist version, it will have an incompatible dependency and cause a crash whenever you close the pdf
