### ISSUE TITLE
pdf File path issue

### ISSUE THREAD

**Issue by raluxi5** [react-pdf-viewer/react-pdf-viewer#1849]
I am using the <Worker workerUrl="https://unpkg.com/pdfjs-dist@3.4.120/build/pdf.worker.min.js"> 
            <Viewer fileUrl={pdf} defaultScale={SpecialZoomLevel.PageFit} scrollMode={ScrollMode.Page} />
          </Worker>

and the pdf variable has the document path by doing import pdf from "./assets/test.pdf"; which works perfectly fine. 
The issue is I want to dynamically assign a file path so after making a post request to the server I want to give the document.url to the fileUrl attribute from the Viewer.. when I do this I get either Missing File "the name" or Invalid PDF Structure. How should I proceed to give to the fileUrl the path dynamically ?

**Comment by Lovenson2000** [comment]
Hey @raluxi5 !
Did you manage to figure it out ? I'm having the same issue.
