### ISSUE TITLE
License key

### ISSUE THREAD

**Issue by shomy1992** [react-pdf-viewer/react-pdf-viewer#1859]
Hello, my team purchased the react-pdf-viewer library and we got the license key, but there is no explanation of what to do with it. Can you please share some documentation on how to use the license key? I appreciate any help you can provide.

**Comment by Titorat** [comment]
Please look the previous issue, also you don't need the license key in anything. Just download using npm, but it isn't used for actual activation. I would really advise not using this package. It has a lot of vulnerabilities that are very hard to resolve and maintain. I am an ex-user.

**Comment by jkgenser** [comment]
> Please look the previous issue, also you don't need the license key in anything. Just download using npm, but it isn't used for actual activation. I would really advise not using this package. It has a lot of vulnerabilities that are very hard to resolve and maintain. I am an ex-user.

What did you end up using instead?
