### ISSUE TITLE
1.7.0 Unhandled Rejection (Error): Invalid SVG dimensions

### ISSUE THREAD

**Issue by zhanchengkun** [react-pdf-viewer/react-pdf-viewer#198]
环境: 
"@phuocng/react-pdf-viewer": "^1.7.0",
 "pdfjs-dist": "^2.4.456"
代码:

  <Viewer fileUrl="***.pdf"      
    renderPage={props => {
            return (
              <> 
                {props.svgLayer.children} 
              </>
            );
          }}
  />
报错
Unhandled Rejection (Error): Invalid SVG dimensions
unreachable
./pdfjs-dist/build/pdf/src/shared/util.js:333
  330 | }
  331 | 
  332 | function unreachable(msg) {
> 333 |   throw new Error(msg);
  334 | }
  335 | 
  336 | function assert(cond, msg) {

**Comment by phuoc-ng** [comment]
Closed. Will be tracked by #418
