### ISSUE TITLE
Different filename when downloading pdf file.

### ISSUE THREAD

**Issue by angyangcheng** [react-pdf-viewer/react-pdf-viewer#205]
Currently, I am loading the pdf from base64. When downloading the file, the filename comes from the blob url which isn't the actual filename. Is there a fix for this problem?

**Comment by phuoc-ng** [comment]
I saw that feature request in #161 as well. So it'll be supported in the next version 1.8.0.
cc @sushirat

**Comment by phuoc-ng** [comment]
@angyangcheng 
The v2.0.1 was released.
You can use the `fileNameGenerator` option provided by the [Get File](https://react-pdf-viewer.dev/plugins/get-file) plugin.

Note that the `fileNameGenerator` option is also available if you use [Toolbar](https://react-pdf-viewer.dev/plugins/toolbar)
or [Default Layout](https://react-pdf-viewer.dev/plugins/default-layout) plugin.

Let me know if you don't know how to use the option when upgrading to 2.0.1.
