### ISSUE TITLE
target="blank" on click on link in pdf

### ISSUE THREAD

**Issue by JSurquin** [react-pdf-viewer/react-pdf-viewer#221]
Hi , there is a possibility to add a simple target="blank" on click in **annotation** link ? 

I use your solution (older solution answered in a issue before the onTextLayerRender method) with Linkify wrapper for handle <a> when the <a> is in layer text , it's work great, but some links wrap by the reader directly

![image](https://user-images.githubusercontent.com/33385043/87657562-46ae4980-c75b-11ea-9063-8e929e9614b3.png)

--------------------- **on official website**

![image](https://user-images.githubusercontent.com/33385043/87657199-c8ea3e00-c75a-11ea-9d5a-f549e940ee8e.png)
![image](https://user-images.githubusercontent.com/33385043/87657204-cbe52e80-c75a-11ea-95a4-b192f8f2d7b7.png)

Target attribute is empty here

**Comment by JSurquin** [comment]
(I sent screenshots from the official website to show the "problem", I have links encapsulated by Linkify and others by the reader directly)

**Comment by phuoc-ng** [comment]
@JSurquin I'll add support for that in the next version.

**Comment by phuoc-ng** [comment]
@JSurquin 

Update:
The feature was implemented. I'll let you know when 2.1.0 is released.

_Demo_

<img width="1680" alt="Screen Shot 2020-10-25 at 12 39 24" src="https://user-images.githubusercontent.com/57786711/97099876-7953d080-16c0-11eb-84bf-571ef5440dd7.png">

PS: The latest version 2.0.1 was released, please [upgrade](https://react-pdf-viewer.dev/updates).

**Comment by phuoc-ng** [comment]
@JSurquin 
Please [upgrade](https://react-pdf-viewer.dev/updates) to v2.1.0 which is released officially.

## Usage

```javascript
import React from 'react';
import { AnnotationType, Plugin, PluginOnAnnotationLayerRender, Viewer, Worker } from '@react-pdf-viewer/core';

import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';

import '@react-pdf-viewer/default-layout/lib/styles/index.css';

const testAnnotationRenderPlugin = (): Plugin => {
    const onRenderAnnotations = (e: PluginOnAnnotationLayerRender) => {
        // Find all `Link` annotation
        e.annotations
            .filter(annotation => annotation.annotationType === AnnotationType.Link)
            .forEach(annotation => {
                if (annotation.url) {
                    // Find the `a` element represents the link
                    [...e.container.querySelectorAll('.rpv-core-annotation-link a')].forEach(linkEle => {
                        linkEle.setAttribute('target', '_blank');
                    });
                }
            });
    };

    return {
        onAnnotationLayerRender: onRenderAnnotations,
    };
};

const App = () => {
    const defaultLayoutPluginInstance = defaultLayoutPlugin();
    const testAnnotationRenderPluginInstance = testAnnotationRenderPlugin();

    return (
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.js">
            <div
                style={{
                    height: '750px'
                }}
            >
                <Viewer
                    fileUrl="http://localhost:8001/pdf-open-parameters.pdf"
                    plugins={[
                        defaultLayoutPluginInstance,
                        testAnnotationRenderPluginInstance,
                    ]}
                />
            </div>
        </Worker>
    );
};

export default App;
```

You can see the example [here](https://github.com/react-pdf-viewer/examples/blob/main/customize-link-annotation/CustomLinkAnnotationExample.tsx).
