### ISSUE TITLE
loadingTask library error.

### ISSUE THREAD

**Issue by kokyhin** [react-pdf-viewer/react-pdf-viewer#263]
Installed all dependencies according to docs.
i have next code

`<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.min.js">
    <Viewer fileUrl='./test.pdf' />
</Worker>`

test.pdf file locates in same directory.

in console i have next error
Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at react-pdf-viewer.js:3015

<img width="494" alt="Screen Shot 2020-08-12 at 16 46 06" src="https://user-images.githubusercontent.com/15032628/90022673-7b121880-dcbb-11ea-972e-255a9476b7cb.png">

**Comment by phuoc-ng** [comment]
@kokyhin 
Please try the following approaches:

1. Ensure that the pdfjs-dist versions in `Worker` and your `package.json` are the same

2. Try to use the unminified version of pdf.js (`pdf.worker.js`, not `pdf.worker.min.js`)

```js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.js">
...
</Worker>
```

**Comment by kokyhin** [comment]
@phuoc-ng 
using pdf.worker.js i get error message "Invalid PDF structure"
i'm trying to load this file https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
i've download it and put at './test.pdf'

What's wrong with file ?

**Comment by phuoc-ng** [comment]
@kokyhin I try to open the file with the demo in https://react-pdf-viewer.dev, and it looks good

<img width="1410" alt="Screen Shot 2020-08-12 at 22 57 48" src="https://user-images.githubusercontent.com/57786711/90038148-4324c880-dcef-11ea-8e99-226a78227e4e.png">

Does your setup work with other file such as [this one](https://react-pdf-viewer.dev/assets/pdf-open-parameters.pdf)?

If not, then I think you can try to downgrade pdfjs-dist:

```console
$ npm uninstall pdfjs-dist
$ npm uninstall @phuocng/react-pdf-viewer

$ npm install pdfjs-dist@2.3.200
$ npm install @phuocng/react-pdf-viewer@1.7.0
```

Update the worker:

```console
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.3.200/build/pdf.worker.min.js">
```

**Comment by kokyhin** [comment]
@phuoc-ng it works fine with absolute path. And don't see relative path to a file.

**Comment by miltonhe** [comment]
I have the same issue here, the file opens fine when you use the open file in the viewer itself, but when trying to load from passing the URL in, it fails for some documents.  There is some difference between loading the pdf via the url prop vs the tool bar command.   The documents I'm attempting which fails seem to be primarily scans, documents that I'm generating from images and translating from other formats seem to work fine.

**Comment by phuoc-ng** [comment]
Feel free to re-open if you see this happen again.

**Comment by kdv24** [comment]
@phuoc-ng I'm having the same issue. We have a large pdf (>1000 pages) that loaded fine but very slowly, so we optimized it for fast web using Adobe Acrobat and now it won't load.  We're getting the Invalid PDF structure error. I'd love any help on how to solve this! Thank you in advance!
