### ISSUE TITLE
Search popover click next match, trows error.

### ISSUE THREAD

**Issue by kokyhin** [react-pdf-viewer/react-pdf-viewer#266]
visit https://react-pdf-viewer.dev/ If you leave search input empty and click next match. You will get next error 
<img width="1680" alt="Screen Shot 2020-08-13 at 14 08 46" src="https://user-images.githubusercontent.com/15032628/90128061-e832b600-dd6e-11ea-8070-e49b6631cb4c.png">

**Comment by phuoc-ng** [comment]
Thanks for reporting the bug. Actually it was fixed and the fix will be available in next v2.0.0.

**Comment by phuoc-ng** [comment]
@kokyhin 
The bug is fixed and released in 2.1.0. Please [upgrade](https://react-pdf-viewer.dev/updates) if you already purchase.

You can try it in the [search](https://react-pdf-viewer.dev/plugins/search) plugin.
