### ISSUE TITLE
Disabling annotation links highlight

### ISSUE THREAD

**Issue by arvinsim** [react-pdf-viewer/react-pdf-viewer#275]
Is there a way to disable the annotation link higlights like the red boxes show below?

![image](https://user-images.githubusercontent.com/2200902/91279045-9b5fce00-e7b7-11ea-84ec-e0d0304c979c.png)

**Comment by phuoc-ng** [comment]
@arvinsim Can you attach the document here, so I can take a look?

**Comment by phuoc-ng** [comment]
@arvinsim Any update?
