### ISSUE TITLE
Error: Invalid parameter object: need either .data, .range or .url

### ISSUE THREAD

**Issue by David-moonsite** [react-pdf-viewer/react-pdf-viewer#276]
Hi , 
i am  trying to show a pdf file, and i got this error .
Error: Invalid parameter object: need either .data, .range or .url

**my implementation :**

`  <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.min.js">
          <div style={{ height: "750px" }}>
            <Viewer fileUrl={documentURL} />
          </div>
        </Worker>
`

**Comment by phuoc-ng** [comment]
@David-moonsite 
What's `documentURL`? Is it a valid URL (relative such as `/path/to/document.pdf`, or absolute as `http://domain/path/to/document.pdf`)?

**Comment by David-moonsite** [comment]
absolute

**Comment by phuoc-ng** [comment]
* If you use the absolute path for `fileUrl` and the file belongs to different domain, then you need to ensure that the domain does allow your site to access it (due to the cross domain issue).

* Does the issue happen with the file on your site (relative path)?

**Comment by David-moonsite** [comment]
* the file belongs to same domain .
* when i use relative path a gov new error ,
react-pdf-viewer.js:3015 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at react-pdf-viewer.js:3015

**Comment by phuoc-ng** [comment]
You can try the following approaches:

## Try to use the normal version of worker

(I see some issues with the minified version of pdf-js 2.4.456)

``` js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.js"> /* There is no .min.js */
   ...
</Worker>
```

## Try to downgrade pdfjs-dist

1. Uninstall

``` console
npm uninstall --save-dev pdfjs-dist
```

2. Reinstall with the lower version:

``` console
npm install --save-dev pdfjs-dist@2.3.200
```

Adjust the Worker:

```js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.3.200/build/pdf.worker.min.js">
</Worker
```

In both approaches, ensure that the `pdfjs-dist` version in `Worker` and in your `package.json` are the same.

**Comment by David-moonsite** [comment]
pdf.js:16952 Uncaught Error: Unknown action from worker: undefined
    at Worker.MessageHandler._onComObjOnMessage (pdf.js:16952)

**Comment by David-moonsite** [comment]
![Screen Shot 2020-09-07 at 16 25 14](https://user-images.githubusercontent.com/58983212/92392383-def6f800-f126-11ea-8382-3719d7f47b39.png)

**Comment by phuoc-ng** [comment]
> pdf.js:16952 Uncaught Error: Unknown action from worker: undefined
at Worker.MessageHandler._onComObjOnMessage (pdf.js:16952)

It is mentioned here https://react-pdf-viewer.dev/docs/basic-usage

<img width="781" alt="Screen Shot 2020-09-07 at 20 24 21" src="https://user-images.githubusercontent.com/57786711/92392235-280b7400-f148-11ea-8a95-ef2887a6ef0f.png">


Let's refresh the installation as I mentioned above.

``` console
npm uninstall --save-dev pdfjs-dist
npm uninstall @phuocng/react-pdf-viewer

npm install pdfjs-dist@2.3.200
npm install @phuocng/react-pdf-viewer@1.7.0
```

``` js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.3.200/build/pdf.worker.min.js">
...
</Worker>
```

**Comment by phuoc-ng** [comment]
I just saw your screenshot after posting the previous message, can you give me the PDF file?

**Comment by David-moonsite** [comment]
[david.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/5183317/david.pdf)

**Comment by phuoc-ng** [comment]
I am not sure what's wrong with the setup, but I tried to open your file with https://react-pdf-viewer.dev/, and it looks good

<img width="1048" alt="Screen Shot 2020-09-07 at 20 33 17" src="https://user-images.githubusercontent.com/57786711/92393069-78cf9c80-f149-11ea-801e-d2bac79892cd.png">

Can you try to load another file (such as [this one](https://react-pdf-viewer.dev/assets/pdf-open-parameters.pdf)) to see if the problem is there?

If yes, then I think there's a problem with the setup. Maybe you should try with the fresh folder (no other dependencies, just react-pdf-viewer and pdfjs-dist).

``` console
npm uninstall --save-dev pdfjs-dist
npm uninstall @phuocng/react-pdf-viewer

npm install pdfjs-dist@2.3.200
npm install @phuocng/react-pdf-viewer@1.7.0
```

``` js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.3.200/build/pdf.worker.min.js">
...
</Worker>
```

Here is [sample setup](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/demo/webpack) with webpack.

**Comment by David-moonsite** [comment]
`
  <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.3.200/build/pdf.worker.min.js">
          <div style={{ height: "750px" }}>
            <Viewer fileUrl="../../assets/pdf/pdf-open-parameters.pdf" />
          </div>
        </Worker>

`
same issue : invalid pdf structure , like in screenshot above

**Comment by phuoc-ng** [comment]
> Maybe you should try with the fresh folder (no other dependencies, just react-pdf-viewer and pdfjs-dist).
> Here is [sample setup](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/demo/webpack) with webpack.

**Comment by David-moonsite** [comment]
In your code ,
in pdf.js , the function --> getDocument(src)
gets src that its data  is undefined .
<img width="1045" alt="Screen Shot 2020-09-08 at 11 06 47" src="https://user-images.githubusercontent.com/58983212/92450014-8e81a800-f1c3-11ea-8f37-cda37fc26936.png">

**Comment by David-moonsite** [comment]
> > Maybe you should try with the fresh folder (no other dependencies, just react-pdf-viewer and pdfjs-dist).
> > Here is [sample setup](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/demo/webpack) with webpack.

thats what i did :
`yarn remove pdfjs-dist`
`yarn remove @phuocng/react-pdf-viewer`
i remove yarn.lock
removed node_modules
than i run ::
 `yarn`
`yarn add pdfjs-dist@2.3.200`
 `yarn add @phuocng/react-pdf-viewer@1.7.0`
i still get an error : invalid pdf structure

**Comment by adirrapidapi** [comment]
@phuoc-ng I have the same issue. I installed the same versions you provided here and I get "Invalid PDF structure"

**Comment by phuoc-ng** [comment]
@David-moonsite @adirrapidapi 
1. Can you let me know the browser version?
2. Does the demo on the [homepage](https://react-pdf-viewer.dev) work with your browser?
