### ISSUE TITLE
Support custom toolbar controls

### ISSUE THREAD

**Issue by tgfischer** [react-pdf-viewer/react-pdf-viewer#277]
I'm trying out this package to see if it suits our needs, and so far this package is looking really good :)

The one thing we'd like to do is to use custom buttons/controls in the toolbar. For example, we wanted to replace the search pop over with an input that is inline in the toolbar. I see in the docs that we can use the controls in the `ToolbarSlot` to make our own toolbar. But if I gave it an `input` and some `button`s rather than a `searchPopover`, are we able to hook it up to the functions that actually search and navigate through the document?

Thanks!

**Comment by phuoc-ng** [comment]
@tgfischer 

* Update 1:
Now the v2.0.1 is [released](https://react-pdf-viewer.dev/updates) with **plugin architecture**, you can customize almost anything on toolbar.
See examples on https://react-pdf-viewer.dev/plugins/toolbar/

* Update 2:

> But if I gave it an input and some buttons rather than a searchPopover, are we able to hook it up to the functions that actually search and navigate through the document

This is the part hasn't been implemented in v2.0.1.
I'll add it to the next version, so ALL parts on toolbar are customizable.

**Comment by phuoc-ng** [comment]
@tgfischer 

The feature was implemented and will be released in the next v2.2.0.

_Demo_

![search](https://user-images.githubusercontent.com/57786711/97712959-bd483a80-1af1-11eb-84fc-6befd481826c.gif)

I'll let you know when 2.2.0 is released.

**Comment by tgfischer** [comment]
This looks great! Thank you for the quick turn around 🙂

**Comment by phuoc-ng** [comment]
@tgfischer v2.2.0 was [released](https://react-pdf-viewer.dev/updates)
You can see the custom search control in action here https://react-pdf-viewer.dev/plugins/search

Let me know if there's anything stops you from making a purchase :)

**Comment by tgfischer** [comment]
Thank you again! My company did end up buying a license 😄
