### ISSUE TITLE
white  pdf page

### ISSUE THREAD

**Issue by David-moonsite** [react-pdf-viewer/react-pdf-viewer#278]
hi ,
 i get white page . 
cant see any errors or something.
<img width="603" alt="Screen Shot 2020-09-09 at 14 35 09" src="https://user-images.githubusercontent.com/58983212/92593518-e692da00-f2a9-11ea-8160-1a6296206b7f.png">

**Comment by phuoc-ng** [comment]
You can inspect it by right click on the page, choose _Inspect_ (assume that you're using Chrome browser).

Do you see anything like


```html
<div class="viewer-text-layer">
  <span class="viewer-text">...</span>
  <span class="viewer-text">...</span>
  <span class="viewer-text">...</span>
  <span class="viewer-text">...</span>
  ...
</div>
```

The text are rendered inside `<span class="viewer-text">` elements.

**Comment by 1986webdeveloper** [comment]
> hi ,
> i get white page .
> cant see any errors or something.
> <img alt="Screen Shot 2020-09-09 at 14 35 09" width="603" src="https://user-images.githubusercontent.com/58983212/92593518-e692da00-f2a9-11ea-8160-1a6296206b7f.png">

@phuoc-ng I face the same problem, What is the solution for this case.

**Comment by phuoc-ng** [comment]
@1986webdeveloper @David-moonsite 
From the thumbnail view, it means that it can parse and display the document properly.
* Please give me the sample document.
* Do you make any customization on the styles?

**Comment by 1986webdeveloper** [comment]
@phuoc-ng  In my case shows a white page, and also images are not rendering in the thumbnail view. In the inspect section it contains content, but the pdf-viewer not showing anything. Please check provided screenshot.

https://user-images.githubusercontent.com/6542302/109452972-e4e6e980-7a76-11eb-88c6-ec096d0ca4ed.png

I have tried with various sample pdf documents but it's not working with anyone. 
Here is a sample video for the issue.
https://www.loom.com/share/100ffa16a1084c5283e2c548841514f8

**Note: it's working fine in the local, but when I upload implementation on the server, it doesn't work.**

Here is the dependency version I have installed.
"@react-pdf-viewer/core": "^2.4.0",
"@react-pdf-viewer/default-layout": "^2.4.0",
"pdfjs-dist": "^2.0.943",

workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js"

Please help me to fix this issue. awaiting for a reply from your end. Thanks !!

**Comment by phuoc-ng** [comment]
Here is the issue

```js
"pdfjs-dist": "^2.0.943",

workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js"
```

The version of `pdfjs-dist` in `package.json` and in the Worker have to be the same.

Please upgrade the `pdfjs-dist` in `package.json` to make it match with the version used in `Worker`.

You can automate it by following this [doc](https://react-pdf-viewer.dev/examples/compile-and-set-the-worker-source-with-webpack).

**Comment by 1986webdeveloper** [comment]
@phuoc-ng If the pdfjs-dist version is greater than the 2.0.943 version, it's creating an issue for me while making build (react webpack), it fails with the following issue.

https://stackoverflow.com/questions/66381671/react-build-failed-to-minify-the-bundle-error-from-uglifyjs-build-failed-while

**Comment by YasineNifa** [comment]
Hey,
My `pdfjs-dist` in `package.json` and the `worker` version are the same, but I still have this issue
Any solution to that please
```
"@react-pdf-viewer/core": "^3.3.1",
"pdfjs-dist": "^2.13.216",
```
`<Worker workerUrl='https://unpkg.com/pdfjs-dist@2.13.216/build/pdf.worker.min.js' >`
