### ISSUE TITLE
Jump between search hits not working in horizontal scroll

### ISSUE THREAD

**Issue by janhoy** [react-pdf-viewer/react-pdf-viewer#280]
I enabled horizontal scroll in the demo, then did a search. When hitting next button, the thumbnail view updates and jumps to the next hit, but the large PDF view does not scroll horizontally to the hits.

**Comment by phuoc-ng** [comment]
@janhoy 

The issue was fixed in the latest code.

_Demo_

![jump-match](https://user-images.githubusercontent.com/57786711/97798542-99076d80-1c59-11eb-9f4f-eecef950cc6c.gif)

I'll update here when the next 2.2.0 is released officially.

**Comment by phuoc-ng** [comment]
@janhoy v2.2.0 was [released](https://react-pdf-viewer.dev/updates/).
Please let me know if you need anything else, so you can make a purchase :+1:
