### ISSUE TITLE
Add scrollMode prop for Viewer

### ISSUE THREAD

**Issue by robertvasile** [react-pdf-viewer/react-pdf-viewer#291]
atm there's no decent way to display 
PDF pages at render in a side-by-side manner

adding _scrollMode_ prop for the Viewer 
(similarly to _selectionMode_), 
and combining it with _defaultScale_
would allow side-by-side pages at render

**Comment by phuoc-ng** [comment]
@robertvasile It was implemented in the latest development code.
You'll see it in the next v2.0.0.

_Demo_

The following screenshot has the initial scroll mode as `ScrollMode.Horizontal`

<img width="808" alt="Screen Shot 2020-10-11 at 17 11 43" src="https://user-images.githubusercontent.com/57786711/95676100-f3c32180-0be5-11eb-9f1d-2547bc214e2e.png">

**Comment by robertvasile** [comment]
nice, but side-by-side means 2 pages with vertical scroll, not horizontal scroll, similar to actual wrapped scrolling, except it should zoom out to fit 2 pages 😏
![Like this](https://user-images.githubusercontent.com/4264827/95680213-8fea2a00-0be0-11eb-82bd-d8b4d2ae31a4.jpg)

**Comment by phuocng** [comment]
@robertvasile 
This is now supported in [v3.10.0](https://react-pdf-viewer.dev/updates/).
