### ISSUE TITLE
onPageChange may fire more than once, on a single page change, with different values

### ISSUE THREAD

**Issue by NirGallner** [react-pdf-viewer/react-pdf-viewer#300]
version: 1.7.0

Consider the following: 
`<Viewer
    fileUrl={this.props.fileUrl}
    onPageChange={(e)=> console.log(e.currentPage)} 
/> `

While moving up page by page sometimes it shows on a single page change (for instance):
3
1
3

5
4
5

**Comment by phuoc-ng** [comment]
@NirGallner 
The issue was fixed in [v2.0.1](https://react-pdf-viewer.dev/updates).
Please update.

**Comment by esetnik** [comment]
I have the same issue as this still in the latest version.
