### ISSUE TITLE
PDF pagination not working

### ISSUE THREAD

**Issue by WSlim4** [react-pdf-viewer/react-pdf-viewer#313]
My PDF component is displaying all pages at once, I would like to have it working just like in the documentation example where I can change between pages.

This is how i'm doing.

`           
                partituras.map((partitura,i)=>{
                  return (
                    <div className="partitura">
                        <Viewer 
                        fileUrl={`partitura.url}`}
                        />
                    </div>)

**Comment by phuoc-ng** [comment]
By default, `Viewer` will take the full height.
You have to put the `Viewer` inside a container that has a fixed height:

~~~ javascript
<div style={{ height: '750px' }}>
  <Viewer fileUrl={partitura.url} />
</div>
~~~
