### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by linweiboy** [react-pdf-viewer/react-pdf-viewer#320]
hi,
i am trying to show some pdf files, some PDF files can be opened, some report errors，and i got this error .
(Uncaught (in promise) TypeError: Cannot read property 'message' of undefined)
i use 
 <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js">
...
</Worker>

package.json---> "@phuocng/react-pdf-viewer": "^1.7.0",

**Comment by linweiboy** [comment]
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js"> <div style={{ height: "750px" }}> <Viewer fileUrl={documentURL} /> </div> </Worker>

I have tried the previous solution, but there are still problems

**Comment by phuoc-ng** [comment]
@linweiboy It's mentioned here

<img width="772" alt="Screen Shot 2020-10-23 at 18 25 45" src="https://user-images.githubusercontent.com/57786711/96998172-34635900-155d-11eb-9bcf-2a51f41f9c90.png">

~~~ console
npm uninstall @phuocng/react-pdf-viewer
npm uninstall pdfjs-dist
~~~

Reinstall:

~~~ console
npm install pdfjs-dist@2.4.456
npm install @phuocng/react-pdf-viewer@1.7.0
~~~

Setup worker:
~~~ console
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.js">
   ...
</Worker>
~~~

**Comment by phuoc-ng** [comment]
See similar issue: #296

**Comment by linweiboy** [comment]
> ```
> <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.js">
> ```

I'm sorry，excuse me again,I tried your solution, but failed to open a new error：Warning: Indexing all PDF objects
Page error is as follows：
![image](https://user-images.githubusercontent.com/31678213/97544569-c60f1280-1a04-11eb-8eda-5e7453de5e05.png)

**Comment by phuoc-ng** [comment]
@linweiboy Can you attach here the document?

**Comment by linweiboy** [comment]
http://test.file.tuns.com.cn/tuns/product/life/2020/10/23/bJSB6CsTGS平安家庭财产保险条款.pdf

**Comment by phuoc-ng** [comment]
@linweiboy Thanks for getting back to me.
I tested the document with https://react-pdf-viewer.dev, and it works fine

<img width="1055" alt="Screen Shot 2020-11-02 at 20 35 06" src="https://user-images.githubusercontent.com/57786711/97873959-e9122d00-1d4a-11eb-9166-0784463554f2.png">

I think you should try one of starter here https://github.com/react-pdf-viewer/starter
It provides the most simple setup.

**Comment by linweiboy** [comment]
thank you very much!
