### ISSUE TITLE
Zoom makes the viewer change the page

### ISSUE THREAD

**Issue by katrinewi** [react-pdf-viewer/react-pdf-viewer#346]
When I zoom in on a page it changes to another page location in the PDF. It would be more useful if it was zooming in/out on the page in the current view.

**Comment by phuoc-ng** [comment]
@katrinewi 
Thanks for the suggestion.
It was implemented and will be included in the next release.

_Demo_

Look at the text _Adobe® Acrobat® SDK_ at the top.

![zoom](https://user-images.githubusercontent.com/57786711/98822885-f4104000-2463-11eb-9406-0d77f17eebbd.gif)

**Comment by phuoc-ng** [comment]
@katrinewi 
v2.2.1 is [released](https://react-pdf-viewer.dev/updates/)

**Comment by vijayg-idexcel** [comment]
Still, I am facing the same issue with ZoomIn and ZoomOut custom buttons. 

const {  ZoomIn, ZoomOut } = zoomPluginInstance;

const zoomInComponent = () =>  (<ZoomIn >
        {(props) => (
                        <span
                            className="zoom-btn-hil"
                            onClick={props.onClick}
                        >
                           <ZoomInIcon />
                        </span>
                    )}
        </ZoomIn>);
        
        <Viewer enableShortcuts={true} defaultScale={SpecialZoomLevel.ActualSize} viewMode ={ViewMode.SinglePage}  scrollMode = {ScrollMode.Page} fileUrl={fileUrl} plugins={[pageNavigationPluginInstance, zoomPluginInstance]} initialPage={initialPage} enableSmoothScroll={false} />
        
        
        Please suggest a better solution for ZoomIn and ZoomOut.
        I have attached some code for better understanding. Whenever I am clicking on ZoomInComponent. SDK shows some random page instead of a given page.
