### ISSUE TITLE
NextJS 2.1.0 Error

### ISSUE THREAD

**Issue by DzTheRage** [react-pdf-viewer/react-pdf-viewer#347]
Hello, I've been using version 1.7.0 with **NextJS** and wanted to try to upgrade to latest version of 2.1.0. 
In development everything works fine but when I build to production I'm getting this error: 

Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at H (21.03fb0151de3aa442c4b1.js:1)
    at Object.MhNE.t.useState (21.03fb0151de3aa442c4b1.js:1)
    at t.Viewer (21.03fb0151de3aa442c4b1.js:1)
    at qi (framework.8299dc80fe738d1535de.js:1)
    at go (framework.8299dc80fe738d1535de.js:1)
    at su (framework.8299dc80fe738d1535de.js:1)
    at uu (framework.8299dc80fe738d1535de.js:1)
    at eu (framework.8299dc80fe738d1535de.js:1)
    at framework.8299dc80fe738d1535de.js:1
    at t.unstable_runWithPriority (framework.8299dc80fe738d1535de.js:1)

I believe it has something to do with useState hooks in new <Viewer /> component in 2.1.0. 

If you have any ideas about this error and how why it may be happening in NextJS, I'd appreciate it!

**Comment by phuoc-ng** [comment]
Thanks for reporting the issue, @DzTheRage 
I'll try to play with NextJS to see the issue.

**Comment by phuoc-ng** [comment]
@DzTheRage I guess the issue is caused by the fact that you're having 2 React versions.
React PDF viewer 2.1.0 only supports React 16, and I think NextJS uses the latest version React 17?

The v2.2.0 which was just [released](https://react-pdf-viewer.dev/updates/) supports both React 16 and 17.

Please try to upgrade to 2.2.0, and see if the issue is still there.

**Comment by DzTheRage** [comment]
@phuoc-ng Thanks! I'll upgrade now.
