### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by gabrielwallin** [react-pdf-viewer/react-pdf-viewer#353]
Hi! 

I am considering using your product, however, I am concerned about the license. I see that you've discussed this in #25 but no changes have since been made. Are you for example planning on migrating the code to MIT as your other products? (for example 1 LOC)

**Comment by phuoc-ng** [comment]
Thanks for reaching out. But I don't have plan for this at the moment.

**Comment by phuoc-ng** [comment]
There is other alternative which is licensed under MIT license such as https://github.com/wojtekmaj/react-pdf
