### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by anthager** [react-pdf-viewer/react-pdf-viewer#361]
Hi just noticed that you have the zoom properties on the page for the page_navigation plugin in the docs. https://react-pdf-viewer.dev/plugins/page-navigation. Are the docs open source so I can submit a pr? :)

**Comment by phuoc-ng** [comment]
Thanks you for reporting the issue. It was [fixed](https://react-pdf-viewer.dev/plugins/page-navigation).
