### ISSUE TITLE
Customize sidebar

### ISSUE THREAD

**Issue by vasgkanis** [react-pdf-viewer/react-pdf-viewer#362]
I want to use the default layout. I have already customized the toolbar, but know I want to customize the sidebar.
In particular I want to hide/remove the attachment plugin. Is this possible?
Thank you

**Comment by phuoc-ng** [comment]
@vasgkanis It will be supported in the next version 2.3.0.

In the following sample code, the `default-layout` plugin creates 2 tabs which lists the thumbnails and bookmarks:

<img width="480" alt="Screen Shot 2020-12-13 at 19 18 17" src="https://user-images.githubusercontent.com/57786711/102011629-fc67dd80-3d77-11eb-9172-4a53b09f0ad9.png">

```js
const defaultLayoutPluginInstance = defaultLayoutPlugin({
    sidebarTabs: defaultTabs => [defaultTabs[0], defaultTabs[1]],
});
```

If you already purchase, you will get a notification email when the next 2.3.0 is released.

**Comment by phuoc-ng** [comment]
@vasgkanis Here is the live example: https://react-pdf-viewer.dev/examples/remove-a-tab-from-the-sidebar
Please note that you've to use v2.3.0 to use the feature.
