### ISSUE TITLE
How to write tests with @testing-library/react

### ISSUE THREAD

**Issue by tgfischer** [react-pdf-viewer/react-pdf-viewer#375]
I'd like to write a test for a component that renders the PDF Viewer somewhere in it using [@testing-librarty/react](https://testing-library.com/docs/react-testing-library/intro/). For example

```jsx
export const MyComponent = ({ url, getLayout }) => (
  <Worker workerUrl="/pdfjs/pdf.worker.js">
      <div className="pdf-viewer">
        <Viewer
          fileUrl={url}
          layout={getLayout}
          characterMap={{ isCompressed: true, url: "/pdfjs/cmaps/" }}
          renderError={MyErrorComponent}
        />
    </div>
  </Worker>
);
```

```jsx
import { render } from "@testing-library/react";

describe("MyComponent tests", () => {
  it("should render the component", async () => {
    // Pass the proper props in
    const { container } = render(<MyComponent url={...} getLayout={...} />);
    expect(container.firstChild).toMatchSnapshot();
  });
});
```

Right now when I do this sort of test, it always renders the component passed to `renderError`. I'm assuming I need to mock the requests `Worker` and `Viewer` are making to get the `pdf.worker.js` and cmaps.

Do you have any examples of how this can be done? I checked the source in this repository but didn't find any

Thanks in advance!

**Comment by phuoc-ng** [comment]
Thanks for the suggestions, @tgfischer 👍 

I'll add a lot of tests in the next few days/weeks.
The first one is [available](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/__tests__/viewer.spec.tsx) after setting up (#393).
