### ISSUE TITLE
Not works on mobile

### ISSUE THREAD

**Issue by David-moonsite** [react-pdf-viewer/react-pdf-viewer#385]
Hi, 
cant see my document on mobile , 
in desktop it works great .
![Screen Shot 2020-12-13 at 11 16 20](https://user-images.githubusercontent.com/58983212/102007795-ad4c8900-3d34-11eb-9aaf-a1316d2141f7.png)

**Comment by phuoc-ng** [comment]
@David-moonsite Adding a responsive theme is on the roadmap.

**Comment by David-moonsite** [comment]
When?

**Comment by emorling** [comment]
Subscribe

**Comment by emorling** [comment]
Having this responsive is a must-have feature for us. Is this being prioritized?

**Comment by emorling** [comment]
Having this responsive is a must-have feature for us. Is this being prioritized?

**Comment by vishesh04** [comment]
Subscribe

**Comment by phuoc-ng** [comment]
It will be supported in the next 2.5.0.
Here is a few of screenshots:

_iPhone 6/7/8 screen_
<img width="425" alt="Screen Shot 2021-05-15 at 21 13 57" src="https://user-images.githubusercontent.com/57786711/118364443-a5826080-b5c2-11eb-9592-e858bf679436.png">

<img width="715" alt="Screen Shot 2021-05-15 at 21 16 55" src="https://user-images.githubusercontent.com/57786711/118364511-e7aba200-b5c2-11eb-99ed-22a011442443.png">

_iPhone X_
<img width="416" alt="Screen Shot 2021-05-15 at 21 14 11" src="https://user-images.githubusercontent.com/57786711/118364483-c8ad1000-b5c2-11eb-8122-f05ac323306f.png">

_iPad_
<img width="810" alt="Screen Shot 2021-05-15 at 21 14 31" src="https://user-images.githubusercontent.com/57786711/118364494-d06cb480-b5c2-11eb-92f1-b0da170b1f88.png">

**Comment by phuoc-ng** [comment]
[v2.5.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
It doesn't support mobile 100%, but the big part is in. The default layout is compatible with different screen sizes.

**Comment by phuoc-ng** [comment]
@David-moonsite @emorling @vishesh04 
This was implemented in the latest code, and will be included in the next v3.1.0.
The viewer works on mobile without any crashes!

**Comment by phuoc-ng** [comment]
The [v3.1.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!
