### ISSUE TITLE
Error: Unknown action from worker: undefined

### ISSUE THREAD

**Issue by evskorobogatij** [react-pdf-viewer/react-pdf-viewer#388]
Hi!

I used @phuocng/react-pdf-viewer and do:

```
import Viewer, { Worker } from '@phuocng/react-pdf-viewer';

import '@phuocng/react-pdf-viewer/cjs/react-pdf-viewer.css';
```
And then 
```
            <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.2.228/build/pdf.worker.min.js">
                <div style={{ height: '750px' }}>
                   <Viewer fileUrl='./path/to/pdf/test.pdf' /> 
                </div>
            </Worker>
```
But I had an error:
```
Unhandled Runtime Error

Error: Unknown action from worker: undefined
```

**Comment by phuoc-ng** [comment]
As noted in the https://react-pdf-viewer.dev/docs/basic-usage

> It's very important to note that the worker version and the `pdfjs` package (mentioned in the [Install pdfjs library section](https://react-pdf-viewer.dev/docs/getting-started) of Getting started) have to be the same.

![1](https://user-images.githubusercontent.com/57786711/102178261-b3c73600-3ed7-11eb-974d-7e1c2d3416bf.png)

PS: It's recommended to use the latest package (`@react-pdf-viewer/core`) instead of `@phuocng/react-pdf-viewer`.

**Comment by evskorobogatij** [comment]
```
            <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/es5/build/pdf.worker.js">
                <div style={{ height: '750px' }}>
                   <Viewer fileUrl='./path/to/pdf/store/test.pdf' /> 
                </div>
            </Worker>
```
