### ISSUE TITLE
Hand tool

### ISSUE THREAD

**Issue by evskorobogatij** [react-pdf-viewer/react-pdf-viewer#392]
Hi

How to activate **hand tool** by default?

**Comment by phuoc-ng** [comment]
According to the [Scroll Mode plugin](https://react-pdf-viewer.dev/plugins/scroll-mode), you can set it via the `scrollMode` option.

If you're using the [Default Layout plugin](https://react-pdf-viewer.dev/plugins/default-layout), then the setup should look like

```js
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';
import { SelectionMode } from '@react-pdf-viewer/selection-mode';

const defaultLayoutPluginInstance = defaultLayoutPlugin(
  toolbarPlugin: {
    selectionModePlugin: {
      selectionMode: SelectionMode.Hand,
    }
  }
);

// Your render function
<Viewer
    fileUrl='...'
    plugins={[
        defaultLayoutPluginInstance,
    ]}
/>
```
