### ISSUE TITLE
Single Page Rotation

### ISSUE THREAD

**Issue by Nafixk16** [react-pdf-viewer/react-pdf-viewer#394]
No option to rotate only single page, kindly help me!

**Comment by phuoc-ng** [comment]
Can you tell me your usecase? Why doesn't [Rotate plugin](https://react-pdf-viewer.dev/plugins/rotate) help?

**Comment by Nafixk16** [comment]
kindly let me know how to use it in class component

import { defaultLayoutPlugin } from "@react-pdf-viewer/default-layout";
const defaultLayoutPluginInstance = defaultLayoutPlugin();

when I use this plugin in Viewer its showing me this error.
"
  Error: Invalid hook call. Hooks can only be called inside of the body of a function component. 
   This could happen for one of the following reasons:
"


  <Viewer
                  fileUrl={
                    "https://cors-anywhere.herokuapp.com/http://www.africau.edu/images/default/sample.pdf"
                  }
                  plugins={[defaultLayoutPluginInstance]}
                />

**Comment by irudyi-carecloud** [comment]
@phuoc-ng The use case is simple, we have functionality which allows to rotate one or multiple pages and generate a new document based on that. Such libraries like PDFTron or PDF.js allow to rotate a selected page. We evaluate PDF viewer for our product. Is that easy to enable such feature?

**Comment by phuoc-ng** [comment]
Duplicate with #792.

@Nafixk16 
The feature was implemented in the latest code, and will be available in the next v3.2.0.

See demos [here](https://github.com/react-pdf-viewer/react-pdf-viewer/issues/792#issuecomment-1086830261)

**Comment by phuoc-ng** [comment]
@Nafixk16 @irudyi-carecloud 
Please see three ways of rotating a single page in the [v3.2.0](https://react-pdf-viewer.dev/updates/). Please upgrade.
