### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sendWithPromise' of null

### ISSUE THREAD

**Issue by rjtubera** [react-pdf-viewer/react-pdf-viewer#413]
Hi,

Everytime I change the fileUrl from an axios get it's giving me an error `api.js:2372 Uncaught TypeError: Cannot read property 'sendWithPromise' of null`

Do you know how to fix it? I basically want to change the content of the pdf from the api

**Comment by rjtubera** [comment]
Fixed

**Comment by phuoc-ng** [comment]
@rjtubera Can you share how you fixed it?

**Comment by rjtubera** [comment]
It was my state for the url, I just reset it everytime I'm doing a request and the issue was gone

**Comment by rjtubera** [comment]
hi @phuoc-ng, can you help me if there's a way to change the zoom level when they click full screen? I want the full screen to be always pageWidth so it consumes all the screen.
