### ISSUE TITLE
Jump to page?

### ISSUE THREAD

**Issue by hleduff** [react-pdf-viewer/react-pdf-viewer#415]
Hello,

First of all I want to say, congratulations for your great job on this library! It's very cleanly done and feature-rich.

Now my question: is it still possible to jump to a given page in the current version?
The example linked in #20 points to a blank page. I'm not too sure it's exactly what I'm looking for, though.

I see there seems to be a jumpTo/jumpToPage method in page-navigation.js. I would very much like to be able to use it from my app. I have kind of a custom made bookmark list, with in it, a list buttons that each point to a specific page number.

**Comment by phuoc-ng** [comment]
Hi @hleduff,

> I have kind of a custom made bookmark list, with in it, a list buttons that each point to a specific page number.

It's possible! Do you want to create a button on the toolbar or create your own UI that allows user to jump to given page?

**Comment by hleduff** [comment]
Good!
It's a custom UI. So to simplify, what I need is to be able to do (where the value of {pageNumber} is in my component's state so no need to worry about that):

`<button type="button" onClick={() => jumpToPage(pageNumber)}>click me</button>`

Basically in my project I cannot use the native bookmark system of my PDFs, so I need to recreate it. I'm getting additional info about the PDFs from an API, that's why I have the page numbers in state.

**Comment by phuoc-ng** [comment]
@hleduff 
I prepared [an example](https://github.com/react-pdf-viewer/examples/tree/main/jump-to-given-page) for you.

Here is how it looks like

![jump](https://user-images.githubusercontent.com/57786711/104197140-3a2f5300-5457-11eb-8517-05f9e166238d.gif)

If you need the ability of entering the page index, and/or know the number of pages of the current document, just let me know.

**Comment by hleduff** [comment]
You're awesome, thanks!

**Comment by vminvsky** [comment]
Is there an updated approach to doing this?

**Comment by KindaCallam-io** [comment]
I followed this approach. Didn't really work. What is the difference between this can calling jumpToPage from pageNavigationPluginInstance?

**Comment by RejithReghunathan** [comment]
I followed this approach. Didn't really work. What is the difference between this can calling jumpToPage from pageNavigationPluginInstance?
