### ISSUE TITLE
(Potential) Memory Leaks

### ISSUE THREAD

**Issue by aspnetde** [react-pdf-viewer/react-pdf-viewer#422]
I've integreated the component today and am debugging what React warnings call potential memory leaks since. Unfortunately, I cannot share the codebase I am working on, but I can share some leads. The only plugin I use right now is the Zoom plugin.

The warning itself is always the same:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

When _not_ using the `Zoom` element, in general it works correctly. I only receive the warning when I manage to load different PDFs "too fast" -> read: my component seems to re-render before the PDF processing has finished.

Example:

```
AnnotationLoader@http://localhost:3000/static/js/0.chunk.js:2301:14
div
AnnotationLayer@http://localhost:3000/static/js/0.chunk.js:2325:13
div
div
Observer@http://localhost:3000/static/js/0.chunk.js:536:18
PageLayer@http://localhost:3000/static/js/0.chunk.js:2594:21
div
div
div
Inner@http://localhost:3000/static/js/0.chunk.js:2754:22
PageSizeCalculator@http://localhost:3000/static/js/0.chunk.js:3139:13
DocumentLoader@http://localhost:3000/static/js/0.chunk.js:3319:22
LocalizationProvider@http://localhost:3000/static/js/0.chunk.js:585:18
ThemeProvider@http://localhost:3000/static/js/0.chunk.js:3421:18
Viewer@http://localhost:3000/static/js/0.chunk.js:3431:22
Worker@http://localhost:3000/static/js/0.chunk.js:3518:18
div
div
div
div
div
PdfViewer@http://localhost:3000/static/js/main.chunk.js:1917:19
```

I suspect it is [that promise](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/src/annotations/AnnotationLoader.tsx#L30) that needs to be aborted and cleaned up in the effect function. ([Example](https://stackoverflow.com/a/56443045/271150))

--

What I really want is to wrap my `Viewer` into `Zoom`. However, then I run into that problem immediately on the first run:

```
DocumentLoader@http://localhost:3000/static/js/0.chunk.js:3319:22
LocalizationProvider@http://localhost:3000/static/js/0.chunk.js:585:18
ThemeProvider@http://localhost:3000/static/js/0.chunk.js:3421:18
Viewer@http://localhost:3000/static/js/0.chunk.js:3431:22
Worker@http://localhost:3000/static/js/0.chunk.js:3518:18
div
div
div
div
div
Zoom@http://localhost:3000/static/js/0.chunk.js:3839:18
ZoomDecorator
```

Could be [that one](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/src/loader/DocumentLoader.tsx#L90) that is not functioning correctly.

**Comment by phuoc-ng** [comment]
Hi @aspnetde,

Thanks for making the purchase, and reporting the issue.

> When _not_ using the `Zoom` element, in general it works correctly. I only receive the warning when I manage to load different PDFs "too fast" -> read: my component seems to re-render before the PDF processing has finished

You're right, we can possibly reproduce the issue by creating a button which clicking will load another PDF.
It's related to #417.

I'll take a look and make those high priority for the next version.

**Comment by phuoc-ng** [comment]
This issue is fixed in #424. I'll include the fix in v2.3.2!

**Comment by aspnetde** [comment]
Fantastic, thank you!

**Comment by aspnetde** [comment]
Feedback: I cannot reproduce the described behavior with 2.3.2. 👍

**Comment by GowthamKr-firstsource** [comment]
@phuoc-ng in the latest version 2.4.3 there is a memory leak issue, i am re-rendering the pdf again and again and will load multiple file url for the process, and this cause the memory leak, could you help me with this..?
