### ISSUE TITLE
Question: How to programmatically update the scale of a document?

### ISSUE THREAD

**Issue by aspnetde** [react-pdf-viewer/react-pdf-viewer#423]
I've integrated the viewer in an existing application that offers the user to toggle some UI elements. Let's say by default there is a side bar shown that leaves 500px for the PDF on the X axis. Now the user can hide that side bar, so there will be 800 px.

Now I would like to use that available width as efficient as possible by rescaling the open document so it always uses the full width when that side bar is toggled.

However, going through the docs I can't find a way to achieve that programmatically on demand. Do I miss something, or is this not supported at the moment?

PS: I noticed that wrapping my `<Viewer />` into `<Zoom />` when using the zoom plugin does exactly that. But it seems this is a side-effect of an enforced render cycle, which in turn leads to a whole set of other problems for me (as described [here](https://github.com/react-pdf-viewer/react-pdf-viewer/issues/422)).

Thx!

**Comment by phuoc-ng** [comment]
That's is an interesting question. Let me prepare an example for you!

**Comment by phuoc-ng** [comment]
@aspnetde 
## Before

We don't do anything. User has to zoom to see the page.

https://user-images.githubusercontent.com/57786711/104456266-011feb80-55db-11eb-9fee-6dc57ffbcff1.mp4

## After

Fit the width after resizing

https://user-images.githubusercontent.com/57786711/104456309-0f6e0780-55db-11eb-9245-5753422475a7.mp4

**Comment by aspnetde** [comment]
_After_ looks good. But what's the difference, code-wise? 😄

**Comment by phuoc-ng** [comment]
Here is the sample code

1. Create a plugin definition

```js
import { Plugin } from '@react-pdf-viewer/core';

interface ZoomToFitPlugin extends Plugin {
    zoomToFit(): void;
}
```

2. Implement the plugin

```js
import { createStore, PluginFunctions, SpecialZoomLevel } from '@react-pdf-viewer/core';

interface StoreProps {
    zoom?(scale: number | SpecialZoomLevel): void;
}

const zoomToFitPlugin = (): ZoomToFitPlugin => {
    const store = React.useMemo(() => createStore<StoreProps>({}), []);

    return {
        install: (pluginFunctions: PluginFunctions) => {
            store.update('zoom', pluginFunctions.zoom);
        },
        zoomToFit: () => {
            const zoom = store.get('zoom');
            if (zoom) {
                // Zoom to that scale
                zoom(SpecialZoomLevel.PageWidth);
            }
        },
    };
};
```

3. Prepare the layout

Let's take a look at the video in the previous comment.
Assume that I have an internal state to store the width of the container:

```js
const [width, setWidth] = React.useState('100%');
```

There are four buttons that resize the width of container. In reality, you might need to trigger a function after toggling particular UI element.

```js
<div style={{ marginRight: '8px' }}>
    <Button onClick={() => setWidth('600px')}>Resize width to 600px</Button>
</div>
<div style={{ marginRight: '8px' }}>
    <Button onClick={() => setWidth('800px')}>Resize width to 800px</Button>
</div>
<div style={{ marginRight: '8px' }}>
    <Button onClick={() => setWidth('1000px')}>Resize width to 1000px</Button>
</div>
<div style={{ marginRight: '8px' }}>
    <Button onClick={() => setWidth('100%')}>Full width</Button>
</div>
```

The `width` state is used to set the width of container:

```html
<div
    style={{
        height: '750px',
        width: `${width}`,
    }}
>
    <Viewer
        fileUrl="/path/to/document.pdf"
        ...
    />
</div>
```

4. Use the plugin

```js
const defaultLayoutPluginInstance = defaultLayoutPlugin();
const zoomToFitPluginInstance = zoomToFitPlugin();

const { zoomToFit } = zoomToFitPluginInstance;

// Here is the tip
// Use `useLayoutEffect` to ensure that the layout is already there
React.useLayoutEffect(() => {
    zoomToFit(); // Hey, I want to to fit my container
}, [width]);

return (
    <Viewer
        fileUrl="/path/to/document.pdf"
        plugins={[
            zoomToFitPluginInstance,
        ]}
    />
);
```

That's it!

I hope you see how powerful the plugin architecture is :)

**Comment by aspnetde** [comment]
Thank you very much for that detailed explanation. It works like a charm 👍 (And that plugin system is really neat, well done).

Feel free to close the issue.

**Comment by phuoc-ng** [comment]
@aspnetde v2.4.0 is [released](https://react-pdf-viewer.dev/updates/).
With v2.4.0, you can zoom to specific level simply as following:

```js
// If you're using the default-layout plugin
const defaultLayoutPluginInstance = defaultLayoutPlugin();
const { toolbarPluginInstance } = defaultLayoutPluginInstance;
const { zoomPluginInstance } = toolbarPluginInstance;
const { zoomTo } = zoomPluginInstance;

// If you're using the zoom plugin
const zoomPluginInstance = zoomPlugin();
const { zoomTo } = zoomPluginInstance;
```

And then use the `zoomTo` function:

```js
<button onClick={() => zoomTo(1.5) }>
    Zoom to 150%
</button>
```

**Comment by buzzdead** [comment]
Hmm, thanks for the info. But what if you want to override the zoom and change crlt+scroll to an event listener and just zoom 10% at a time (scrolling 10% out or 10% in) ?

Problem is that it's doing that + the integrated zoom which is like 100% at a time...

**Comment by scherroman** [comment]
To get the pdf viewer work as expected (The pdf resizes to the available width upon window resize) I had to use `SpecialZoomLevel.PageWidth` like so: 

```
import { SpecialZoomLevel, Viewer, Worker } from "@react-pdf-viewer/core";

...

<Worker workerUrl="https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js">
  <Viewer
    fileUrl={pdfUrl}
    defaultScale={SpecialZoomLevel.PageWidth}
  />
</Worker>
```

Should be the default imo as it's surprising/undesirable when you resize your page or the width of the pdf viewing area changes in your app and your pdf gets clipped off until you reload the page

**Comment by Prabuv2e** [comment]
> To get the pdf viewer work as expected (The pdf resizes to the available width upon resize of the parent div's width) I had to use `SpecialZoomLevel.PageWidth` like so:
> 
> ```
> import { SpecialZoomLevel, Viewer, Worker } from "@react-pdf-viewer/core";
> 
> ...
> 
> <Worker workerUrl="https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js">
>   <Viewer
>     fileUrl={pdfUrl}
>     defaultScale={SpecialZoomLevel.PageWidth}
>   />
> </Worker>
> ```
> 
> Should be the default imo as it's surprising/undesirable when you resize your window or the width of the pdf viewing area changes in your app and your pdf gets clipped off until you reload the page

This worked well thank you
