### ISSUE TITLE
Search and highlight functionality does not work for phrase spanning across multiple lines.

### ISSUE THREAD

**Issue by nish5uec** [react-pdf-viewer/react-pdf-viewer#426]
Search plugin is not able to highlight phrase/text spanning multiple line in pdf, however it's able to find the text as its get updated in the search box as 1/1 when searched.
Is there any way to highlight the phrase spanning across multiple lines in pdf ?

**Comment by phuoc-ng** [comment]
Thanks for reporting the issue, @nish5uec 
I will fix it in 2.3.3.

**Comment by phuoc-ng** [comment]
@nish5uec The bug is fixed in the latest code.

_Demo_

The following screenshot demonstrates how a keyword _supported by_ is searched and highlighted.

In the document, the keyword actually belongs to different elements:

```html
<span class="rpv-core-text" style="...">... suppor</span>
<span class="rpv-core-text" style="...">ted by ...</span>
``` 

<img width="636" alt="Screen Shot 2021-01-24 at 16 36 39" src="https://user-images.githubusercontent.com/57786711/105626555-fbd86180-5e62-11eb-8f92-b1618bcb9529.png">

**Comment by nish5uec** [comment]
Hi @phuoc-ng was trying to test above features in my local machine, tried to build and add the project locally but no luck. Any idea how i can test the new features before you release a version ?

**Comment by phuoc-ng** [comment]
@nish5uec You can try the latest code by following the steps:
1. Fork this repos
2. Clone it in your local
3. From the root directory of cloned version:

```console
// Install the dependencies
$ npm install

// Build the latest code
$ npm run build
```

Go to the demo folder:

```console
$ cd demo
$ npm run dev
```

Then open http://localhost:8001 to see the demo running with the latest code.

**Comment by phuoc-ng** [comment]
@nish5uec Do you have chance to test it on your local?
Let me know if it works or not.

**Comment by nish5uec** [comment]
Hi @phuoc-ng  yeah it works, thanks for the fix.

**Comment by phuoc-ng** [comment]
Done.

**Comment by Biladenn** [comment]
hi @phuoc-ng 
I want to highlight multiple line for pdf, I tried and it didn't work.
Please help me check it, thanks.
![img](https://user-images.githubusercontent.com/44205118/176150707-e1f52f80-4409-40eb-a46f-1efd8cd50b31.png)

**Comment by prtkjakhar** [comment]
Hi @phuocng, I am facing the same issue as @Biladenn. Please check if the highlight function is highlighting lines that span across multiple lines in the pdf or not.
In my use case I'll be receiving multiple lines in an array and would need to highlight them all in the pdf but among those, the lines that span across multiple lines are not being highlighted.

**Comment by fuadinaqi** [comment]
Hi @phuocng , yeah I'm facing the same issue too as @Biladenn 's

**Comment by muftisamiullah** [comment]
has this issue been fixed?
