### ISSUE TITLE
Viewer does not render signature fields

### ISSUE THREAD

**Issue by fmigot** [react-pdf-viewer/react-pdf-viewer#430]
Hello there,

I'm using your wonderful lib on a new project I'm working on for my company and I ran into an issue today. If a try to render with your viewer a PDF which contains **_signature fields_**, they are just simply ignored 😱

You can reproduce it by going to the [home](https://react-pdf-viewer.dev/) then use the action button "Open file" to open any PDF that has signature fields. For example, this the the PDF I'm using : [test.pdf](https://github.com/react-pdf-viewer/react-pdf-viewer/files/5831656/test.pdf)

Any help on this issue would be very much appreciated because right now I can't display contracts with electronic signature to the users 😭

Don't hesitate if you need more infos! Thank you ☺️

**Comment by phuoc-ng** [comment]
@fmigot 
Thanks for reporting the issue and the sample document is super helpful!
I can confirm that it's a bug! Will try to fix it!

**Comment by phuoc-ng** [comment]
I am looking for the solution, and it turns out that it's not possible :(

pdf.js, the library we're using to parse the document, disables the signature annotation due to the fact that it can't verify the (digital) signature.
The signature annotation is disable, so we can't even view them.

Here is the [lines](https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L1023-L1030) in pdf.js:

```js
    // Hide signatures because we cannot validate them, and unset the fieldValue
    // since it's (most likely) a `Dict` which is non-serializable and will thus
    // cause errors when sending annotations to the main-thread (issue 10347).
    if (data.fieldType === "Sig") {
      data.fieldValue = null;
      this.setFlags(AnnotationFlag.HIDDEN);
      data.hidden = true;
    }
```

So, what is the solution for us?

Fork pdf.js, comment the lines above, and build our own version!
Modify the library code isn't recommended since it's more hard for us to upgrade the library and maintain our changes.

However, there is a similar library, built for Angular, does that.

* Example: https://pdfviewer.net/extended-pdf-viewer/signatures
* In its codebase, it modify pdf.js and worker as you can [see](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/modifyPdfJs/modifyPdf.js#L85-L88) [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/modifyPdfJs/modifyPdfWorker.js#L66-L81)

**Comment by fmigot** [comment]
Thanks for your quick answer!

I also deep a little bit on my side because we have a legacy JS Vanilla project where we display PDF with digital signatures. And you're totally right! After looking in the code, we forked pdf.js to update those lines..

I think you found the open issue [#1076](https://github.com/mozilla/pdf.js/issues/1076#issuecomment-679853994) since 2012 on the subject and even some medium post like this [one](https://medium.com/@4rn4udf/pdf-js-signature-not-showing-in-pdf-viewer-6113646760eb) which explains how to enable the display of digital signatures.

As you mentioned, the solution so far is **to fork the lib** and everyone is doing that. It's amazing that there is still no update yet on pdf.js to handle that with a global parameter or whatever 😲

Anyway, your work on this lib is amazing and right now you are becoming a reference for React users who need to display a PDF and to "play" with it 🔥
At the same time, PDF with digital signatures have become more and more common on the market, so I think that you will need to fork pdf.js too to support them. If I can reassure you, what we did on our legacy project was just to keep on a branch the commits which enable signature annotation and at each new version of pdf.js, we cherry-pick them and adapt the code if necessary (it's rare).

Let me know your call on this issue🤞. Unfortunately, I don't see another option

**Comment by phuoc-ng** [comment]
@fmigot 
I am going to fork pdf.js and create a custom build version that supports signature as well. I'll update the documentation and add an example. 

As I imagine, the forked version can be released under `@react-pdf-viewer/pdfjs` and whenever user wants to see the signature, they just replace `npm install pdfjs-dist` with `npm install @react-pdf-viewer/pdfjs`. 

Will keep you posted!

**Comment by fmigot** [comment]
Great! Sounds really nice 🤘

Thanks again @phuoc-ng, I'm looking forward to your update!

**Comment by phuoc-ng** [comment]
## Updated 1

* Forked, [patched](https://github.com/react-pdf-viewer/pdf.js/pull/1) the codes, and saw the signature

<img width="1127" alt="Screen Shot 2021-01-20 at 22 43 31" src="https://user-images.githubusercontent.com/57786711/105199171-0946d080-5b71-11eb-8c1a-d5ceadfcc937.png">

**Comment by phuoc-ng** [comment]
## Update 2

Got it working with our component:

<img width="1048" alt="Screen Shot 2021-01-21 at 20 09 57" src="https://user-images.githubusercontent.com/57786711/105355917-51bfc600-5c25-11eb-8281-fda215458321.png">

**Comment by phuoc-ng** [comment]
## Update 3

I released the patched. Here is the steps that you can follow to see the signature:

1. Install `@react-pdf-viewer/pdfjs-dist-signature`:

I'll keep the version number of patched package same as the original package.

``` console
$ npm install @react-pdf-viewer/pdfjs-dist-signature@2.5.207
```

2. Replace the `pdfj-dist` in the web bundler. If you're using Webpack, then change the your `webpack.config.js` as following:

``` js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    ...
    plugins: [
        // If you want to see the signature which is disabled by pdf.js, then you have to replace it
        // with `@react-pdf-viewer/pdfjs-dist-signature`
        new webpack.NormalModuleReplacementPlugin(
            /^pdfjs-dist$/,
            resource => {
                resource.request = path.join(__dirname, './node_modules/@react-pdf-viewer/pdfjs-dist-signature');
            },
        ),
    ],
};
```

The settings above is applied for Webpack 4.43.0. I haven't tried Webpack 5 yet, but I guess the setting is simillar.

3. Replace the worker path:

``` js
import { Worker } from '@react-pdf-viewer/core';

<Worker workerUrl="https://unpkg.com/@react-pdf-viewer/pdfjs-dist-signature@2.5.207/build/pdf.worker.js">
  ...
</Worker>
```

![](https://media4.giphy.com/media/fg9c6gu2NwyWs/giphy.gif)

**Comment by fmigot** [comment]
🔥 AMAZING 🔥 Thanks a lot @phuoc-ng!!

I implemented what you mentioned and it works like a charm. By the way, I'm using Webpack 5 and It's the same config 😉

Thanks again for your fix!

**Comment by phuoc-ng** [comment]
Thanks for letting me know it works. I also [updated](https://react-pdf-viewer.dev/examples/display-signatures-in-a-pdf-document) the document, so it can help other people ❤️

**Comment by mikamokedo1** [comment]
how can i fix for create-react-app (not using webpack)

**Comment by phuoc-ng** [comment]
@mikamokedo1 Please see this [starter](https://github.com/react-pdf-viewer/starter/tree/main/create-react-app)

**Comment by mikamokedo1** [comment]
@phuoc-ng thanks alot ,  i can fix the webpack issue based on your mention. but for now, I got another issue.
![image](https://user-images.githubusercontent.com/89120701/140629485-63e4cdbb-6a4b-41ab-bbeb-5bf26c330f4c.png)
My pacgket json
![image](https://user-images.githubusercontent.com/89120701/140629504-f82926f1-51fa-4754-979b-be9112e55380.png)

**Comment by mikamokedo1** [comment]
> @mikamokedo1 Please see this [starter](https://github.com/react-pdf-viewer/starter/tree/main/create-react-app)

you save my life!
