### ISSUE TITLE
Error: "Cannot read property 'WorkerMessageHandler' of undefined

### ISSUE THREAD

**Issue by lpcuellar** [react-pdf-viewer/react-pdf-viewer#434]
Hi, 

I´m trying to make an app to upload a request to our human resources team and it need a pdf to be uploaded. To make sure there are no errors, I want to display a preview of the pdf before it is uploaded. I was searching the web and found your library. I think it´s awesome because there are no much other libraries that let you do the same.

I was watching the code in this page: https://react-pdf-viewer.dev/examples/preview-a-pdf-file-before-uploading/ and when I try the same code in my app it gave me an error. The error is this `Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".`.

I don´t know what could´ve gave me that error. My code is the same as this: https://github.com/react-pdf-viewer/examples/blob/main/preview-a-pdf-file-before-uploading/PreviewLocalFile.tsx

**Comment by phuoc-ng** [comment]
As mentioned in https://react-pdf-viewer.dev/docs/basic-usage, please ensure that the pdf.js version installed in your package.json is the same as the one in `Worker` (2.5.207 in the following steps).

1) Install packages:
```console
$ npm install pdfjs-dist@2.5.207
$ npm install @react-pdf-viewer/core@2.3.2
```

2) Setup the worker:
```javascript
import { Worker } from '@react-pdf-viewer/core';

<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js">
    <!-- The viewer component will be put here -->
    ...
</Worker>
```

**Comment by MaxKoldun** [comment]
It works on Chrome browser, but if you use Android browser it sends the error  "Cannot read property 'WorkerMessageHandler' of undefined again.
