### ISSUE TITLE
The browser/environment lacks native support for critical functionality used by the pdf.js library; Please use an ES5-compatible build instead

### ISSUE THREAD

**Issue by rjtubera** [react-pdf-viewer/react-pdf-viewer#435]
Hi can you help me fix this issue?

`The browser/environment lacks native support for critical functionality used by the pdf.js library; Please use an ES5-compatible build instead`

It doesn't work on tablets,

Thanks

**Comment by phuoc-ng** [comment]
Please take a look at this [guide](https://react-pdf-viewer.dev/examples/support-internet-explorer-11)

**Comment by Straightly** [comment]
Can pdf.js be used in nodejs?  I am getting the same error message.
