### ISSUE TITLE
Can't import CSS when integrate with next.js

### ISSUE THREAD

**Issue by phuoc-ng** [react-pdf-viewer/react-pdf-viewer#441]
Issue error:
https://github.com/vercel/next.js/blob/master/errors/css-npm.md

**Comment by ankit2049** [comment]
You'll encounter this issue if you are using any of `@react-pdf-viewer/default-layout` or `@react-pdf-viewer/toolbar`

Workaround the issue until the next release (2.4.0)

Install [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules)
Create or update `next.config.js` with
```
// For transpiling some @react-pdf-viewer packages
// Also, for piping react-pdf-viewer packages through babel (to learn why, see babel.config.js)
const withTM = require('next-transpile-modules')(['@react-pdf-viewer/default-layout', '@react-pdf-viewer/toolbar']);

module.exports = withTM({});
```
Declare `withTM` as your last plugin (the "most nested" one)


Install [@babel/preset-react](https://www.npmjs.com/package/@babel/preset-react) [babel-plugin-transform-require-ignore](https://www.npmjs.com/package/babel-plugin-transform-require-ignore)
Create or update `babel.config.js`
```
module.exports = {
  presets: [
    '@babel/preset-react', // necessary for all .jsx files
  ],

  // react-pdf-viewer attempts to import its own CSS files, but next.js does not allow this.
  // Throw away these statements before they arrive at next.js, but you'll need to import them manually.
  overrides: [
    {
      include: ['./node_modules'],
      plugins: [
        [
          'babel-plugin-transform-require-ignore',
          {
            extensions: ['.css'],
          },
        ],
      ],
    },
  ],
};
```
Then import all the css files required in `default-layout.js` or `toolbar.js` in your NextJs component

**Comment by phuoc-ng** [comment]
@ankit2049 
Thanks for sharing the workaround.
Supporting Next.js was implemented in the latest code (#459), and will be included in the next 2.4.0.

_Demo_

* Use with the toolbar plugin
<img width="667" alt="Screen Shot 2021-02-02 at 20 01 23" src="https://user-images.githubusercontent.com/57786711/106604869-cb937000-6592-11eb-9165-8238cf4550bd.png">

* Use with the default-layout plugin
<img width="668" alt="Screen Shot 2021-02-02 at 19 58 51" src="https://user-images.githubusercontent.com/57786711/106604920-dea64000-6592-11eb-9543-a9a72310f5f4.png">

The styles are added to `_app.js` as usual:

<img width="638" alt="Screen Shot 2021-02-02 at 20 05 36" src="https://user-images.githubusercontent.com/57786711/106604964-efef4c80-6592-11eb-921d-9307f1defcfa.png">

**Comment by PaulPCIO** [comment]
Any idea when this will be released? could you possibly add some beta or alpha release tags with these updates?

**Comment by phuoc-ng** [comment]
@PaulPCIO @ankit2049 
v2.4.0 is just [released](https://react-pdf-viewer.dev/updates/). Please update.

I also created a starter for NextJS integration [here](https://github.com/react-pdf-viewer/starter/tree/main/nextjs).
