### ISSUE TITLE
Disable scrolling

### ISSUE THREAD

**Issue by emorling** [react-pdf-viewer/react-pdf-viewer#444]
Is it possible to disable scrolling, to be able to display one slide at a time, and control them with navigation? Similar to SlideShare

**Comment by phuoc-ng** [comment]
it's possible. I will create an example for you!

**Comment by phuoc-ng** [comment]
I haven't got enough time to add this example with full explanation to the official website, but you can take a look at the [working code](https://github.com/react-pdf-viewer/examples/tree/main/slide-presentation).

Here is the demo:

https://user-images.githubusercontent.com/57786711/105730286-c0bc5800-5f60-11eb-9c52-e5e90579d1d0.mp4

**Comment by emorling** [comment]
Awesome,thank you!

**Comment by phuoc-ng** [comment]
@emorling The example is now [available](https://react-pdf-viewer.dev/examples/slide-presentation) on the official website.

I also simplified the code as you can see [here](https://github.com/react-pdf-viewer/examples/tree/main/slide-presentation).

**Comment by Andy-ZYA** [comment]
Is there a JS version of the code?
