### ISSUE TITLE
"The API version "2.5.207" does not match the Worker version "2.6.347"." error message

### ISSUE THREAD

**Issue by laazaz** [react-pdf-viewer/react-pdf-viewer#445]
It used to work perfectly for a month, but since this morning it gives this error:

**The API version "2.5.207" does not match the Worker version "2.6.347".**

react-pdf-viewer (/core) version 2.3.2
pdfjs-dist (that apparently got installed automatically with react-pdf-viewer) version: 2.5.207

my code:

```
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js">
        <div className="pdfPreviewContainer">
            <div className="pdfPreviewBody">
              <Viewer fileUrl="/pdf/test.pdf" />
            </div>
          </div>
</Worker>
```

I tried updating pdfjs-dist to 2.6.347 and it works, but.. do I have to update pdfjs-dist everytime they upgrade their module?

**Comment by phuoc-ng** [comment]
Thanks @laazaz. The issue is known and is mentioned in the [Basic usage](https://react-pdf-viewer.dev/docs/basic-usage) page.

However, I think we can fix it by asking the bundler (Webpack, for example) to use the `Worker` from the `pdfjs-dist` version installed in the `node_modules` folder.

I'll update here and the guide when I get this approach working.

**Comment by phuoc-ng** [comment]
@laazaz @nish5uec @jinuem @SimonCorellia 
Follow the steps below that uses `pdfjs-dist` 2.6.347 and `webpack` 4.43.0

1. Install `worker-loader`

```console
$ npm install --save-dev worker-loader
```

2. Ask Webpack to load `pdfjs-dist/webpack` when it sees `pdfjs-dist` import:

```js
// webpack.config.js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    plugins: [
       new webpack.NormalModuleReplacementPlugin(
            /^pdfjs-dist$/,
            resource => {
                resource.request = path.join(__dirname, './node_modules/pdfjs-dist/webpack');
            },
        ),
        ...
    ],
};
```

3. Build pdfjs worker:

```js
// webpack.config.js
const path = require('path');

module.exports = {
    entry: {
        main: './src/index.tsx',
        'pdf.worker': path.join(__dirname, './node_modules/pdfjs-dist/build/pdf.worker.js'),
    },
    output: {
        path: path.join(__dirname, 'dist'),
        filename: '[name].bundle.js'
    },
    ...
};
```

Webpack will build a worker named `pdf.worker.bundle.worker.js` located in the `dist` directory.

4. Set the worker source:

```js
import { Worker } from '@react-pdf-viewer/core';

<Worker workerUrl="/pdf.worker.bundle.worker.js">
    ...
</Worker>
```

**Comment by phuoc-ng** [comment]
I also added the [Compile and set the worker source with Webpack](https://react-pdf-viewer.dev/examples/compile-and-set-the-worker-source-with-webpack) example.

**Comment by akhfasarrofi** [comment]
> It used to work perfectly for a month, but since this morning it gives this error:
> 
> **The API version "2.5.207" does not match the Worker version "2.6.347".**
> 
> react-pdf-viewer (/core) version 2.3.2
> pdfjs-dist (that apparently got installed automatically with react-pdf-viewer) version: 2.5.207
> 
> my code:
> 
> ```
> <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js">
>         <div className="pdfPreviewContainer">
>             <div className="pdfPreviewBody">
>               <Viewer fileUrl="/pdf/test.pdf" />
>             </div>
>           </div>
> </Worker>
> ```
> 
> I tried updating pdfjs-dist to 2.6.347 and it works, but.. do I have to update pdfjs-dist everytime they upgrade their module?

> I think this part ```https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js```need to be same as in package json, i have experience something similar but my error in server and in my local is secure, and i change part ```https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js``` and done

**Comment by AnthonyGies** [comment]
You can also do like this : 

```
import packageJson from '/package.json'; // With correct path
<Worker workerUrl={`https://unpkg.com/pdfjs-dist@${packageJson.dependencies['pdfjs-dist'].replace(/^\^/, '')}/build/pdf.worker.min.js`}>
</Worker>
```
