### ISSUE TITLE
Expose APIs to jump between search/highlight elements as well as to disable/enable the match case and whole word filters in search plugin!

### ISSUE THREAD

**Issue by nish5uec** [react-pdf-viewer/react-pdf-viewer#451]
This requirement is extension of #427 
To give user complete control of search and highlight plugin programatically, above need to be implemented.

**Comment by phuoc-ng** [comment]
@nish5uec Supporting keyword flags was implemented.

_Demo_

```js
const searchPluginInstance = searchPlugin({
    keyword: {
        keyword: 'PDF',
        matchCase: false,   // The default value
        wholeWords: false, // The default value
    },
});
```

<img width="670" alt="Screen Shot 2021-02-08 at 21 06 50" src="https://user-images.githubusercontent.com/57786711/107230957-46a4cc80-6a52-11eb-85c0-d5f688eea51d.png">

```js
const searchPluginInstance = searchPlugin({
    keyword: {
        keyword: 'PDF',
        matchCase: true,
    },
});
```

There are 2 `PDF` words that will be highlighted:

<img width="665" alt="Screen Shot 2021-02-08 at 21 06 27" src="https://user-images.githubusercontent.com/57786711/107230755-080f1200-6a52-11eb-8100-7f6cde595b1e.png">

**Comment by phuoc-ng** [comment]
```js
const searchPluginInstance = searchPlugin();
const { highlight } = searchPluginInstance;

// Search for keyword
highlight([
    'document',
    {
        keyword: 'PDF',
        matchCase: true,
    },
])}
```

**Comment by phuoc-ng** [comment]
@nish5uec The Search plugin now exposes API to jump between matches

https://user-images.githubusercontent.com/57786711/107506546-cc4e8680-6bd0-11eb-9203-02323103982a.mp4

```js
const searchPluginInstance = searchPlugin();
const { jumpToPreviousMatch, jumpToNextMatch } = searchPluginInstance;
```

**Comment by nish5uec** [comment]
Thanks @phuoc-ng, can you please let me know due date for 2.4.0 release.

**Comment by nish5uec** [comment]
Thanks @phuoc-ng for the quick response, let me test out these functionalities.

**Comment by phuoc-ng** [comment]
Done.
