### ISSUE TITLE
[Bug] Loading pdf page stuck

### ISSUE THREAD

**Issue by okilled** [react-pdf-viewer/react-pdf-viewer#452]
## What happens?

Use Viewer component to load pdf page stuck, with iframe can open normally

## How To Reproduce

Use this address to import the pdf
> https://react-pdf-viewer.dev/examples/preview-a-pdf-file-before-uploading/

## Context

- **pdfjs-dist Version**:  2.6.347
- **@react-pdf-viewer/core Version**:  2.3.2

**Comment by phuoc-ng** [comment]
@okilled Can you try to rollback to `pdfjs-dist` 2.5.207?

```console
$ npm uninstall pdfjs-dist
$ npm install pdfjs-dist@2.5.207
```

`Worker` should use `2.5.207` as well:

```js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js">
    ...
</Worker>
```

**Comment by phuoc-ng** [comment]
The official website [now](https://react-pdf-viewer.dev/docs/getting-started/) [uses](https://react-pdf-viewer.dev/docs/basic-usage) `pdfjs-dist` 2.6.347!
So, you can keep the current version. 2.6.347, and update the worker:

```js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
    ...
</Worker>
```

I'll update the guide, so the worker should use the current version installed in `node_modules`.
See #445

**Comment by okilled** [comment]
> The official website [now](https://react-pdf-viewer.dev/docs/getting-started/) [uses](https://react-pdf-viewer.dev/docs/basic-usage) `pdfjs-dist` 2.6.347!
> So, you can keep the current version. 2.6.347, and update the worker:
> 
> ```js
> <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
>     ...
> </Worker>
> ```
> 
> I'll update the guide, so the worker should use the current version installed in `node_modules`.
> See #445

Thank you for your reply
I encounter the whole page does not respond when loading pdf, only some pdfs appear this situation

Download pdf
> http://sendanywhe.re/H90DDWZN

You can upload the downloaded pdf at the following address
> https://react-pdf-viewer.dev/examples/preview-a-pdf-file-before-uploading/

**Comment by phuoc-ng** [comment]
@okilled I can confirm that I can reproduce the issue.
I tried to open the PDF with [pdf.js viewer](https://mozilla.github.io/pdf.js/web/viewer.html), but it has the same issue.

It is the issue from pdf.js which can't parse this document.
