### ISSUE TITLE
Take out the toolbar completely

### ISSUE THREAD

**Issue by nataliaCodes** [react-pdf-viewer/react-pdf-viewer#455]
Hi,

First of all thank you so much for all the work you put into this package, the only PDF viewer I could actually get to work with my project straight away. However, looking at your docs, it says "By default, the Viewer component does not come with other parts such as toolbar and sidebar. If you want to have a full features viewer, please use the default-layout plugin.". And that is actually what I would like to happen, since the toolbar has a lot of buttons I don't need and it's not responsive. But just by following the set up instructions here https://react-pdf-viewer.dev/docs/basic-usage I do get the toolbar attached to the viewer and can't seem to take it out. I tried using the toolbar plugin to customize the buttons and take out what I don't need, but it didn't seem to work. Could you guide me through the steps of taking out the toolbar? I currently have this in my code:

import Viewer, { Worker } from '@phuocng/react-pdf-viewer';
import '@phuocng/react-pdf-viewer/cjs/react-pdf-viewer.css';

      <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js">
        <div id="pdfviewer">
            <div
              style={{
                overflow: 'hidden',
                height: '87em',
                border: '.5px solid gray',
              }}
            >
              <Viewer
                fileUrl={file}
                defaultScale="1.0"
              />
            </div>
        </div>
      </Worker>

Thank you so much!

**Comment by phuoc-ng** [comment]
@nataliaCodes 
`@phuocng/react-pdf-viewer` is the old legacy version and isn't supported anymore.

Please use the latest, up-to-date package (`@react-pdf-viewer/...`) by following the docs, starting from [this page](https://react-pdf-viewer.dev/docs/getting-started).

And you'll see the viewer without toolbar, sidebar, etc.

Now, if you want to bring the toolbar, see the [Toolbar plugin](https://react-pdf-viewer.dev/plugins/toolbar).
There are some examples at the bottom of Toolbar plugin page.

**Comment by nataliaCodes** [comment]
Thank you so much for your quick response! Switching to the newer version did indeed bring the viewer without the toolbar, as I wanted it. Thank you for the great work!

**Comment by phuoc-ng** [comment]
@nataliaCodes Awesome! Let me know if you have any questions.
