### ISSUE TITLE
Custom buttons for scrollmode do not work in v2.4.0

### ISSUE THREAD

**Issue by katrinewi** [react-pdf-viewer/react-pdf-viewer#473]
After upgrading the PDF-viewer to v2.4.0 the custom buttons for changing between vertical, horizontal and wrapped scroll mode no longer work .. The example is found here:  [ https://github.com/react-pdf-viewer/examples/blob/main/scroll-mode/CustomSwitchModeButtonsExample.tsx](https://github.com/react-pdf-viewer/examples/blob/main/scroll-mode/CustomSwitchModeButtonsExample.tsx)

**Comment by phuoc-ng** [comment]
Hi @katrinewi,

I just tried the [live example](https://react-pdf-viewer.dev/examples/customize-the-buttons-to-switch-the-scroll-mode), and it works fine.

<img width="1092" alt="Screen Shot 2021-02-24 at 22 43 23" src="https://user-images.githubusercontent.com/57786711/109025948-c8068b00-76f1-11eb-8426-1af672c12972.png">

Is there anyway that I can reproduce the issue?

**Comment by katrinewi** [comment]
Hi,
Is the live example also running in v2.4.0 ? I just thought it was a bit weird that my code worked before I updated, and after the update the custom scroll mode stopped working, so I just assumed that there had been some changes ... @phuoc-ng

**Comment by phuoc-ng** [comment]
@katrinewi 
The entire website, including all [examples](https://react-pdf-viewer.dev/examples/), run with the latest version 2.4.0.
Also, v2.4.0 mostly contains the changes in _Search plugin_. There's no changes in _Scroll Mode_ plugin.

* What happen if you use one of [these starters](https://github.com/react-pdf-viewer/starter) and use the exactly code in the example?

* Do you put the viewer within a container that has fixed height?

```js
<div style={{ height: '750px' }}>
  <Viewer ... />
</div>
```

**Comment by katrinewi** [comment]
@phuoc-ng 
Thank you for your answer. I found the error, and it was in my implementation, now everything works fine! 😄  I'm closing this issue!

**Comment by phuoc-ng** [comment]
@katrinewi 
Great! Let me know if you need anything else.
