### ISSUE TITLE
Download button doesn't work until we scroll to 2nd page

### ISSUE THREAD

**Issue by im-amir** [react-pdf-viewer/react-pdf-viewer#475]
When we open a pdf in a modal and click on the download icon, nothing happens.
But when we scroll to the 2nd page of the document and again click on the download icon, it downloads the document. So, if there is only one page of the document, we can never download the document by clicking on the download icon.

Also, when clicked on the zoom out, it starts working.

react-pdf-viewer version: 2.4.0
Using rsuit Modal

**Comment by phuoc-ng** [comment]
@im-amir Thanks for reporting the issue. It was fixed in the latest code, and the fix will be available in the next v2.4.1.

**Comment by im-amir** [comment]
@phuoc-ng 
Thank you!

**Comment by phuoc-ng** [comment]
@im-amir 
v2.4.1 was [released](https://react-pdf-viewer.dev/updates). Please update.
