### ISSUE TITLE
Organization License

### ISSUE THREAD

**Issue by handofthecode** [react-pdf-viewer/react-pdf-viewer#476]
Sorry for posting this here, but I don't see any other way to contact you.

If I purchase the "Organization" license, can I use this code in a commercial application?

Can the license be viewed before purchase?

Thanks!

**Comment by handofthecode** [comment]
Nevermind. I found it here: https://react-pdf-viewer.dev/license

**Comment by phuoc-ng** [comment]
Awesome! Let me know if you have any questions.

**Comment by phuoc-ng** [comment]
You can contact me directly via [Twitter DM](http://twitter.com/nghuuphuoc) or [email](mailto:me@phuoc.ng)
