### ISSUE TITLE
Support linear (web optimized) PDF

### ISSUE THREAD

**Issue by maikgramatte** [react-pdf-viewer/react-pdf-viewer#483]
When loading linear (web optimized) PDFs, PDFjs will send range requests to get e.g. the first two pages. After this it will load the entire PDF file. Once so ever the viewer will show loading state until the entire PDF is downloaded.

As we have this feature already baked into PDFjs, as the default, it would be beneficial if the PDF viewer could show the already loaded pages as early as possible.

**As a reference:**
- https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#pdfjs-is-fetching-the-entire-pdf-file-from-a-server-can-it-fetch-only-the-required-portions-for-rendering
- https://mozilla.github.io/pdf.js/web/viewer.html (This example is using a web optimized PDF)

**Comment by maikgramatte** [comment]
@phuoc-ng 
What I just did for my purpose: I just don't show the Loading state as PDFjs may will load the first page in a smaller range request and therefore this page can be rendered earlier. So maybe it's possible to just remove the Loading state or make it an optional feature to be toggle off/on.

**Comment by kdv24** [comment]
@maikgramatte or @phuoc-ng is there a code example of how you didn't show the loading state? Or, is there a better way? We have pdfs that are 1000 to 2000 pages long, and looking in the network tab, it appears rendering the first view is held up waiting for the full load to happen despite the relevant pages looking like they're loaded quickly. I'd love any direction on how to solve this! Thank you!

**Comment by phuoc-ng** [comment]
@maikgramatte @kdv24 
This was implemented in the latest code, and will be available in the next version.

**Comment by kdv24** [comment]
Yay! Thanks for the notification, @phuoc-ng.

**Comment by phuoc-ng** [comment]
It is supported in [v3.3.3](https://react-pdf-viewer.dev/updates/). Please upgrade!
