### ISSUE TITLE
Downloaded file (get file plugin) with Uint8Array

### ISSUE THREAD

**Issue by breezeful** [react-pdf-viewer/react-pdf-viewer#486]
When I load an Uint8Array into the fileUrl prop and use the getFilePlugin the downloaded file defaults a `.txt` and not a `.pdf` I tried the `fileNameGenerator` but just ended up with fileName.pdf.txt for example.

Can we have this default to .pdf extensions for Uint8Array loaded files? Or have an option to set that?

**Comment by phuoc-ng** [comment]
@breezeful It was fixed in [2.4.2](https://react-pdf-viewer.dev/updates). Please upgrade.
