### ISSUE TITLE
Selection mode plugin is always falling back to the specified default

### ISSUE THREAD

**Issue by maikgramatte** [react-pdf-viewer/react-pdf-viewer#487]
When specifying the selectionMode via the toolbarPlugin it will always fall back to this mode, even when changing it to Text using the MoreActionsPopover.
```javascript
const toolbarPluginInstance = toolbarPlugin({
    selectionModePlugin: {
      selectionMode: SelectionMode.Hand,
    },
  });
```

**Comment by phuoc-ng** [comment]
@maikgramatte 
Can you give how to reproduce the issue?

I tried the following code with latest 2.4.1

```js
const App = () => {
    const defaultLayoutPluginInstance = defaultLayoutPlugin({
        toolbarPlugin: {
            selectionModePlugin: {
                selectionMode: SelectionMode.Hand,
            }
        }
    });

    return (
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js">            
            <div
                style={{
                    height: '720px',
                    width: '640px',
                }}
            >
                <Viewer
                    fileUrl="/path/to/document.pdf"
                    plugins={[
                        defaultLayoutPluginInstance,
                    ]}
                />
            </div>
        </Worker>
    );
};
```

And it works fine.

https://user-images.githubusercontent.com/57786711/111032983-8e4bb900-8441-11eb-8969-4e02c27862e3.mp4

**Comment by maikgramatte** [comment]
@phuoc-ng I can confirm that this works perfectly for me. I was trying to set it using the `toolbarPluginInstance` or the `selectionModePlugin` and there I experienced the mentioned problem. But maybe that is due to using the default layout.

Maybe this is somehow worth to mention this in the documentation.

**Comment by phuoc-ng** [comment]
From the next 2.8.1, all the plugin instances provided by `default-layout` and `toolbar` plugins are read-only.
So if we are using TypeScript, we can't set it as following

```js
defaultLayoutPluginInstance.toolbarPluginInstance = toolbarPlugin: {
    selectionModePlugin: {
        selectionMode: SelectionMode.Hand,
    }
}
```

**Comment by phuoc-ng** [comment]
Done.
