### ISSUE TITLE
Can't change page numbers.

### ISSUE THREAD

**Issue by handofthecode** [react-pdf-viewer/react-pdf-viewer#492]
Can't delete the last remaining digit in the page number input. This makes it difficult to change page numbers. You can outsmart it by arrowing to the left and sneaking in a digit but it's a bad UX. Seems like at no time can there be a number in the input box that is outside of the pdf page range.

Better functionality would be, if a number is entered that is outside the range, it should just auto correct to 0 OR the highest page number **after** user presses enter.

**Comment by handofthecode** [comment]
Tested on Chrome and Safari.

**Comment by phuoc-ng** [comment]
It was fixed in [2.4.2](https://react-pdf-viewer.dev/updates). Please upgrade.
