### ISSUE TITLE
Allow to choose pages when printing a document

### ISSUE THREAD

**Issue by phuoc-ng** [react-pdf-viewer/react-pdf-viewer#494]

**Comment by kdv24** [comment]
@phuoc-ng do you know when this is likely to be added? We're needing this in our build we're working on now. I'm looking at how to modify the print dialog box to allow us to print and download only specific pages or sections of our pdf.

Thanks so much for all your work on this!

**Comment by kdv24** [comment]
@phuoc-ng is this likely to be something you add in the near future?

**Comment by phuoc-ng** [comment]
@kdv24 This will be supported soon.

## API

You're able to define the pages when printing a document via the `setPages` option. Is is a function that takes the current document and returns the list of zero-based index of pages you want to print.

```js
import type { PdfJs } from '@react-pdf-viewer/core';
import { printPlugin } from '@react-pdf-viewer/print';

const printPluginInstance = printPlugin({
    setPages: (doc: PdfJs.PdfDocument) => number[],
});
```

Here are some examples:

```js
// Only print the even pages
const printPluginInstance = printPlugin({
    setPages: (doc) =>
        Array(doc.numPages)
            .fill(0)
            .map((_, i) => i)
            .filter((i) => i % 2 === 0),
});

// Only print the odd pages
const printPluginInstance = printPlugin({
    setPages: (doc) =>
        Array(doc.numPages)
            .fill(0)
            .map((_, i) => i)
            .filter((i) => i % 2 === 1),
});
```

The option is also available when using the default layout plugin:

```js
const defaultLayoutPluginInstance = defaultLayoutPlugin({
    toolbarPlugin: {
        printPlugin: {
            setPages: ...,
        },
    },
});
```

## Demo

Here is the demo that we only print the odd pages:

https://user-images.githubusercontent.com/57786711/173097419-f706d9eb-3e8d-4a11-b927-57fd55287170.mp4

**Comment by phuoc-ng** [comment]
@kdv24 Is the API described above good for you?
Let me know your feedbacks, so I can adjust/improve, and release the feature soon.

**Comment by kdv24** [comment]
Hi @phuoc-ng thanks for looking at that. At this point we've built a download modal that has options for users to specify the following kinds of options for what they want to download to print:
- [ ] only the current page,
- [ ] custom (user inputted) ranges of pages (for example 1-4, 89, 101-200),
- [ ] by sections from a list like what appears through the bookmarks api. We've built a dropdown that we'd like to display the chapters or sections the way they do in the bookmarks api so users could select a given bookmarked section to download for printing.

Does that make sense?

**Comment by phuoc-ng** [comment]
@kdv24 The feature of setting print pages will be available in the next v3.6.0.

## API

```tsx
import { getEvenPagesNumbers } from '@react-pdf-viewer/print';
const printPluginInstance = printPlugin();

const { setPages } = printPluginInstance;

// Show UI for users to choose pages
const handleChooseEvenPages = () => setPages(getEvenPagesNumbers);

<label>
    <input type="radio" onChange={handleChooseEvenPages} />
    Print even pages
</label>;
```

## Demo 

Here is [sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/print-pages/index.tsx).

https://user-images.githubusercontent.com/57786711/174477853-36d69031-f45c-457b-9ad4-20cbbd9f41fa.mp4

**Comment by kdv24** [comment]
@phuoc-ng thank you! That's fantastic!

**Comment by kdv24** [comment]
@phuoc-ng is this same functionality available for the download button?

**Comment by phuoc-ng** [comment]
> is this same functionality available for the download button?

No. You might have to create another issue to track it. I don't have any idea how to do it at the moment.

**Comment by kdv24** [comment]
Okay. Thank you.

**Comment by phuoc-ng** [comment]
@kdv24 [v3.6.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!
I also created this [example](https://react-pdf-viewer.dev/examples/determine-the-target-pages-to-print-from-users-input/).
