### ISSUE TITLE
Using the Rotation actions is jumping randomly to other pages

### ISSUE THREAD

**Issue by maikgramatte** [react-pdf-viewer/react-pdf-viewer#495]
Issue can be reproduced on https://react-pdf-viewer.dev/. When using Rotation tools the Document will jump somehow "randomly" to other pages.

**Comment by phuocng** [comment]
Update: The issue was fixed in the latest code, and will be included in the next 3.9.0.

**Comment by phuocng** [comment]
Fixed in [v3.9.0](https://react-pdf-viewer.dev/updates/)
