### ISSUE TITLE
Set the initial page does not work

### ISSUE THREAD

**Issue by jjbier** [react-pdf-viewer/react-pdf-viewer#498]
Hi
I set the initial page manually. But the page always is not loads
I am doing something wrong?

```js
import { Worker, Viewer } from "@react-pdf-viewer/core";
import demoFile from "./demo.pdf";

export default function App() {
  return (
    <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
      <Viewer fileUrl={demoFile} initialPage={2} />
    </Worker>
  );
}
```
https://codesandbox.io/s/fast-fog-bdnf5?file=/src/App.js

**Comment by phuoc-ng** [comment]
@jjbier 
There're 2 missing things:

* Import the styles

```js
import "@react-pdf-viewer/core/lib/styles/index.css";
```

* Always put the `Viewer` inside a fixed container

```js
<div style={{ height: "720px" }}>
  <Viewer fileUrl={demoFile} initialPage={2} />
</div>
```

Here is the update version https://codesandbox.io/s/pensive-leakey-sy01h?file=/src/App.js:

**Comment by jjbier** [comment]
@phuoc-ng  thanks for your help

**Comment by Jbarget** [comment]
I feel like the docs could make this a lot clearer, especially for the "Set the initial page" example
https://react-pdf-viewer.dev/examples/set-the-initial-page/
