### ISSUE TITLE
pdfjs 2.7.570 breaks build for Create-React-Apps

### ISSUE THREAD

**Issue by aspnetde** [react-pdf-viewer/react-pdf-viewer#499]
I just want to leave that here: As with the latest versions of pdfjs-dist, my CRA app is broken as decribed [here](https://github.com/mozilla/pdf.js/issues/13239). I have no idea whether or not this might be a pdfjs problem, or if it might be related to react-pdf-viewer. 

Any insights are highly appreciated.

**Comment by phuoc-ng** [comment]
Thanks @aspnetde for reporting the issue.
I can reproduce the issue with pdfjs 2.7.570:

<img width="1075" alt="Screen Shot 2021-04-14 at 20 18 51" src="https://user-images.githubusercontent.com/57786711/114716985-cc990880-9d5e-11eb-80f3-d3a25cbbca27.png">

While I am investigating the issue, you should downgrade pdfjs.

**Comment by aspnetde** [comment]
Thx for looking into it. Staying with `2.6.347` works for me for now.

**Comment by phuoc-ng** [comment]
@aspnetde 
pdf.js 2.7.570 uses some special syntaxes such as 
- optional chaining (`a?.b`), 
- nullish coalescing operator (`a ?? b`) (you can see this operator in the message above)

That's the reason we see the unexpected token issue. It requires us to use Webpack 5.

I have just updated the [webpack](https://github.com/react-pdf-viewer/starter/tree/main/webpack) and [webpack-typescript](https://github.com/react-pdf-viewer/starter/tree/main/webpack-typescript) starters which works with `pdfjs` 2.7.570 and the latest version of Webpack 5.

However, `create-react-app` 4 [doesn't support](https://github.com/facebook/create-react-app/issues/9994) Webpack 5 yet.

So I think we should wait for it.

**Comment by aspnetde** [comment]
That's unfortunate, but I guess there's not much we/you can do here. If there will be any trouble before this is resolved on their end, I will consider to move away from CRA.

**Comment by Avhishek05** [comment]
> Thx for looking into it. Staying with `2.6.347` works for me for now.

@aspnetde How did you fix that I am also getting related issue.
![image](https://user-images.githubusercontent.com/23546633/115572191-4ee47800-a2dd-11eb-9687-331291ac67ae.png)

**Comment by aspnetde** [comment]
> How did you fix that I am also getting related issue.

With staying on 2.6 and not upgrading.

**Comment by smartcris** [comment]
is this version compatible with   pdfjs-dist  v. 2.8.335 ?

**Comment by phuoc-ng** [comment]
Let me try!

**Comment by cognvn** [comment]
My suggesstion:
https://github.com/react-pdf-viewer/react-pdf-viewer/blob/e7e1a5a6c3c2706198c71b57fff3cff285c5fe54/packages/core/src/vendors/PdfJsApi.ts#L9
For version  `2.7.570` (and `>= 2.4.456`), import from `pdfjs-dist/es5/build/pdf.js`.
For version `>= 2.8.335`, import from `pdfjs-dist/legacy/build/pdf.js`.

**Comment by chira37** [comment]
> My suggesstion:
> https://github.com/react-pdf-viewer/react-pdf-viewer/blob/e7e1a5a6c3c2706198c71b57fff3cff285c5fe54/packages/core/src/vendors/PdfJsApi.ts#L9
> 
> 
> For version `2.7.570` (and `>= 2.4.456`), import from `pdfjs-dist/es5/build/pdf.js`.
> For version `>= 2.8.335`, import from `pdfjs-dist/legacy/build/pdf.js`.

thanks it worked

**Comment by sifloz** [comment]
> My suggesstion:
> https://github.com/react-pdf-viewer/react-pdf-viewer/blob/e7e1a5a6c3c2706198c71b57fff3cff285c5fe54/packages/core/src/vendors/PdfJsApi.ts#L9
> 
> 
> For version `2.7.570` (and `>= 2.4.456`), import from `pdfjs-dist/es5/build/pdf.js`.
> For version `>= 2.8.335`, import from `pdfjs-dist/legacy/build/pdf.js`.

Could you please explane where do we import from?

I'm having the same issue of this topic, but I don't know what do you refer that import code from :/

**Comment by cognvn** [comment]
> 
> Could you please explane where do we import from?
> 
> I'm having the same issue of this topic, but I don't know what do you refer that import code from :/

That suggestion is for those who compile package themself.

You can use [`react-app-rewired`](https://github.com/timarney/react-app-rewired) to resolve `pdfjs-dist` yourself:
```js
/* <root directory>/config-overrides.js */
const path = require('path');

module.exports = {
  webpack: function (config, env) {
    // ...additional webpack config for your need
    config.resolve.alias['pdfjs-dist'] = path.join(__dirname, './node_modules/pdfjs-dist/legacy/build/pdf');
    return config;
  }
}
```
then start your React with `react-app-rewired start`

**Comment by phuoc-ng** [comment]
Thanks @cognvn 
I updated the starter for Create React App at https://github.com/react-pdf-viewer/starter/tree/main/create-react-app
