### ISSUE TITLE
Preventing PDF Clicks

### ISSUE THREAD

**Issue by Caaarrrlll** [react-pdf-viewer/react-pdf-viewer#502]
When displaying a PDF I would like to capture any click events from the pdf, I have pictures in the PDF that redirect the browser and I would like to open these pictures in a popup/modal instead, is there any way of preventing Worker/Viewer defaults or something in that line so I can accomplish this ?

**Comment by phuoc-ng** [comment]
It's not possible because each page is rendered as a canvas. So we can't know which element we clicked on.
