### ISSUE TITLE
Annotation popup is displayed under pages

### ISSUE THREAD

**Issue by phuoc-ng** [react-pdf-viewer/react-pdf-viewer#509]
<img width="628" alt="Screen Shot 2021-04-24 at 18 50 15" src="https://user-images.githubusercontent.com/57786711/115957669-fe178e00-a52d-11eb-994d-086b29f3727f.png">

**Comment by arqamtoptal** [comment]
hey I am still having the same issue, using "@react-pdf-viewer/core": "^3.12.0"
Any solution to this?
