### ISSUE TITLE
Internal links from PDF with annotations are off

### ISSUE THREAD

**Issue by maikgramatte** [react-pdf-viewer/react-pdf-viewer#516]
I worked with this kind of PDFs and the links are jumping one page after the designated page:

https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/src/annotations/Link.tsx#L34

For me it was sufficient to change it to:
`onJumpToDest(pageIndex, bottomOffset, 0, scaleTo);`

If you need a sample PDF, please let me know.

**Comment by phuoc-ng** [comment]
@maikgramatte Please give me the sample PDF.

**Comment by maikgramatte** [comment]
@phuoc-ng  Emailed you a PDF with those links

**Comment by phuoc-ng** [comment]
The issue was fixed in the latest code, and will be included in the next 2.4.3.

**Comment by phuoc-ng** [comment]
@maikgramatte 2.4.3 was [released](https://react-pdf-viewer.dev/updates). Please upgrade!
