### ISSUE TITLE
Feature request: make all PDFjs options configurable via Viewer

### ISSUE THREAD

**Issue by maikgramatte** [react-pdf-viewer/react-pdf-viewer#517]
PDFjs has many options for `PdfJs.getDocument`: https://mozilla.github.io/pdf.js/api/draft/module-pdfjsLib.html

It would be awesome if we could declare them in `Viewer`:  https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/src/loader/DocumentLoader.tsx#L60

**Comment by phuoc-ng** [comment]
Thanks for the suggestion, @maikgramatte 👍

**Comment by phuoc-ng** [comment]
@maikgramatte 
This was implemented in the latest code, and will be supported in the next v2.5.0:

```js
<Viewer
    fileUrl='...'
    transformGetDocumentParams={(options: PdfJs.GetDocumentParams) => (
        Object.assign({}, options, {
            disableRange: false,
            disableStream: false,
            // You can pass more pdf.js `getDocument` options here...
        })
    )}
/>
```

**Comment by phuoc-ng** [comment]
@maikgramatte 
[v2.5.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
