### ISSUE TITLE
Automatically zoom pdf to fit changing width of container

### ISSUE THREAD

**Issue by handofthecode** [react-pdf-viewer/react-pdf-viewer#526]
If I use an iFrame to display a pdf, the document and text always resizes/zooms based on the width of the container as it shrinks/grows. Is there a way to implement this behavior with this library?

**Comment by phuoc-ng** [comment]
The zoom plugin provides a function that you can [zoom the document](https://react-pdf-viewer.dev/examples/zoom-to-a-specific-level-programmatically) to specific level programmatically.

```js
// If you're using the zoom plugin
const customZoomPluginInstance = customZoomPlugin();
const { zoomTo } = customZoomPluginInstance;

<Viewer
    fileUrl={fileUrl}
    plugins={[
        customZoomPluginInstance,
    ]}
/>

// If you're using the default-layout plugin
const defaultLayoutPluginInstance = defaultLayoutPlugin();
const { zoomTo } = defaultLayoutPluginInstance. toolbarPluginInstance.zoomPluginInstance;

<Viewer
    fileUrl={fileUrl}
    plugins={[
        defaultLayoutPluginInstance,
    ]}
/>
```

My approach is to handle the `resize` event of the iframe (using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)), and whenever the iframe is resized, we zoom the document:

```js
zoomTo(SpecialZoomLevel.PageFit);
```

**Comment by phuoc-ng** [comment]
@handofthecode 
[v2.7.2 is released](https://react-pdf-viewer.dev/updates/). Please upgrade.
v2.7.2 automatically fits the pages within its container if you set the `defaultScale` to `SpecialZoomLevel.PageWidth`.
It happens when you resize the window/iframe as well.
