### ISSUE TITLE
There will be no loading Icon for a short time before the canvasLayer is rendered successfully

### ISSUE THREAD

**Issue by okilled** [react-pdf-viewer/react-pdf-viewer#527]
## What happens?

There will be no loading Icon for a short time before the canvasLayer is rendered successfully
![image](https://user-images.githubusercontent.com/23131376/117534626-da237480-b024-11eb-9d0f-f839e34b3a51.png)

## Expected behavior

Loading icon appears

## Context

- **@react-pdf-viewer/core**: 2.4.1
- **pdfjs-dist**: 2.6.347

**Comment by okilled** [comment]
> @okilled Does the issue happen with any document? From the screenshot above, does it happen in the pages or sidebar (thumbnails tab)?

thank you for your reply

yes, it happen with any document, happen in the pages 

It will be more obvious when zooming

**Comment by phuoc-ng** [comment]
@okilled You're right.
The issue was fixed in the latest code, and will be included in the next 2.4.3.

**Comment by okilled** [comment]
> @okilled You're right.
> The issue was fixed in the latest code, and will be included in the next 2.4.3.

Thank you!

**Comment by phuoc-ng** [comment]
2.4.3 was [released](https://react-pdf-viewer.dev/updates). Please upgrade!
