### ISSUE TITLE
Default Layout Plugin - 3 dotted "More actions" button doesn't work

### ISSUE THREAD

**Issue by breezeful** [react-pdf-viewer/react-pdf-viewer#536]
I noticed that the "More actions" button doesn't work anymore. There used to be a dropdown but doesn't seem to be registering a click.

![image](https://user-images.githubusercontent.com/62401227/118201923-ac746c00-b426-11eb-9546-89962afafe43.png)

**Comment by phuoc-ng** [comment]
You can see it working in the [official website](https://react-pdf-viewer.dev/)

<img width="1105" alt="Screen Shot 2021-05-14 at 20 28 19" src="https://user-images.githubusercontent.com/57786711/118277403-f4f95b80-b4f2-11eb-962a-1589c512fde0.png">

To make it work properly, don't forget to place the viewer inside a fixed height container, for example

```js
<div
    style={{
        height: '750px',
    }}
>
    <Viewer
        fileUrl='...'
        plugins={[
            defaultLayoutPluginInstance,
        ]}
    />
</div>
```
