### ISSUE TITLE
Slideshow / Single page view

### ISSUE THREAD

**Issue by beenham** [react-pdf-viewer/react-pdf-viewer#555]
Is there a way to render only the current page, similarly to a slide show? If not, I think it would be a nifty feature!

**Comment by phuoc-ng** [comment]
@beenham There's an example [here](https://react-pdf-viewer.dev/examples/slide-presentation)

**Comment by beenham** [comment]
Thanks for the quick reply,
I did see this example, although it still renders all the pages. For example, if the pdf does not fill the height of the viewer, you can see the next page below it.
It'd be nice to display just the current page and have it centered within the viewer

**Comment by jkeruzec** [comment]
I think I'm interested with only one page rendering because of speed and performance for display especially with large PDF.

**Comment by luyixin** [comment]
I feel so too

**Comment by phuocng** [comment]
@beenham @luyixin @jkeruzec 
This is supported in [v3.10.0](https://react-pdf-viewer.dev/updates/). I also create a similar example at https://react-pdf-viewer.dev/examples/magazine-layout/
