### ISSUE TITLE
[question] Is possible to use the default Toolbar plugin and set at false the option we dont want ?

### ISSUE THREAD

**Issue by LucaHermann** [react-pdf-viewer/react-pdf-viewer#571]
I'm interesting into using the toolbar but i don't want to let my users upload a PDF on it can i set as `false` the open file plugin inside without having to write my own custom toolbar ?

**Comment by LucaHermann** [comment]
as matter of fact is super easy to create a custom toolbar with you rplugin i consider this issue close

**Comment by phuoc-ng** [comment]
For anyone who has the same question, you can create a custom toolbar easily with Toolbar slot.
See https://react-pdf-viewer.dev/examples/toolbar-slot/

@LucaHermann Let me know if you have any questions.
