### ISSUE TITLE
highlight selection over 2 pages lead to a bug 

### ISSUE THREAD

**Issue by LucaHermann** [react-pdf-viewer/react-pdf-viewer#573]
[![Image from Gyazo](https://i.gyazo.com/2043f06bfe0d0aadb04ccdc0cea79fb0.png)](https://gyazo.com/2043f06bfe0d0aadb04ccdc0cea79fb0)

When i try to highlight over 2 different pages your func getRecBetween throw an error and sometime add a blank pages between the 2 selected pages.

Why ? and how get rid of this ?

**Comment by phuoc-ng** [comment]
Can you give me steps to reproduce the issue?

**Comment by LucaHermann** [comment]
you just have to select multiple line over 2 pages
