### ISSUE TITLE
highlight Index or size is negative or greater than the allowed amount

### ISSUE THREAD

**Issue by LucaHermann** [react-pdf-viewer/react-pdf-viewer#574]
[![Image from Gyazo](https://i.gyazo.com/a99b29de9fad638478f910f2990f1494.png)](https://gyazo.com/a99b29de9fad638478f910f2990f1494)

for some reasons highlights throw the error `Index or size is negative or greater than the allowed amount` what is this index and to what this refer ? 

How fix this ?

**Comment by phuoc-ng** [comment]
Please give me the steps to reproduce the issue.

**Comment by LucaHermann** [comment]
same than #573 select multiple lines over 2 pages or just one sometime with a .pdf

**Comment by phuoc-ng** [comment]
Can you give me the stack trace?
The error message in the screenshot comes from `highlight.js` which isn't part of the component, so it's not useful.

**Comment by LucaHermann** [comment]
how can i retrieve the stack trace ? tbh i have implement pspdfkit on the project but i can go into my previous commit for help you !

**Comment by LucaHermann** [comment]
Hi I'm gonna send you the stack trace ASAP because we implement your viewer again are you free for check and fix this together maybe ?

**Comment by phuoc-ng** [comment]
@LucaHermann That will be great! I can't reproduce the issue.
It's better if you can create a [codesandbox](https://codesandbox.io/) project that reproduces the issue.

**Comment by anooj-gandham** [comment]
Hi @phuocng 
https://codesandbox.io/s/divine-rain-mku09c

Please check the above codesandbox where I am still seeing this issue when I am selecting text using triple click.
I am just using the HighlightExample code from https://github.com/react-pdf-viewer/examples

![image](https://user-images.githubusercontent.com/63911217/226184322-77305769-65b8-469a-b53e-9a72ae7594f3.png)
![image](https://user-images.githubusercontent.com/63911217/226184337-2d6b814d-0686-4281-8cda-bc267c529673.png)

Can you please acknowledge if you are able to access with codesandbox?

Thanks you.
