### ISSUE TITLE
highlight selection fallback have a weird comportement

### ISSUE THREAD

**Issue by LucaHermann** [react-pdf-viewer/react-pdf-viewer#575]
https://user-images.githubusercontent.com/23220769/119944526-ac32af80-bf94-11eb-9863-e8cf8b51028a.mov

How get rid of this fallback comportement it annoying to don't be able to extend the selection and lead to an UX/UI experience really not smooth for the user.

We should be allow to select the area we want without this kind of fallback.

**Comment by phuoc-ng** [comment]
@LucaHermann This was improved in the latest code.
It will be included in the next 2.6.0.

**Comment by phuoc-ng** [comment]
_Demo_

It prevents users from selecting text that are before of the starting position

https://user-images.githubusercontent.com/57786711/121364525-0ef75400-c962-11eb-902f-897534ac0a22.mp4

**Comment by phuoc-ng** [comment]
[v2.6.0](https://react-pdf-viewer.dev/updates/) is released and includes the fix of this issue.
