### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component .

### ISSUE THREAD

**Issue by yulihai** [react-pdf-viewer/react-pdf-viewer#578]
![image](https://user-images.githubusercontent.com/25435061/119779991-dbe1a900-befb-11eb-8594-2d749c438457.png)
![image](https://user-images.githubusercontent.com/25435061/119948559-87a5fa00-bfcb-11eb-8e57-60a37a878c38.png)
![image](https://user-images.githubusercontent.com/25435061/119780098-fa47a480-befb-11eb-8386-701ce3dd2596.png)
![image](https://user-images.githubusercontent.com/25435061/119780120-0469a300-befc-11eb-8625-616cad898f4a.png)
![image](https://user-images.githubusercontent.com/25435061/119780183-13e8ec00-befc-11eb-8dd5-72201ac8dc6b.png)
![image](https://user-images.githubusercontent.com/25435061/119780218-1f3c1780-befc-11eb-9468-0341b832896d.png)
![image](https://user-images.githubusercontent.com/25435061/119780244-29f6ac80-befc-11eb-8268-eda8e1b3faab.png)
Ask for help ！！！！！！！！！！！

**Comment by phuoc-ng** [comment]
Please create a codesandbox project, so I can reproduce the issue.
Also, you should use `@react-pdf-viewer/core` package instead of `@phuocng/react-pdf-viewer`.

**Comment by travismiller** [comment]
FYI, I ran into this issue in the current version [2.11.0](https://github.com/react-pdf-viewer/react-pdf-viewer/releases/tag/v2.11.0) with React 17.

In my case, the default layout plugin instance needs to be instantiated within the scope of the component and not the file.

The README is a bit ambiguous and a little more explicitness in the example might be helpful. Thanks!

https://github.com/react-pdf-viewer/react-pdf-viewer/blob/dcb26df4996b4015fcfa1d4eefacbc750953ce2f/README.md#L7-L29

```jsx
// Core viewer
import { Viewer, Worker } from '@react-pdf-viewer/core'

// Plugins
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout'

// Import styles
import '@react-pdf-viewer/core/lib/styles/index.css'
import '@react-pdf-viewer/default-layout/lib/styles/index.css'

// Create new plugin instance ⛔️
// const defaultLayoutPluginInstance = defaultLayoutPlugin()

export const MyComponent = ({ fileUrl }) => {
  // Create new plugin instance ✅
  const defaultLayoutPluginInstance = defaultLayoutPlugin()

  return (
    <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
      <div style={{ height: '750px' }}>
        <Viewer
          fileUrl={fileUrl}
          plugins={[
            // Register plugins
            defaultLayoutPluginInstance,
          ]}
        />
      </div>
    </Worker>
  )
}
```
