### ISSUE TITLE
How can I use spanish language or customize labels?

### ISSUE THREAD

**Issue by iOrchK** [react-pdf-viewer/react-pdf-viewer#587]

**Comment by phuoc-ng** [comment]
Please take a look at the [Use a different language](https://react-pdf-viewer.dev/examples/use-a-different-language/)

**Comment by iOrchK** [comment]
Ok, I will take a look, thanks

**Comment by iOrchK** [comment]
How can I do it with jsx (not typescript)?
![image](https://user-images.githubusercontent.com/38798286/120878756-185c7700-c584-11eb-9445-7a424b548ecf.png)

**Comment by phuoc-ng** [comment]
You can simply do that

```js
<LocalizationProvider localization={vi_VN}>
...
</LocalizationProvider>
```
