### ISSUE TITLE
Outside click doesn't close more actions popover after scrolling

### ISSUE THREAD

**Issue by mezeiferenc** [react-pdf-viewer/react-pdf-viewer#598]
**Steps to reproduce:**
1. Click to "More actions" button to open the popover.
2. Scroll at least one page with mouse middle button or click to scrollbar.
3. Click anywhere outside the popover.

**Result:** Popover remains open.
**Expected:** Popover should be closed.

**Comment by phuoc-ng** [comment]
@mezeiferenc Thanks for reporting the issue. I can confirm that I can reproduce the issue.

**Comment by phuoc-ng** [comment]
@mezeiferenc 
We can reproduce the issue with other popovers, such as the zooming popover.

The issue was fixed in the latest code. It will be included in the next v2.6.0.

_Demo_

https://user-images.githubusercontent.com/57786711/121377958-f8a2c580-c96c-11eb-82bd-03bb83d26c7d.mp4

**Comment by mezeiferenc** [comment]
Thank you for the quick response! :)

**Comment by phuoc-ng** [comment]
@mezeiferenc 
[v2.6.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
