### ISSUE TITLE
Print stops all  javascript on page

### ISSUE THREAD

**Issue by stupkad** [react-pdf-viewer/react-pdf-viewer#602]
Hi there,

I tried integrating the react pdf viewer into an existing webproject following the boilerplate examples, which is more than easy. But we experienced a (at least for our usecase) serious issue. When the user is going to print the pdf (via the toolbar), all javascript execution is stopped until the print dialog is closed...

Is this a know issue, or does someone know a way how to circumvent this issue?

Thanks a lot,
Dietmar

**Comment by phuoc-ng** [comment]
There's an issue with #584 

You can reproduce in the live website by
* Pressing the Print button
* After printing, you can't open any popover such as zooming, more actions (on the right)

**Comment by stupkad** [comment]
Thanks a lot for the quick reply. When do you expect the new version to be released?
Actually I am using https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js

Thanks,
Dietmar

**Comment by phuoc-ng** [comment]
@stupkad 
[v2.6.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
