### ISSUE TITLE
question about Drop plugin

### ISSUE THREAD

**Issue by ReactDevOnline** [react-pdf-viewer/react-pdf-viewer#605]
Hello,
I was looking and researching about this exact pdf viewer, however, when I tried using it I did not find a way to disable one plugin which is a drop instance. I'm using a toolbar with different slots for the default layout and a viewer with a one registered plugin that I mentioned before. May I receive some advice on how to disable this drop plugin instance which I am not even using?

**Comment by phuoc-ng** [comment]
@ReactDevOnline 
In the next 2.6.0, the `drop` plugin won't be enabled by default. So, let's wait for the next 2.6.0.

**Comment by phuoc-ng** [comment]
See #608

**Comment by phuoc-ng** [comment]
@ReactDevOnline 
[v2.6.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.
