### ISSUE TITLE
Weird CSS for custom toolbar

### ISSUE THREAD

**Issue by breezeful** [react-pdf-viewer/react-pdf-viewer#617]
Also seen on the site as an example:
![image](https://user-images.githubusercontent.com/62401227/123147504-212ac500-d42d-11eb-8239-daa261fbb213.png)

https://react-pdf-viewer.dev/examples/create-a-floating-toolbar/

**Comment by breezeful** [comment]
Tooltip looks off too
![image](https://user-images.githubusercontent.com/62401227/123147562-2f78e100-d42d-11eb-85b2-9604a65816ff.png)

**Comment by phuoc-ng** [comment]
@breezeful Thanks for reporting the issue.
It's fixed [here](https://github.com/react-pdf-viewer/examples/pull/32/files)
I will update the official website later.

**Comment by phuoc-ng** [comment]
Fixed in [2.6.1](https://react-pdf-viewer.dev/updates/).
