### ISSUE TITLE
Accessibility of Page Input 

### ISSUE THREAD

**Issue by dmtrek14** [react-pdf-viewer/react-pdf-viewer#618]
In the page-navigation plugin, the CurrentPage input is created without a label (understandable as not everyone will want a visible form label), but that makes this input inaccessible for screen readers and other assistive technology. Adding an 'aria-label="Enter page number"' attribute to the Current page element would be appreciated. If not that, then can an id be added so that folks rolling their own toolbar can add their own label later in the stack?

**Comment by phuoc-ng** [comment]
That's great suggestion, @dmtrek14 
I'll add it in the next v2.6.1.

**Comment by phuoc-ng** [comment]
@dmtrek14 The v2.7.0 was released. Now you can use the Viewer completely with keyboard.
See more information at https://react-pdf-viewer.dev/updates/

**Comment by dmtrek14** [comment]
@phuoc-ng Awesome. Thanks for all that work. I've bumped my version and added back some features to the toolbar that I'd previously hidden; everything is working well and my client is happy with the changes. Again, really appreciate it.
