### ISSUE TITLE
CallBack support when thumbnail is clicked.

### ISSUE THREAD

**Issue by NaveenJ-ICARUS** [react-pdf-viewer/react-pdf-viewer#619]
Hello,

Thank you for this wonderful package. I've requirement that when the user clicks on the thumbnail image, I need to perform some application-specific tasks. 

is there any way to callback function to thumbnails?

Thank you in advance

**Comment by phuoc-ng** [comment]
I can support it in the next version v2.6.1.
Can I know more about the specific feature that you want to archive?

**Comment by NaveenJ-ICARUS** [comment]
Hello,

the requirement is, initially the user wants to see only thumbnails, on Clicking the particular thumbnail, the corresponding page should be shown. 

If you can provide the callback for thumbnail click,  with use if some CSS and jump to function. I can achieve this feature.


Adding to this, if possible, Could you please add a callback for the PDF canvas click event also?

**Comment by phuoc-ng** [comment]
@NaveenJ-ICARUS 
This feature was supported in the [v3.0.0](https://react-pdf-viewer.dev/updates/).
Here is an example https://react-pdf-viewer.dev/examples/customize-thumbnail-items/

Let me know if you need anything else.
