### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sendWithPromise' of null  

### ISSUE THREAD

**Issue by xb-developer** [react-pdf-viewer/react-pdf-viewer#620]
Good afternoon. It's been one day that I'm trying to fix this error when I'm clicking on a button to switch from a url to another. I tried to run a separate example on a new create-react-app project and here it works. When I'm trying to run exactly the same snipper of code inside of my app, I'm triggering this error.  The pdfjs dist and the worker have the same version, while the react-viewer-core it's updated to the latest version. I've seen previous issues like this, but none of those advices helped me go through it. Any idea what could trigger the issue?

**Comment by phuoc-ng** [comment]
Can you create a minimal repository that reproduces the issue?

**Comment by phuoc-ng** [comment]
Feel free to open when you provide the steps to reproduce the issue.
