### ISSUE TITLE
Support accessibility

### ISSUE THREAD

**Issue by phuoc-ng** [react-pdf-viewer/react-pdf-viewer#630]
## Goals
* Should follow WAI-ARIA 1.1 standards.
* Can use the entire component with keyboard only

_`core` components_
* [x] `Button`
* [x] `Icon` 
* [x] `Modal`
* [x] `Menu`
* [x] `MenuDivider`
* [x] `MenuItem`
* [x] `Popover`
* [x] `Tab`
* [x] `Textbox`
* [x] `Tooltip`

_`open` package_
* [x] File input

_`search` package_
* [x] Checkbox

_`thumbnail` package_
* [x] Thumbnails

_Shortcuts_
* [x] Use arrows to go to different menu items in a menu
* [x] Use arrows to go to previous and next page in the list of thumbnails
* [x] Use arrows to navigate between bookmarks
* [x] Press `Esc` to close a `Tooltip`
* [x] Print (`aria-keyshortcuts`)
* [x] Zoom (`aria-keyshortcuts`)

_Layers_
* [x] Page
* [x] Link annotation

**Comment by phuoc-ng** [comment]
cc @dmtrek14 We have a long list here!

**Comment by dmtrek14** [comment]
@phuoc-ng This is awesome. Thanks so much for including these improvements! Appreciate all you're doing with this project.

**Comment by phuoc-ng** [comment]
Done.
