### ISSUE TITLE
How to have blank fileUrl in Viewer until the user selects a file to view and the URL is known/available?

### ISSUE THREAD

**Issue by montclairskiclub** [react-pdf-viewer/react-pdf-viewer#641]
I've created a React FC for managing the React PDF Viewer component. This component will display files based upon the user selection.

The URL of the selected file is stored in local state

`const [fileUrl, setFileUrl] = React.useState<string>('');
`

then the Viewer is

```
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
    <Viewer fileUrl={fileUrl} />
</Worker>
```

 Initially "fileUrl" has an empty string. Then a user action makes an API call to the server which returns the data for "fileUrl" and the state value is set. However, this results in the following error when the page is initially loaded.

_Error: Invalid parameter object: need either .data, .range or .url_

How should this scenario be handled where there is no initial value for the Viewer fileUrl?

**Comment by phuoc-ng** [comment]
The `fileUrl` can't be empty. You can display something like

```js
const [fileUrl, setFileUrl] = React.useState<string>('');

// Your `render` function
if (fileUrl) {
    <Viewer
        fileUrl={fileUrl}
    />
} else {
    <div>
        <div>Please select a file from the list</div>

        {files.map(file => {
            <button onClick={() => setFileUrl(file)}>...</button>
        })}
    </div>
}
```
