### ISSUE TITLE
Async behaviour of setKeyWord in Search Plugin

### ISSUE THREAD

**Issue by charlesfrisbee** [react-pdf-viewer/react-pdf-viewer#672]
I have been using react-pdf-viewer to create a custom pdf search which is fired on each keystroke. I notice in your example on GitHub, it is run on enter keypress, which probably gives enough time for the setKeyWord function to successfully update the keyword/keywords to the previous keystroke before firing renderSearchProps.search(). I was wondering if there needs to be a promise returned from the setKeyWord function in order to ensure that renderSearchProps.search() is using the right value?

**Comment by phuoc-ng** [comment]
@charlesfrisbee 

`setKeyword` function doesn't take time, it runs really quick. However, `search` doesn't. For the first time, it has to query all the text of all pages, indexing them. This is perform only once, and the results are cached for the next use.

However, it's more user friendly if the `search` function returns `Promise` as you mentioned.
And then we can display a loading indicator informing that the search process isn't done yet.

Both were implemented in the latest code, and will be available in the next 2.7.0.

See #675 

_Demo_

https://user-images.githubusercontent.com/57786711/126888509-177293a8-d312-4cca-a037-482a4e969ff1.mp4

**Comment by phuoc-ng** [comment]
It's implemented in the v2.7.0:
* Adding a loading indicator while executing the `search` function
* The `search()` function returns a `Promise`.
