### ISSUE TITLE
SpecialZoomLevel.PageWidth overflows page on initial render with defaultLayoutPlugin at smaller container widths

### ISSUE THREAD

**Issue by ewalti** [react-pdf-viewer/react-pdf-viewer#698]
There seems to be a bug on the initial render of the `Viewer` using the `defaultLayoutPlugin` for smaller sizes (in the case provided, a container width of 600px works, but 550px does not).

The `0.5rem` padding on `.rpv-core__inner-page` seems to push the `.rpv-core__page-layer` to overflowX, causing scrollX bars to be present.

If you go up to the zoom controls and reselect "page width", it correctly sizes. Maybe something wrong with the initial render:

![overflowY](https://user-images.githubusercontent.com/1052436/127363141-03416aa2-7eb3-4431-873a-c0c2c06522ff.gif)

App.js
```
import "./styles.css";
import pdf from "./gre_research_validity_data.pdf";

import { Viewer, Worker } from "@react-pdf-viewer/core";
import { SpecialZoomLevel } from "@react-pdf-viewer/core";

import { defaultLayoutPlugin } from "@react-pdf-viewer/default-layout";

import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";

export default function App() {
  const defaultLayoutPluginInstance = defaultLayoutPlugin();
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <div className="box">
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.10.377/build/pdf.worker.min.js">
          <Viewer
            fileUrl={pdf}
            plugins={[defaultLayoutPluginInstance]}
            defaultScale={SpecialZoomLevel.PageWidth}
          />
        </Worker>
      </div>
    </div>
  );
}
```

index.css
```
.App {
  font-family: sans-serif;
  text-align: center;
}

.box {
  border: 1px solid red;
  width: 550px;
  height: 500px;
}
```

Repro example: https://codesandbox.io/s/beautiful-varahamihira-8f0tx?file=/src/App.js

I'll investigate, but just pinging for visibility. In my case, I just removed the padding, for now.

**Comment by phuoc-ng** [comment]
@ewalti Thanks for reporting the issue.
It was fixed in the latest code, and will be included in the next version.

_Demo_

https://user-images.githubusercontent.com/57786711/130354309-7849f05e-1efa-4840-a4e0-018e7210773a.mp4

**Comment by phuoc-ng** [comment]
@ewalti 
[v2.7.2 is released](https://react-pdf-viewer.dev/updates/). Please upgrade.
