### ISSUE TITLE
can i control the currentPage property in js

### ISSUE THREAD

**Issue by youbin06** [react-pdf-viewer/react-pdf-viewer#700]
hi, im front end engineer in korea.
i used your npm pdf-viewer library.
so my project's env is js file.
i want to used currentPage property in js file.
thanks!

**Comment by LucaHermann** [comment]
@youbin06 maybe give us more details about what you try to do and the context could help us for give you an explanation

**Comment by phuoc-ng** [comment]
@youbin06 Of course, you can use normal JS (not TypeScript) to use the component.
Please give me the sample code you can't make it work, then I can help you convert it to JS.

**Comment by phuoc-ng** [comment]
@youbin06 I guess you solve the issue. Feel free to reopen the issue or need more helps.

**Comment by youbin06** [comment]
oh i solve this issue, thx :)
