### ISSUE TITLE
switchTheme doesn't work when not in the default layout

### ISSUE THREAD

**Issue by fredc97** [react-pdf-viewer/react-pdf-viewer#701]
See this example : https://react-pdf-viewer.dev/examples/create-a-toolbar-with-more-options/

The switch theme doesn't change to dark... I have the same issue. The ThemeContext doesn't change in this case. Do you have a workaround ? Thanks. 

- I try to import the theme plugin directly instead of taking if from the toolbar slots => not working
- I don't use the default layout

**Comment by phuoc-ng** [comment]
@fredc97 I'll fix the issue.

**Comment by fredc97** [comment]
Thank you!

**Comment by meseven** [comment]
Hi,

I'm using the default toolbar `<Toolbar />` provided by the Toolbar plugin. But the toolbar theme does not change. Only Viewer changes. How can I fix that?


https://user-images.githubusercontent.com/1716620/162861061-1fd99b4d-6517-4dbc-95b7-253a34455fb4.mp4

My code:

```jsx

const toolbarPluginInstance = toolbarPlugin();
const { Toolbar } = toolbarPluginInstance;

const themeContext = {
  currentTheme,
  setCurrentTheme,
};

return (
  <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.13.216/build/pdf.worker.js">
    <ThemeContext.Provider value={themeContext}>
      <Toolbar />
      <Viewer fileUrl={fileUrl} theme={theme} plugins={[toolbarPluginInstance]} />
    </ThemeContext.Provider>
  </Worker>;
)
```
