### ISSUE TITLE
how can i fix memory leak problem for bookmark?

### ISSUE THREAD

**Issue by youbin06** [react-pdf-viewer/react-pdf-viewer#703]
![캡처](https://user-images.githubusercontent.com/39545095/128108037-f8f41fea-bc7b-4200-b4e7-b318bca435b5.PNG)

when i use bookmark plugin, having this problem ;(

**Comment by phuoc-ng** [comment]
Please give me the steps to reproduce the issue.

**Comment by youbin06** [comment]
This is my source file.
`<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
<Viewer fileUrl={url}
                    plugins={[
                      bookmarkPluginInstance,
                      pageNavigationPluginInstance,
                    ]}
                    characterMap={{
                      isCompressed: true,
                      url: '/node_modules/pdfjs-dist/cmaps/',
                    }}
                  />
                </Worker>`

url property is the element passed parent component `const { url } = props`

This is my project step of pdf

1. Button Click in parent component 
2. Passed url property to child component
3. Just load pdf using <Viewer /> in child component

**Comment by phuoc-ng** [comment]
@youbin06 I can't reproduce the issue.


https://user-images.githubusercontent.com/57786711/130347070-9ecfd60b-4b9a-48cf-b04d-843a300d2150.mp4

My sample code looks like

```js
const [url, setUrl] = React.useState('pdf-open-parameters.pdf');

return (
    <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.9.359/build/pdf.worker.js">
        <div className="demo">
            <div style={{ display: 'flex', marginBottom: '1rem' }}>
                <div style={{ marginRight: '.5rem'}}>
                    <Button onClick={() => setUrl('sample.pdf')}>Load sample.pdf</Button>
                </div>
                <div style={{ marginRight: '.5rem'}}>
                    <Button onClick={() => setUrl('sample-two-pages.pdf')}>Load sample-two-pages.pdf</Button>
                </div>
                <div style={{ marginRight: '.5rem'}}>
                    <Button onClick={() => setUrl('pdf-open-parameters.pdf')}>Load pdf-open-parameters.pdf</Button>
                </div>
            </div>
            <Viewer
                fileUrl={url}
                plugins={[defaultLayoutPluginInstance]}
            />
        </div>
    </Worker>
);
```

**Comment by youbin06** [comment]
thanks, i tried it! it is solved
