### ISSUE TITLE
Sometimes the highlighted search terms are not word-centered

### ISSUE THREAD

**Issue by fredc97** [react-pdf-viewer/react-pdf-viewer#707]
See the following screenshot : 

<img width="625" alt="Screen Shot 2021-08-05 at 5 18 40 PM" src="https://user-images.githubusercontent.com/43142809/128422759-a9c315d2-c669-445a-ab56-d92c6ed9a90a.png">

The same comportement happens in the demo in https://react-pdf-viewer.dev/

I use this document : https://escholarship.org/uc/item/9js5291m

**Comment by fredc97** [comment]
@phuoc-ng 
it is the same thing when we selected some text at some place. It is very random and the behavior change among the pages

See in the demo on https://react-pdf-viewer.dev/
<img width="959" alt="Screen Shot 2021-08-10 at 2 23 06 PM" src="https://user-images.githubusercontent.com/43142809/128914314-fec437a0-5d99-481a-a53c-42d421ac9ebf.png">

**Comment by phuoc-ng** [comment]
@fredc97 Please upgrade to the latest version of `pdfjs-dist`, and the problem is gone

![Screen Shot 2021-08-22 at 14 12 56](https://user-images.githubusercontent.com/57786711/130346061-693c07fa-1c9b-4394-8c67-216fbebb8fd7.png)

```shell
$ npm uninstall pdfjs-dist
$ npm install pdfjs-dist
```

Update the installed version in `Worker`, for example:

```js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.9.359/build/pdf.worker.js">
```

**Comment by fredc97** [comment]
I have this error now : 

./node_modules/pdfjs-dist/build/pdf.js 3473:145
Module parse failed: Unexpected token (3473:145)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|               numPages: this._numPages,
|               annotationStorage: this.annotationStorage.serializable,
>               filename: ((_this$_fullReader = this._fullReader) === null || _this$_fullReader === void 0 ? void 0 : _this$_fullReader.filename) ?? null
|             }).finally(() => {
|               this.annotationStorage.resetModified();

**I don't use webpack**

**Comment by phuoc-ng** [comment]
@fredc97 It's because pdfjs uses some modern syntax.
You can follow [this comment](https://github.com/react-pdf-viewer/react-pdf-viewer/issues/499#issuecomment-903406761)

**Comment by phuoc-ng** [comment]
@fredc97 
I updated the starter for Create React App https://github.com/react-pdf-viewer/starter/tree/main/create-react-app
Please follow its README.
