### ISSUE TITLE
can i detect the onchange event when changed page?

### ISSUE THREAD

**Issue by youbin06** [react-pdf-viewer/react-pdf-viewer#712]
To show current page number, i used pageNavigationPluginInstance.
this is my source code.
`<CurrentPageLabel>
                  {RenderCurrentPageLabelProps => (
                    <>
                      <strong className="cur-p">
                        {RenderCurrentPageLabelProps.currentPage + 1}
                      </strong>{' '}
                      /
                      <span className="tot-p">
                        {RenderCurrentPageLabelProps.numberOfPages}
                      </span>
                    </>
                  )}
                </CurrentPageLabel>`

i want to detect the onChange event when current page changed, cuz to store current page.

The pdf loaded again, i want to set initial page to current page stored.

**Comment by phuoc-ng** [comment]
Please take a look at this example
https://react-pdf-viewer.dev/examples/set-the-page-from-last-visit-as-the-initial-page/

**Comment by youbin06** [comment]
oh i got it!! thanks :)
