### ISSUE TITLE
Print stops all javascript on page

### ISSUE THREAD

**Issue by stupkad** [react-pdf-viewer/react-pdf-viewer#713]
Hi there,

I tried again integrating the react pdf viewer into an existing webproject following the boilerplate examples, which is more than easy. But we experienced a (at least for our usecase) serious issue. When the user is going to print the pdf (via the toolbar), all javascript execution is stopped until the print dialog is closed...

Same issue has been reported as issue #602, but seems to still exist in version 2.7.1.

Is this a know issue, or does someone know a way how to circumvent this issue?
Or is this by design?

Thanks a lot,
Dietmar

**Comment by stupkad** [comment]
Hi there,

I have asked the same question to the pdf.js team, but it seems this is a browser/specification limitation.

https://github.com/mozilla/pdf.js/issues/13888

Regards,
Dietmar

**Comment by phuoc-ng** [comment]
In this case, we can't do anything.
