### ISSUE TITLE
Downloading a pdf does not work in IOS devices

### ISSUE THREAD

**Issue by ReactDevOnline** [react-pdf-viewer/react-pdf-viewer#716]
When I click on download icon it opens up a pdf file with a link "blob:https://.../3927..." instead of downloading. When clicking on "Open in..." it says "The file could not be downloaded at this time.". It seems like the blob files are not supported in the IOS browsers. I would appreciate any sort of help.

**Comment by phuoc-ng** [comment]
Can I know the version of browser? Is the browser a Chrome iOS or Safari iOS?

**Comment by phuoc-ng** [comment]
Updated: The downloading issue on iOS Safari was fixed in the latest code.

![download-iOS](https://user-images.githubusercontent.com/57786711/141317807-36af22de-d276-4c35-8b35-0d4d99b540b5.PNG)

**Comment by phuoc-ng** [comment]
Updated: Fixed the issue on iOS Chrome

![download-chrome-ios](https://user-images.githubusercontent.com/57786711/141325296-141c3e31-1ccb-4c14-9d0c-dfcd5018c574.PNG)

**Comment by phuoc-ng** [comment]
@ReactDevOnline 
[v2.11.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade and let me know if you need anything else.
