### ISSUE TITLE
highlight() on a specific page

### ISSUE THREAD

**Issue by phuoc-ng** [react-pdf-viewer/react-pdf-viewer#723]

**Comment by phuoc-ng** [comment]
@nouredine This was implemented in the latest code.
In the next version (2.7.2), you're able to set the target pages that you want to search for. It is also affected when you call `searchFor` or `highlight` manually.

Usage looks like

```js
import { searchPlugin } from '@react-pdf-viewer/search';

const searchPluginInstance = searchPlugin();
const { setTargetPages } = searchPluginInstance;

// Only search in even pages
setTargetPages((targetPage) => targetPage.pageIndex % 2 === 0);

// Only search in the page 4
setTargetPages((targetPage) => targetPage.pageIndex === 3);

// Call `highlight` manually here ...
```

**Comment by phuoc-ng** [comment]
@nouredine Please take a look at the API mentioned in the comment above.
Let me know if there's any suggestion, otherwise I will include it in the next release.

**Comment by nouredine** [comment]
Dear @phuoc-ng,
here it is my current code
`
// ---- I call the search function with dynamic value and page number
<IconButton
	onClick={ev => pdfViewerRef.current.search(item['My Key'], item['Page num'])}
	className="p-0"
>
      <Icon color="secondary">location_on</Icon>
</IconButton>

// Current search function
const search = (keyword, pageNum)=>{
                        // ---- I'm looking for scrolling to pageNum and **highlighting** the keyword( a long text for my case) 
			highlight(keyword.split(' ')).then(data => {
			});
		}
/*--------------------------------------------------------------------------------------------------------------*/
// this how I'm guessing to implement your code on search function()
/*--------------------------------------------------------------------------------------------------------------*/
// Edited search function with the new code
const search = (keyword, pageNum)=>{
                        // ---- I'm looking for scrolling to pageNum and **highlighting** the keyword( a long text for my case) 
                        **// Only search in the page 4
                       setTargetPages((targetPage) => targetPage.pageIndex === pageNum);**
			highlight(keyword.split(' ')).then(data => {
			});
		}`
If you see this will be working for me, this what I'm looking for
Thank you @phuoc-ng

**Comment by phuoc-ng** [comment]
@nouredine 
[2.7.2 is released](https://react-pdf-viewer.dev/updates/). Please upgrade. 
Feel free to open new issue if you see any problems with the new API.

**Comment by nouredine** [comment]
Dear @phuoc-ng
Really it's working as expected ! 
I can’t thank you enough for your help !

**Comment by phuoc-ng** [comment]
@nouredine Awesome ❤️ 
Let me know if you have any suggestions, so I can make the library better.

**Comment by erictu22** [comment]
Hello! `setTargetPages` doesn't seem to have any effect on the `highlight` function in `3.11.0`

**Comment by erictu22** [comment]
Nevermind. I resolved my own issue here: https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1654
