### ISSUE TITLE
Hi can i install jumpToPagePlugin or create jumpToPagePlugin as js ?

### ISSUE THREAD

**Issue by youbin06** [react-pdf-viewer/react-pdf-viewer#731]
Hi, i watched your source code (jumpToPagePlugin.tsx) to do test.

1. It is released in current version? so,  can i install(npm) this plugin? 

or

2. I will create jumpToPagePlugin source coed in my project? 
but my project (webpack) not supported in typeScript. (Module parse failed: The keyword 'interface' is reserved)
so, can you support plugin source code in js?

**Comment by phuoc-ng** [comment]
@youbin06 Please give me the link to `jumpToPagePlugin.tsx`

**Comment by youbin06** [comment]
This is the link!
https://github.com/react-pdf-viewer/examples/blob/main/jump-to-given-page/jumpToPagePlugin.tsx

**Comment by phuoc-ng** [comment]
The normal JS version looks like

```js
import * as React from 'react';
import { createStore } from '@react-pdf-viewer/core';

const jumpToPagePlugin = () => {
    const store = React.useMemo(() => createStore(), []);

    return {
        install: (pluginFunctions) => {
            store.update('jumpToPage', pluginFunctions.jumpToPage);
        },
        jumpToPage: (pageIndex) => {
            const fn = store.get('jumpToPage');
            if (fn) {
                fn(pageIndex);
            }
        },
    };
};

export default jumpToPagePlugin;
```
