### ISSUE TITLE
Selecting only first page from the PDF

### ISSUE THREAD

**Issue by bylly1** [react-pdf-viewer/react-pdf-viewer#732]
I want to render only first page of the PDF. How I do that?

**Comment by bylly1** [comment]
I have a page in my site where I want to render first page of all PDFs and user must to choose what PDF should open

**Comment by phuoc-ng** [comment]
@bylly1 I created this example for you
https://github.com/react-pdf-viewer/examples/tree/main/display-a-thumbnail-of-the-given-page

The entry point is [DisplayThumbnailExample.tsx](https://github.com/react-pdf-viewer/examples/blob/main/display-a-thumbnail-of-the-given-page/DisplayThumbnailExample.tsx)

**Comment by bylly1** [comment]
> @bylly1 I created this example for you
> https://github.com/react-pdf-viewer/examples/tree/main/display-a-thumbnail-of-the-given-page
> 
> The entry point is [DisplayThumbnailExample.tsx](https://github.com/react-pdf-viewer/examples/blob/main/display-a-thumbnail-of-the-given-page/DisplayThumbnailExample.tsx)

Thanks for helping me!
