### ISSUE TITLE
Highlights should render below text

### ISSUE THREAD

**Issue by sirkrisp** [react-pdf-viewer/react-pdf-viewer#738]
Hi, it seems that the highlights are rendered above the text layer instead of below it. Is there any way to fix this? Thanks! Kris

**Comment by phuoc-ng** [comment]
You're right. So we can't select the text which is highlighted. I guess it's the reason you asked for this issue.
I'll fix it.

**Comment by phuoc-ng** [comment]
@sirkrisp [v2.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.

**Comment by Braweria** [comment]
@phuoc-ng  The same issue is when a user highlights text themselves, the highlight is above the text instead of below. See here
https://codesandbox.io/s/react-pdf-viewer-i545h?file=/src/App.js

My version is 
```
    "@react-pdf-viewer/core": "2.9.1",
    "@react-pdf-viewer/default-layout": "^2.9.1",
    "@react-pdf-viewer/highlight": **"^2.9.1",
```
