### ISSUE TITLE
Selection event

### ISSUE THREAD

**Issue by GlenOFI** [react-pdf-viewer/react-pdf-viewer#739]
Your product looks great and it looks like it can do everything I want except when a selection is made (text or area), it doesn't look like there is an event to listen to to get the selected data? Is this correct or does this feature already exist? If it doesn't, would you consider adding it?

Thanks.

**Comment by phuoc-ng** [comment]
It has something like this in the [Highlight](https://react-pdf-viewer.dev/plugins/highlight/) plugin.
Maybe is it a thing you're looking for?

**Comment by GlenOFI** [comment]
OK thanks. I had a look at the Highlight plugin and it looks like I can get the selected text as props in renderHighlightTarget and renderHighlightContent. If the user wants to select an image or a table, how would I get that data as an image?

**Comment by phuoc-ng** [comment]
> If the user wants to select an image or a table, how would I get that data as an image?

It's not possible.

**Comment by GlenOFI** [comment]
One more question on this, from you last response I can see that it is not currently possible in this product. But is it technically possible to be implemented? ie it isn't implemented right now but could it be?

**Comment by phuoc-ng** [comment]
@GlenOFI It is not possible technically because the images, table, etc., are embedded in the `canvas` element. I can't do anything with it.
I will not close an issue if it's possible for me to implement, even in the future.

**Comment by GlenOFI** [comment]
OK, thanks a lot.
