### ISSUE TITLE
Can I replace workerUrl ?

### ISSUE THREAD

**Issue by youbin06** [react-pdf-viewer/react-pdf-viewer#742]
Hello, 
I want to import pdf.worker.min.js file in my project folder.
and use like this.
`<Worker workerUrl="./pdf.worker.min.js">`

but it was rendering, apply the base url (like http://localhost:3000/pdf.worker.min.js) automatically.

**Comment by phuoc-ng** [comment]
@youbin06 Please take a look at this example
https://react-pdf-viewer.dev/examples/compile-and-set-the-worker-source-with-webpack/
