### ISSUE TITLE
UI elements stop working after using material UI DatePicker

### ISSUE THREAD

**Issue by FretboardRunner** [react-pdf-viewer/react-pdf-viewer#745]
We have the issue that occasionally some of the UI elements stop working.

After some debugging I could narrow it down to the Material UI KeyboardDatePicker component:
https://material-ui-pickers.dev/api/KeyboardDatePicker

Once that was used, the element to select a zoom level and the "more options" button in React PDF Viewer no longer work. My assumption is, that the DatePicker somehow interferes with the overlays that are opened when clicking on the elements.

Any ideas on how to avoid this behavior?

**Comment by phuoc-ng** [comment]
@FretboardRunner In v2.7.2, I fixed a similar issue (#714), where we can't close the zooming menu when using the https://github.com/microsoft/fluentui library.

Can you upgrade to the latest version?
If the issue still happens, can you create a [codesandbox](https://codesandbox.io/) project that reproduces the issue?

**Comment by FretboardRunner** [comment]
Perfect, that also fixed our issue, thanks a lot!
