### ISSUE TITLE
Lazyloading pages & Preventing automatic pdf downloads by IDMs

### ISSUE THREAD

**Issue by KimeraMoses** [react-pdf-viewer/react-pdf-viewer#746]
Hey, is there a way to LAZYLOAD pages, i tried loading a relatively large pdf but the experience wasn't awesome at all, i have to wait for some time for the entire pdf to load and for some mobile devices that have tried loading my site on, the browser throws an error of NOT ENOUGH MEMORY and does not load the pdf at all, can we lazyload pages?
Also, when opened on a machine with any internet download Manager, the pdf does not load and an error is displayed but rather initiate download through the Idm installed. i would like the pdf to ONLY be downloaded when the download button is clicked. thanks

**Comment by phuoc-ng** [comment]
You can take a look at this [quote](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#pdfjs-is-fetching-the-entire-pdf-file-from-a-server-can-it-fetch-only-the-required-portions-for-rendering):

> Actually, PDF.js is doing just that. PDF is a complicated format; in most of the cases, the vital data of a PDF document is located at the end. Depending on browser support and on what web server returns the HTTP Range Requests headers, PDF.js may automatically start using HTTP Range Requests to fetch not-yet-loaded portions of a PDF needed for rendering visible pages, so a document can be rendered without fully loading it.

It means that for a PDF document that isn't optimized for the web, we have to download the entire documents to have enough information to display it.

As soon as the document is ready, on the rendering part, `@react-pdf-viewer` only renders the visible pages.
It also lazy loads the document if the container isn't visible.

> Also, when opened on a machine with any internet download Manager, the pdf does not load and an error is displayed but rather initiate download through the Idm installed

I don't know how to fix that. It seems that the software always try to download all the files on the page.

**Comment by KimeraMoses** [comment]
How about disabling the download functionality until the download button is clicked?
