### ISSUE TITLE
Password filled programmatically

### ISSUE THREAD

**Issue by lillogoal** [react-pdf-viewer/react-pdf-viewer#762]
I have a question about protected pdf. I uploaded a pdf with password in viewer and it asked to me password. 
Can i fill this form and submit programmatically, for example automatically onPdfLoaded ? 

Thanks

**Comment by phuoc-ng** [comment]
Currently, it's not possible. But I will think about supporting it. Thanks for the suggestion.

**Comment by lillogoal** [comment]
Thanks. Can i fork or make new pull request? How to do ?

**Comment by phuoc-ng** [comment]
I am sorry, it doesn't accept PRs because it's a commercial product.
Can you give me the idea of how you can pass the password?

**Comment by lillogoal** [comment]
Ok ok thanks to reply. Have you assigned an id or input ref to textfield where user have to type password ? And button? 

Sorry for my question but before buy library i Need to understand

**Comment by lillogoal** [comment]
Ok i tested with Javascript console. And it works. Exist a callback that called when password dialog/page prompts to user ?

This is the code:

```
const input = document.querySelector('.rpv-core__textbox');

Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set.call(input, "pippo");

document.querySelector('.rpv-core__primary-button').click();
```

**Comment by phuoc-ng** [comment]
@lillogoal 
The feature was implemented in the latest code. In the next v2.9.0 version, you can do something as following:

```js
const handleAskPassword = (e: DocumentAskPasswordEvent) => {
    e.verifyPassword('The password here');
};

<Viewer onDocumentAskPassword={handleAskPassword} />;
```

You don't have to set the input value and submit button manually.
I also added a [test case](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/__tests__/onDocumentAskPassword.test.tsx) for it.

**Comment by lillogoal** [comment]
Thanks ♥️ do you want close ? When do you deploy ? Thanks

**Comment by phuoc-ng** [comment]
@lillogoal The [v2.9.0](https://react-pdf-viewer.dev/updates/) is released.
I also added a live example for your use case
https://react-pdf-viewer.dev/examples/submit-the-password-programmatically/

Let me know when you make the purchase ♥️

**Comment by lillogoal** [comment]
no words only thanks. I have already written to my PM and in this week CEO is going to buy license

**Comment by phuoc-ng** [comment]
Awesome! Let me know if you have any questions or suggestions, so I can make the library better.
