### ISSUE TITLE
Remove horizontal scrollbar from pdf viewer inside modal

### ISSUE THREAD

**Issue by MrPhyaeSoneThwim** [react-pdf-viewer/react-pdf-viewer#773]
I am using Material UI dialog to show pdf file using react-pdf-viewer. When I'm using these two things together,  the horizontal scrollbar is showing near the bottom of modal dialog content. And then I look at how the css is implemented for pdf viewer but the css properties are used as inline. So can you guide me the right way to remove the horizontal scrollbar...
![error](https://user-images.githubusercontent.com/83585609/132991923-9d7472a3-fa93-4b65-b08b-3dc12b990bac.png)

**Comment by phuoc-ng** [comment]
@MrPhyaeSoneThwim Please fork this [project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) and produce the issue, so I can help.

**Comment by MrPhyaeSoneThwim** [comment]
https://codesandbox.io/s/react-pdf-viewer-forked-7xidm

I have done Sir. You can check my code there.

**Comment by MrPhyaeSoneThwim** [comment]
By the way, how can I set the dynamic height of Viewer without giving it parent container height with fixed value..
For eg.

<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
    <Box style={{ height: "600px" }}>
        <Viewer fileUrl={sample_doc} plugins={[pageNavigationPluginInstance]} />
    </Box>
</Worker>

If I remove the Box wrapper component and use Viewer component alone, the scrollbar is working but the page navigation controls don't work to navigate the page

**Comment by phuoc-ng** [comment]
@MrPhyaeSoneThwim I created #775 to track the request.
