### ISSUE TITLE
Handling viewer scrollbar with keyboard input (up and down key)

### ISSUE THREAD

**Issue by MrPhyaeSoneThwim** [react-pdf-viewer/react-pdf-viewer#774]
It's just my features request. I like the current library too much because it's is lightweight and have so many plugins to customize.
And I would you like to add scroll up and down functionalities with keyboard input (up & down keys) will make the library more attractive.

**Comment by phuoc-ng** [comment]
In order to scroll up/down, users have to click the pages container first. Then they can scroll using the `Up`, `Down` arrow keys.
What kind of shortcuts/behavior do you want?
