### ISSUE TITLE
Pinch to Zoom from mobile (fullscreen) or/and toolbar

### ISSUE THREAD

**Issue by lillogoal** [react-pdf-viewer/react-pdf-viewer#777]
Hi,

Today i started using react-pdf-viewer, i can say one word: great job!!

I have tested from my mobile (android) and it is quite responsive, i don't know how to zoom in fullscreen because i haven't toolbar and pinch to zoom is disabled.

Best regards

**Comment by phuoc-ng** [comment]
This feature will be available in the next version.

**Comment by lillogoal** [comment]
woow fantastic!! Thanks
Best regards

**Comment by phuoc-ng** [comment]
@lillogoal @carlitosz @cesarlarsson @longfellowone @ivan-leschinsky
Updated:
The feature was implemented in the latest code, and will be available in the next release.

_Demo_
In the full screen mode, the _Full screen_ button in the toolbar turns into the exit full screen mode button automatically.

![Screen Shot 2021-11-30 at 21 05 57](https://user-images.githubusercontent.com/57786711/144063864-09ad69fd-377c-4684-98c2-6ce68cfa65b7.png)

**Comment by phuoc-ng** [comment]
@lillogoal @carlitosz @cesarlarsson @longfellowone @ivan-leschinsky
[v3.0.0](https://react-pdf-viewer.dev/updates/) was released. Please upgrade!

Here is the example that demonstrates that new feature
https://react-pdf-viewer.dev/examples/include-the-default-toolbar-in-the-full-screen-mode/
