### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by Nityashasinha1999** [react-pdf-viewer/react-pdf-viewer#778]
![image](https://user-images.githubusercontent.com/51985938/133620412-949b4e60-c35c-4b2f-a5b8-5c4fa3e87731.png)

**Comment by phuoc-ng** [comment]
Please take a look at the _Using the latest version of pdfjs-dist_ section on the [Getting started](https://react-pdf-viewer.dev/docs/getting-started) page

![Screen Shot 2021-09-16 at 21 06 55](https://user-images.githubusercontent.com/57786711/133627032-b803bb90-ea6d-4c1d-9f36-0f026ca1f2de.png)

**Comment by lillogoal** [comment]
@Nityashasinha1999 are you developing in react js + typescript ?
What version are you using of pdfjs-dist ?
