### ISSUE TITLE
Constant high CPU usage for large documents

### ISSUE THREAD

**Issue by sirkrisp** [react-pdf-viewer/react-pdf-viewer#779]
Hi,

the CPU usage is extremely high for large documents and it STAYS high even when not scrolling. 
Pdftron does not have this problem even though it is also based on PDF.js
For a sample document, you can download the script [here](https://www.sam.math.ethz.ch/~grsam/NCSE20/NumCSE_Lecture_Document.pdf).

Thanks for your help!

Best,
Kris

PS: maybe related: https://www.syncfusion.com/forums/135328/constant-high-cpu-usage-after-loading-pdf-file-or-stream-in-pdfdocumentview-control

**Comment by sirkrisp** [comment]
@phuoc-ng 
I think I might know the issue. After profiling the pdf viewer it turns out that for a document with many pages the "Update Layer Tree" and "Recalculate Style" computations take up 50% of the computation even though, visually, nothing should change when not scrolling. 

After closer inspection of what causes the recalculate style, it turns out we have a bunch of "rpv-core__spinner-transform" animation events (try window.onanimationiteration = console.log in the developer console, https://stackoverflow.com/questions/8910396/chrome-timeline-how-can-i-determine-the-cause-of-a-recalculate-style-log-ent). So, I think what happens is that for a document with 800 NOT yet loaded pages we get 800 spinners that cause a huge CPU usage. 

So to fix it you have to make sure that spinners only animate when they are visible.

Would be great if you could give this issue high priority because we launch next week.

Thanks a lot!

Best,
Kris

**Comment by phuoc-ng** [comment]
@sirkrisp Thanks for reporting the issue. It's also a good catch 👍 
Based on your suggestion, I fixed the issue.

The v2.9.1 is just released. Please upgrade!
