### ISSUE TITLE
When printing a preview, the display area is small

### ISSUE THREAD

**Issue by zwj7181** [react-pdf-viewer/react-pdf-viewer#780]
![20210919213940](https://user-images.githubusercontent.com/16178272/133929767-22af68d0-bc40-420f-8e2e-5280fafb332b.png)
When I click print, the preview screen is very small. What is the reason?

**Comment by phuoc-ng** [comment]
@zwj7181 Please fork this [project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) and let me know the steps/document to reproduce the issue.

**Comment by zwj7181** [comment]
It cannot be reproduced in this project. It should be influenced by other factors in my own project

**Comment by zwj7181** [comment]
It may be influenced by the global img style
