### ISSUE TITLE
Highlight using x/y coordinates and page numbers 

### ISSUE THREAD

**Issue by dsac147** [react-pdf-viewer/react-pdf-viewer#785]
Hello  @phuoc-ng and Team,

I have a use case where I want to **highlight certain words and sentences using their x/y coordinates and page numbers** that will be sent from the backend api. As per my understanding, we do not currently have a feature/plugin for that.

- I tried highlighting using keywords api in the search plugin but it highlights all instances of the word. 
- Highlight plugin can only be activated on text selection. 

Can you guide me on how to achieve this functionality using the current version and if not, can I make a feature request for the same? We at our organization are very much interested in buying the commercial license for our purpose and this highlight functionality is an integral part of our product.

Thank You!

**Comment by faangpath** [comment]
Hi authors! This is a use-case that we also have. Here's an example of where the keyword API won't work -- We have the following sentences in the PDF: 
A: "Their house is red."
B: "They're mean people"
C: "They're house is red"

We want to highlight the "they're" from 'C' to indicate that there is a grammatical error. However, using keywords API it is highlighting all the "they're".

The data we have available from a PDF Parser is:

- Absolute X/Y Location of the "they're" from C
- Page number of C

Is this something we can send to the PDF Viewer to highlight only the "they're" from C? If no, please suggest what the alternative is.

**Comment by phuoc-ng** [comment]
@dsac147 @faangpath 
It's possible. You don't need to use the search or highlight plugin. However, before giving you an example, I want to ask this question.

Does the data from back-end (or your parser) support highlighting multiple items in multiple sentences?

I think the input should be

* The page number
* An array of items indicate the area you want to highlight. Each item should include

```
x, y: The absolute location of area
w, h: The width and height of area
```

**Comment by dsac147** [comment]
@phuoc-ng 
Thank You for replying!

**_Q. Does the data from back-end (or your parser) support highlighting multiple items in multiple sentences?_**
Yes. Infact the input data structure you mentioned is the exact format our backend parser uses and sends to client.

If you could provide an example with/without multiple lines, it would be really helpful.

Thanks!

**Comment by phuoc-ng** [comment]
@dsac147 @faangpath 
I created this [live example](https://codesandbox.io/s/react-pdf-viewer-highlight-coordinates-plugin-c4b9h)

![Screen Shot 2021-09-30 at 07 30 24](https://user-images.githubusercontent.com/57786711/135366510-382874bf-bde1-4fe3-ab1a-8eca5a79f5c6.png)

It is a custom plugin that will highlight the areas when users rotate the document

![Screen Shot 2021-09-30 at 07 31 37](https://user-images.githubusercontent.com/57786711/135366551-8cb8a0fb-e6eb-4037-80da-29ad622e6af3.png)

The list of areas have the following structure:

```js
interface HighlightArea {
  height: number;
  left: number;
  pageIndex: number; // Zero-based index
  top: number;
  width: number;
}
```

The `height`, `width`, `left`, `top` are percentage values. So the area will be displayed properly when users zoom the document.

Let me know if you have any questions.

**Comment by phuoc-ng** [comment]
@dsac147 @faangpath

Updated: I added new `trigger` option for the `highlight` plugin:

```js
import { Trigger } from '@react-pdf-viewer/highlight';

const highlightPluginInstance = highlightPlugin({
    trigger: Trigger.None,
});
```

There are two possible values for the `trigger` option:

| Value                             | Description                                                                   |
| --------------------------------- | ----------------------------------------------------------------------------- |
| `Trigger.TextSelection` (default) | Show the target after users select text                                       |
| `Trigger.None`                    | Doesn't trigger the highlight. It is often used to render the highlight areas |

So, in the next version, you can use `Trigger.None`. See this [sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/highlight-trigger-none/index.tsx#L57)

**Comment by phuoc-ng** [comment]
@dsac147 @faangpath Do you have a chance to try it?

**Comment by timnlupo** [comment]
@dsac147 Were you able to get this working? Mine still does not update when you change the areas. I believe this is the same issue as #835

**Comment by dsac147** [comment]
> @dsac147 Were you able to get this working? Mine still does not update when you change the areas. I believe this is the same issue as #835

I was able to wait for data from backend and render highlights when done. I can explain that to you.
However I'm not sure you'll be able to re-render it multiple times on hitting different API endpoints. I didn't try that.
