### ISSUE TITLE
Can I change error message? (404 error) 

### ISSUE THREAD

**Issue by youbin06** [react-pdf-viewer/react-pdf-viewer#788]
![캡처](https://user-images.githubusercontent.com/39545095/135015176-7407a202-f0a4-40b3-a824-bdc245895263.PNG)

Hi, I want to change this error message when 404 error occured.
(ex, img, or another msg, etc...)
Can I change or customize that messgae?

**Comment by phuoc-ng** [comment]
@youbin06 Please take a look at this example
https://react-pdf-viewer.dev/examples/customize-error-renderer/
