### ISSUE TITLE
rotate one page in a document

### ISSUE THREAD

**Issue by bluetailgreg** [react-pdf-viewer/react-pdf-viewer#792]
is it possible to only rotate the selected page and not all pages in the document?

**Comment by phuoc-ng** [comment]
How would you like to rotate a given page?
From a context menu when right-clicking a page or from an API to do it programmatically?

**Comment by bluetailgreg** [comment]
Ideally by using the existing rotate buttons in the tool bar.

**Comment by bluetailgreg** [comment]
any feedback on whether this can be supported?

**Comment by irudyi-carecloud** [comment]
Is this ticket alive? Is there a way to rotate one page/thumbnail?

**Comment by phuoc-ng** [comment]
Yes, supporting this is on the roadmap. I probably can support it in 3.2.0. Rightnow, I am focusing on [v3.1.0](https://github.com/react-pdf-viewer/react-pdf-viewer/milestone/29)

**Comment by phuoc-ng** [comment]
@bluetailgreg @irudyi-carecloud 
The feature was implemented in the latest code, and will be available in the next release (v3.2.0).
There are 3 entry points that you can add this functionality to your application. See the next comments.

**Comment by phuoc-ng** [comment]
## 1. Create a custom thumbnail item

In this example, we add two buttons to each thumbnail item. These buttons can be used to rotate the associate page.

```tsx
const renderThumbnailItem = (props: RenderThumbnailItemProps) => (
    <MinimalButton onClick={() => props.onRotatePage(RotateDirection.Forward)}>
        <RotateForwardIcon />
    </MinimalButton>
    <MinimalButton onClick={() => props.onRotatePage(RotateDirection.Backward)}>
        <RotateBackwardIcon />
    </MinimalButton>
);

const thumbnailPluginInstance = thumbnailPlugin();
const { Thumbnails } = thumbnailPluginInstance;

<Thumbnails renderThumbnailItem={renderThumbnailItem} />
```

See the [full sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/thumbnail-rotate-page/index.tsx)

_Demo_

https://user-images.githubusercontent.com/57786711/161422949-d968fd2b-099b-4320-876b-014a692cf637.mp4

**Comment by phuoc-ng** [comment]
## 2. Customize page renderer

This example adds two buttons to each page.

```tsx
const renderPage: RenderPage = (props: RenderPageProps) => (
    <>
        {props.canvasLayer.children}
        <div>
            <MinimalButton onClick={() => props.onRotatePage(RotateDirection.Forward)}>
                <RotateForwardIcon />
            </MinimalButton>
            <MinimalButton onClick={() => props.onRotatePage(RotateDirection.Backward)}>
                <RotateBackwardIcon />
            </MinimalButton>
        </div>
        {props.annotationLayer.children}
        {props.textLayer.children}
    </>
);

<Viewer renderPage={renderPage} />;
```

See the [full example code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/core-rotate-page-with-thumbnails/index.tsx).

_Demo_
https://user-images.githubusercontent.com/57786711/161423062-e0e46965-aa6d-4f90-9372-332e319d513a.mp4

**Comment by phuoc-ng** [comment]
### 3. Using external buttons

The rotate plugin adds new `RotatePage` component in case you want to rotate a particular page from outside:

```tsx
const rotatePluginInstance = rotatePlugin();
const { RotatePage } = rotatePluginInstance;

<RotatePage>
    {(props) => <PrimaryButton onClick={() => props.onRotatePage(0, RotateDirection.Forward)}>Rotate the first page forward</PrimaryButton>}
</RotatePage>
<RotatePage>
    {(props) => <PrimaryButton onClick={() => props.onRotatePage(0, RotateDirection.Backward)}>Rotate the first page backward</PrimaryButton>}
</RotatePage>
```

See the [full example code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/rotate-page-with-thumbnails/index.tsx).

_Demo_
https://user-images.githubusercontent.com/57786711/161423216-434991cf-665a-4bbe-a05f-d3e302f07f00.mp4

**Comment by phuoc-ng** [comment]
The `onRotatePage` event is triggered when a page is rotated, so you can integrate with your back-end:

```tsx
<Viewer
    onRotatePage={({ direction, doc, pageIndex, rotation }) => {
        // `direction` is the rotate direction
        // `doc` is the current document
        // `pageIndex` is the zero-based page index
        // `rotation` is the latest rotation value
    }}
/>
```

**Comment by phuoc-ng** [comment]
@bluetailgreg @irudyi-carecloud 
[v3.2.0](https://react-pdf-viewer.dev/updates/) provides different approaches to do that. Please upgrade.
