### ISSUE TITLE
How to get properties from PDF document?

### ISSUE THREAD

**Issue by Braweria** [react-pdf-viewer/react-pdf-viewer#799]
I know there is the Plugin  
https://react-pdf-viewer.dev/plugins/properties/
But it only returns React Elements, I tried looking through the Source Code to find an alternative but wasn't successful. How can I get the metadata of a PDF Document so I can handle the data myself?

For example, get the author and title of a pdf and display it in `<title>` so it is in the Tab.  
![image](https://user-images.githubusercontent.com/62669899/135470821-96c5a0bd-7c46-4901-a0ef-3d47edca46b3.png)

Or do other stuff with the information.

**Comment by phuoc-ng** [comment]
@Braweria You can call APIs from the document instance:

```js
// Assume `doc` is the instance of current document
doc.getMetadata()
    .then((meta) => {
        return Promise.resolve(meta);
    })
    .then((meta) => {
       console.log(meta); 
    });
```

You can get the `doc` instance by handling the `onDocumentLoad` event:

```js
import { DocumentLoadEvent, Viewer } from '@react-pdf-viewer/core';

const onDocumentLoad = (e: DocumentLoadEvent) => {
    // `e.doc` is the document instance
};

<Viewer fileUrl="/path/to/document.pdf" onDocumentLoad={onDocumentLoad} />;
```

**Comment by Braweria** [comment]
That did it, thank you.
