### ISSUE TITLE
The text highlighted is wrong after searching

### ISSUE THREAD

**Issue by popoyatou** [react-pdf-viewer/react-pdf-viewer#808]
After searching a keyword, when the user highlights some text, the recognized text of this highlight is wrong although the location information recognized is correct.

**Comment by phuoc-ng** [comment]
@popoyatou Can you give me the steps to reproduce using this [sample project](https://codesandbox.io/s/react-pdf-viewer-sample-yc8ut)?

**Comment by alexmoraru-toptal** [comment]
It's also have this issue, on the latest version 3.1.2.

Repro steps:
Run the app on a smaller screen (ex 14inch laptop) or smaller size browser window.
Use the `searchPlugin` and also the `highlightPlugin` on the same Viewer. 
Have the search plugin highlight some keywords.
Select a piece of text with and you will see that the `props.selectedText` from the `renderHighlightContent (highlightPlugin)` is wrong. Usually it returns the text from 1 row above the selected area. 
However, interestingly enough, the highlight area is correct, only the `selectedText` is wrong.

**Comment by hamza1216** [comment]
@popoyatou same issue in the 3.4.0.
If the search keyword is cleared out before selecting text to be highlighted, it works well.
Can we also have a callback after the text is selected?
