### ISSUE TITLE
Search highlight will be wrong when i have a zoom out scale

### ISSUE THREAD

**Issue by helianthuswhite** [react-pdf-viewer/react-pdf-viewer#816]
I just use the example in https://react-pdf-viewer.dev/examples/zoom-to-a-specific-level-programmatically/.
When i set the scale to "Page fit", the highlight of search keywords will get a wrong position. But if i zoom in, it will be ok.

![image](https://user-images.githubusercontent.com/12878076/137473090-31ab4841-10ca-417f-a205-a85edf1b9614.png)
![image](https://user-images.githubusercontent.com/12878076/137473172-d5ecdfb6-14fa-4ac5-975d-b36cfb558453.png)

**Comment by phuoc-ng** [comment]
If you want to search within the document, please use the [Search plugin](https://react-pdf-viewer.dev/plugins/search/).
