### ISSUE TITLE
Bracket search issue

### ISSUE THREAD

**Issue by ankushkatiyar** [react-pdf-viewer/react-pdf-viewer#830]
Hi, I'm not able to search bracket in react pdf viewer.
I tried searching like this "op 1 juli 2020 is het Instituut Mijnbouwschade Groningen (IMG)" but I don't get any data, when I remove (IMG) then I got data. Can someone knows about this ?

**Comment by phuoc-ng** [comment]
@ankushkatiyar 
Thanks for reporting the issue. It was fixed in the latest code, and will be included in the next version.

_Demo_

https://user-images.githubusercontent.com/57786711/140651654-b7357290-fbbc-4484-adf6-055e9ee40554.mp4

**Comment by phuoc-ng** [comment]
@ankushkatiyar 
[v2.11.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade and let me know if you need anything else.

**Comment by ankushkatiyar** [comment]
Hi @phuoc-ng I checked and it's working fine now, Thanks
