### ISSUE TITLE
Saving Highlights is broken, does not save the correct content and is not rendering it

### ISSUE THREAD

**Issue by Braweria** [react-pdf-viewer/react-pdf-viewer#831]
Hello, I build the feature of highlighting text from the PDF and saving it, and it would display in the sidebar, just as you have explained it in one of your tutorials. That has worked great as well.

Now I have moved to the newer version and updated it accordingly, but suddenly the highlights do not work anymore correctly and I can't understand why. I have also moved to a previous commit in history (with a clean install as well), but the issue somehow persists, which I find very weird.

I have created a sandbox: https://codesandbox.io/s/adoring-lucy-3wqrp?file=/src/App.js

If you select any text and then press the button to highlight it, you will see that the text did not get highlighted. If you check the sidebar notes you can also see, that it did not save the correct content either.  

I am at a loss here. I didn't change anything on the function from the previous time when it did work. I tested it with versions 2.10.1 and 2.9.1.

---

Another thing, unrelated to this issue, I just noticed that [this component](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/94d74753d6283e7afc83a6677384105cb15489c2/packages/thumbnail/src/LabelsLoader.tsx) is throwing warnings because it has no cleanup. Would you welcome a PR on this?

**Comment by Braweria** [comment]
Hey @phuoc-ng , any updates yet?

**Comment by phuoc-ng** [comment]
@Braweria 

The issue was fixed in the latest code. I will include it in the next version.

_Demo_

https://user-images.githubusercontent.com/57786711/140649350-f94f4884-919a-49f8-ac21-1ee005acc6e6.mp4

**Comment by Braweria** [comment]
@phuoc-ng This is great! Thank you for your time and effort on this. :)

And just to repeat my other question from the Issue:
> Another thing, unrelated to this issue, I just noticed that [this component](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/94d74753d6283e7afc83a6677384105cb15489c2/packages/thumbnail/src/LabelsLoader.tsx) is throwing warnings because it has no cleanup. Would you welcome a PR on this?

**Comment by phuoc-ng** [comment]
@Braweria 
[v2.11.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade and let me know if you need anything else.
