### ISSUE TITLE
License key after license purchase.

### ISSUE THREAD

**Issue by noclueabout** [react-pdf-viewer/react-pdf-viewer#832]
After purchasing a license for commercial use I got a license key. How and where do I use it? I didn't manage to find any information either in documentation or in the examples provided.

**Comment by dsac147** [comment]
Thanks! Please update us if and when you want us to include the license key in the component. @phuoc-ng

**Comment by flckv** [comment]
does this mean that if I use the [react-pdf-viewer](https://github.com/react-pdf-viewer/react-pdf-viewer) for personal use only then no purchase is necessary?
