### ISSUE TITLE
Print a pdf with several pages

### ISSUE THREAD

**Issue by FDEINC** [react-pdf-viewer/react-pdf-viewer#833]
I have a PDF with several pages.
I can preview it and download,it, but when I want to print it I can only print first page.
I use : 
React 16.12.0, 
react-pdf-viewer: 2.10.1

My code :

`      <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.10.377/build/pdf.worker.min.js">
        <div
          style={{
            height: '800px',
          }}
        >
          <Viewer
            localization={(fr_FR as unknown) as LocalizationMap}
            fileUrl={URL.createObjectURL(file)}
            plugins={[defaultLayoutPluginInstance]}
            renderLoader={(percentages: number) => (
              <div style={{ width: '240px' }}>
                <ProgressBar progress={Math.round(percentages)} />
              </div>
            )}
          />
        </div>
      </Worker>`

**Comment by phuoc-ng** [comment]
@FDEINC 
Dose the issue happen with all documents or just a particular document?
Can you fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut), update the layout and give me steps to reproduce the issue?

**Comment by FDEINC** [comment]
@phuoc-ng 
All Document, and try this file pdf-open-parameters.pdf
I see all 8 pages
When I click print button I have in network console 8 download

Look screenshots

![Capture](https://user-images.githubusercontent.com/93389015/139526161-3f211963-6a78-4b2b-a24e-7a44cbeb9bd7.JPG)
![Capture2](https://user-images.githubusercontent.com/93389015/139526162-9af3472d-9acc-4cae-8885-36b1690e402e.JPG)
 blob:http://localhost:3000/78546ef6-........

**Comment by FDEINC** [comment]
Code :

import React from 'react';
import { Viewer, Worker } from '@react-pdf-viewer/core';
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';

const App: React.FC = () => {
  const defaultLayoutPluginInstance = defaultLayoutPlugin();

  return (
    <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.10.377/build/pdf.worker.min.js">
      <div
        style={{
          height: '800px',
        }}
      >
        <Viewer
          fileUrl={`${process.env.PUBLIC_URL}/pdf-open-parameters.pdf`}
          plugins={[defaultLayoutPluginInstance]}
        />
      </div>
    </Worker>
  );
};

export default App;

**Comment by FDEINC** [comment]
Pakage.json 👍 

{
  "name": "helical-ui",
  "version": "1.60.4",
  "private": true,
  "dependencies": {
    "@react-pdf-viewer/core": "^2.10.1",
    "@react-pdf-viewer/default-layout": "^2.10.1",
    "@types/react": "^16.9.56",
    "@types/react-dom": "^16.9.5",
    "eslint-config-airbnb-typescript": "^7.2.0",
    "eslint-plugin-react": "^7.18.3",
    "http-proxy-middleware": "^1.0.2",
    "pdfjs-dist": "^2.10.377",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "^4.0.3"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "eject": "react-app-rewired eject",
    "test": "react-app-rewired test"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/node": "^14.14.41",
    "@typescript-eslint/eslint-plugin": "^4.22.0",
    "@typescript-eslint/parser": "^4.22.0",
    "eslint": "^7.24.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "^2.0.5",
    "react-app-rewired": "^2.1.8",
    "react-is": "^16.13.0",
    "typescript": "^4.2.4"
  }
}

**Comment by FDEINC** [comment]
I have solve the problem by remove  "position" property in css :

html, body, #root {
  **position: fixed;**
  height: 100%;
  width: 100%;
}

replace by :

html, body, #root {
  height: 100%;
  width: 100%;
}

**Comment by phuoc-ng** [comment]
Thank you, @FDEINC 👍
