### ISSUE TITLE
Failed to go around this issue, Please help!

### ISSUE THREAD

**Issue by KimeraMoses** [react-pdf-viewer/react-pdf-viewer#834]
Hello, I'm using react-pdf-viewer and things were working fine but when I changed a machine and cloned my repo from git, this is what I get when I try to run my application.
The issue seems to be from pdfs but I have failed to get any way to fix it. Any suggestions on how to go a round it are highly appreciated. Thanks

Failed to compile
./node_modules/pdfjs-dist/build/pdf.js 2293:47
Module parse failed: Unexpected token (2293:47)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|           async getXfa() {
>             return this._transport._htmlForXfa?.children[this._pageIndex] || null;
|           }
|
This error occurred during the build time and cannot be dismissed.

**Comment by phuoc-ng** [comment]
@KimeraMoses 
What's the webpack version?

- If it's Webpack 4, please see this section https://react-pdf-viewer.dev/docs/getting-started/

![Screen Shot 2021-11-01 at 19 02 34](https://user-images.githubusercontent.com/57786711/139668501-b404e2d4-f9f0-4472-adc8-62d64acdeab2.png)

- If you're running Webpack 5, try to update NodeJS.

**Comment by KimeraMoses** [comment]
I'm using  -- webpack@4.44.2 and "pdfjs-dist": "^2.6.347".

**Comment by phuoc-ng** [comment]
@KimeraMoses 

1. If you can't upgrade to Webpack 5, follow the setting guide based on your starter here https://github.com/react-pdf-viewer/starter
2. Try to upgrade to Webpack 5
3. Upgrade NodeJS.

**Comment by KimeraMoses** [comment]
I have upgraded to webpack@5.61.0 and I'm running v12.18.3 of NodeJS and I'm now getting a new set of error that react is run

//******************************//
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.44.2"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\webpack (version: 5.61.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "webpack" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\webpack is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls webpack in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed webpack.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gpa_elevator_v3@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gpa_elevator_v3@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by KimeraMoses** [comment]
On adding SKIP_PREFLIGHT_CHECK =true to .env file, i still get the following error
//***************************//
E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

TypeError: Cannot read property 'tap' of undefined
    at E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\@pmmmwh\react-refresh-webpack-plugin\lib\index.js:236:65
    at SyncHook.eval [as call] (eval at create (E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:13:1)
    at SyncHook.lazyCompileHook (E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\react-scripts\node_modules\webpack\lib\Compiler.js:631:26)
    at E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\react-scripts\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\react-scripts\node_modules\webpack\lib\Compiler.js:662:28)
    at E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\react-scripts\node_modules\webpack\lib\Watching.js:77:18
    at _next0 (eval at create (E:\2020 Projects\gpa_elevator_v3.1_diploy\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gpa_elevator_v3@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gpa_elevator_v3@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by phuoc-ng** [comment]
I see the following error from the message above:

```js
The react-scripts package provided by Create React App requires a dependency:
"webpack": "4.44.2"
```

It seems that `react-scripts` doesn't support Webpack 5. You have to revert to use Webpack 4 in this case.

Can you try to upgrade NodeJS?

**Comment by phuoc-ng** [comment]
@KimeraMoses Can you update the solution so it might help other one?

**Comment by KimeraMoses** [comment]
I upgraded NodeJS as instructed but it did not solve the issue completely and with the new error message received, I cloned the application from my repository, installed the core react-pdf-viewer dependencies  and after successfully running the application with the pdfs showing as expected, I installed all the other dependencies one by one while testing for the functionalities of react-pdf-viewer. This then showed me that there were some dependencies that were conflicting with the version of Webpack that I had installed.

**Comment by phuoc-ng** [comment]
Thanks, @KimeraMoses 👍
