### ISSUE TITLE
Programmatically Rerender Highlight Plugin

### ISSUE THREAD

**Issue by timnlupo** [react-pdf-viewer/react-pdf-viewer#835]
Hello! 

I am using the highlighting plugin as demonstrated in [here](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/highlight-trigger-none/index.tsx). I am hitting an API to get the bounding box of the areas- this all works great.

However, I want to hit an API and get new highlight areas.  I want to trigger a highlight rerender when this happens to update the PDF. I tried setting a state but it seems that `renderHighlights` is memoized and stuck in time from the moment it's instantiated. So updating the highlights has no effect.

I also tried re-instantiating / storing the actual plugin as a state, but got a hooks violation. Is there any way to programmatically force a highlight "rerender" to display an updated highlight area?

Thanks so much.

**Comment by timnlupo** [comment]
I found a kinda sketchy workaround for now.

Adding a key prop [forces the component to rerender](https://stackoverflow.com/questions/35792275/how-to-force-remounting-on-react-components), hence rerendering the plugin.

```
  ...
  const [x, forceUpdate] = useReducer((x) => x + 1, 0);

  useEffect(() => {
    const highlights = getHighlightAreas();
    setAreas(highlights);
    forceUpdate();
  }, [result]);

  return (
    <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js">
      <div style={{ height: "100vh", width: "100%" }}>
        <RenderHighlightAreasExample areas={areas} fileUrl={url} key={x} />
      </div>
    </Worker>
  );
```

**Comment by phuoc-ng** [comment]
@timnlupo The next version will support rendering dynamic areas.
It provides a new function named `setHighlightAreas`. See the [example](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/highlight-dynamic-areas/index.tsx#L63)

https://user-images.githubusercontent.com/57786711/140605830-6221dee8-5203-4638-a4fa-fd78ebfc512b.mp4

**Comment by phuoc-ng** [comment]
@timnlupo 
Updated: In the next version, you don't have to do anything. It just works.
See the [updated example](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/highlight-dynamic-areas/index.tsx).

**Comment by timnlupo** [comment]
This is awesome! Thank you. When do you think this will be released?

**Comment by phuoc-ng** [comment]
@timnlupo 
[v2.11.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade and let me know if you need anything else.
