### ISSUE TITLE
Remove or hide sidebar

### ISSUE THREAD

**Issue by Nightbr** [react-pdf-viewer/react-pdf-viewer#836]
Hey,
I'm looking to disabled the sidebar, I tried with defaultLayoutPlugin like this:

```typescript
  const defaultLayoutPluginInstance = defaultLayoutPlugin({
    sidebarTabs: (defaultTabs) => null,
  });
```

But it seems the listTabs cannot be null. `Uncaught TypeError: listTabs is null`.

Could be great if we can handle this case in the defaultLayout to disable the sidebar.

Thanks in advance!

**Comment by phuoc-ng** [comment]
@Nightbr 
First of all, thanks for making the purchase. It definitely supports my works.
Regarding the question, if you don't want to use the sidebar, you don't need to use the Default Layout plugin.
Instead, you can use the [Toolbar plugin](https://react-pdf-viewer.dev/plugins/toolbar/).

Here is the example of [using the default toolbar](https://react-pdf-viewer.dev/examples/use-the-default-toolbar/).

**Comment by Nightbr** [comment]
> First of all, thanks for making the purchase. It definitely supports my works.

Sure thing, your work deserves it :ok_hand: 

Yes, I use directly the toolbar plugin, but I lost the style of the default layout. I think it could be a nice little improvement to be able to disable the sidebar using the defaultLayout plugin :ok_hand: 

Here is my custom code if anyone has the same need:

```typescript
 const toolbarPluginInstance = toolbarPlugin();
  const { Toolbar } = toolbarPluginInstance;
  const renderToolbar = () => (
    <Toolbar>
      {(slots: ToolbarSlot) => {
        const {
          CurrentPageInput,
          GoToNextPage,
          GoToPreviousPage,
          NumberOfPages,
          Zoom,
          ZoomIn,
          ZoomOut,
          EnterFullScreen,
          Download,
          Print,
          ShowSearchPopover,
        } = slots;
        return (
          <Flex
            justifyContent="center"
            alignItems="center"
            role="toolbar"
            aria-orientation="horizontal"
          >
            <div style={{ padding: '0px 2px' }}>
              <GoToPreviousPage />
            </div>
            <div style={{ padding: '0px 2px', width: '4rem' }}>
              <CurrentPageInput />
            </div>
            <div style={{ padding: '0px 2px' }}>
              / <NumberOfPages />
            </div>
            <div style={{ padding: '0px 2px' }}>
              <GoToNextPage />
            </div>
            <div style={{ padding: '0px 2px', marginLeft: 'auto' }}>
              <ZoomOut />
            </div>
            <div style={{ padding: '0px 2px' }}>
              <Zoom />
            </div>
            <div style={{ padding: '0px 2px' }}>
              <ZoomIn />
            </div>
            <div style={{ padding: '0px 2px', marginLeft: 'auto' }}>
              <EnterFullScreen />
            </div>
            {/*
           // NOT WORKING FOR SECURED PDF withCredentials
           // @see https://github.com/react-pdf-viewer/react-pdf-viewer/issues/837
           <div style={{ padding: '0px 2px' }}>
              <Download />
            </div>
            */}
            <div style={{ padding: '0px 2px' }}>
              <ShowSearchPopover />
            </div>
            <div style={{ padding: '0px 2px' }}>
              <Print />
            </div>
          </Flex>
        );
      }}
    </Toolbar>
  );

  return (
      <div className="rpv-default-layout__container">
        <div className="rpv-default-layout__toolbar">{renderToolbar()}</div>
        <div
          className="rpv-default-layout__body"
          style={{
            flex: 1,
            overflow: 'hidden',
          }}
        >
          <Viewer
            {...file}
            plugins={[
              toolbarPluginInstance,
            ]}
            defaultScale={SpecialZoomLevel.PageWidth}
          />
        </div>
      </div>
  );
```

**Comment by phuoc-ng** [comment]
This was implemented in the latest code, and will be included in the next version.

To create an empty sidebar, just pass an empty `sidebarTabs`:

```js
const defaultLayoutPluginInstance = defaultLayoutPlugin({
    sidebarTabs: () => [],
});
```

Results:

_Light theme_

![Screen Shot 2021-11-04 at 20 39 33](https://user-images.githubusercontent.com/57786711/140326861-c5708bf2-2ea8-4c35-aaf9-3b8e7f38e424.png)

_Dark theme_

![Screen Shot 2021-11-04 at 20 58 28](https://user-images.githubusercontent.com/57786711/140326985-12f79ebd-c66a-490a-8815-1cb4bd962004.png)

**Comment by phuoc-ng** [comment]
[v2.11.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade and let me know if you need anything else.
