### ISSUE TITLE
Download from Get File plugin not working withCredentials files

### ISSUE THREAD

**Issue by Nightbr** [react-pdf-viewer/react-pdf-viewer#837]
Hey,

I have an issue when I want to use the GetFilePlugin to download my PDF withCredentials files. It always return a 401 Unauthorized because it tries to get the URL with the credentials in the plugin.

Here is an example:
```typescript
  const { getToken } = useAuth();
  const file = {
    fileUrl: `${environment.baseAPI}/media/preview/${props.media.id}`,
    httpHeaders: { Authorization: `Bearer ${getToken().getAccessToken()}` },
    withCredentials: true,
  };

  return (<Viewer {...file} plugins={[defaultLayoutPluginInstance]} />)
```

![image](https://user-images.githubusercontent.com/4228646/140090753-9c338ec8-13ef-4c8a-a4c3-afa099706620.png)

Thanks in advance!

**Comment by phuoc-ng** [comment]
You're right, @Nightbr. The `get-file` plugin currently doesn't use any authorization or additional headers when downloading the file. It only uses the direct file URL.

I will try to fix this in the next version.

**Comment by phuoc-ng** [comment]
@Nightbr 
Updated: The issue was fixed in the latest code. The fix will be included in the next release.

**Comment by phuoc-ng** [comment]
[v2.11.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade and let me know if you need anything else.
