### ISSUE TITLE
Change scrollMode on{Enter|Exit}FullScreen

### ISSUE THREAD

**Issue by Nightbr** [react-pdf-viewer/react-pdf-viewer#838]
Hey,
as the same behavior as you can control the Zoom when Enter/Exit FullScreen, I would like to control the ScrollMode.

I tried something like this but it just update the Viewer but not in the FullScreen view:

```Typescript
  const scrollModePluginInstance = scrollModePlugin({
    scrollMode: ScrollMode.Horizontal,
  });

  // Handle FullScreen
  const fullScreenPluginInstance = fullScreenPlugin({
    enableShortcuts: true,
    onEnterFullScreen: (zoom: Zoom) => {
      zoom(SpecialZoomLevel.PageFit);
      scrollModePluginInstance.SwitchScrollMode({ mode: ScrollMode.Wrapped });
    },
    onExitFullScreen: (zoom: Zoom) => {
      zoom(SpecialZoomLevel.PageWidth);
      scrollModePluginInstance.SwitchScrollMode({
        mode: ScrollMode.Horizontal,
      });
    },
  });
```

Ref: https://github.com/react-pdf-viewer/react-pdf-viewer/issues/406

Maybe there is a workaround with a custom plugin: https://github.com/react-pdf-viewer/examples/tree/main/zoom-after-full-screen

Thanks in advance!

**Comment by phuoc-ng** [comment]
@Nightbr 
Updated: This feature request was implemented in the latest code, and will be available in the next version.

## API

```js
const scrollModePluginInstance = scrollModePlugin();
const { switchTo } = scrollModePluginInstance;

// Switch to the wrapped mode
switchTo(ScrollMode.Wrapped);
```

## Using with the default layout plugin

```js
const defaultLayoutPluginInstance = defaultLayoutPlugin({
    toolbarPlugin: {
        fullScreenPlugin: {
            onEnterFullScreen: (zoom) => {
                zoom(SpecialZoomLevel.PageFit);
                defaultLayoutPluginInstance.toolbarPluginInstance.scrollModePluginInstance.switchScrollMode(
                    ScrollMode.Wrapped
                );
            },
            onExitFullScreen: (zoom) => {
                zoom(SpecialZoomLevel.PageWidth);
                defaultLayoutPluginInstance.toolbarPluginInstance.scrollModePluginInstance.switchScrollMode(
                    ScrollMode.Horizontal
                );
            },
        },
    },
});
```

## Demo

https://user-images.githubusercontent.com/57786711/141156671-c7259e44-5cea-45d8-acc3-90d92b050245.mp4

**Comment by phuoc-ng** [comment]
[v2.11.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade and let me know if you need anything else.

**Comment by Nightbr** [comment]
Hey, it works great `onEnterFullScreen` but broke the layout `onExitFullScreen`:

```
  // ScollMode
  const scrollModePluginInstance = scrollModePlugin({
    scrollMode: ScrollMode.Horizontal,
  });
  const { switchScrollMode } = scrollModePluginInstance;

  // Handle FullScreen
  const fullScreenPluginInstance = fullScreenPlugin({
    enableShortcuts: true,
    onEnterFullScreen: (zoom: Zoom) => {
      zoom(SpecialZoomLevel.PageFit);
      switchScrollMode(ScrollMode.Vertical);
    },
    onExitFullScreen: (zoom: Zoom) => {
      zoom(SpecialZoomLevel.PageWidth);
      switchScrollMode(ScrollMode.Horizontal);
    },
  });
```

https://www.loom.com/share/351c2d4f49264b4cb55b2479c14ee6ea

**Comment by Nightbr** [comment]
@phuoc-ng In My Viewer component, I set the `defaultScale={SpecialZoomLevel.PageWidth}` I don't know if the changes of ScrollMode + Zoom combined is probably the problem? 

Do you achieve to reproduce this behavior or do you need some help on this one?
