### ISSUE TITLE
`selectionRegion`

### ISSUE THREAD

**Issue by justinmoon** [react-pdf-viewer/react-pdf-viewer#863]
What is `selectionRegion` for the `renderHighlightTarget` prop in the highlight plugin? 

I assumed based on the variable name and docs that it would be the smallest bounding rectangle which contains al the `highlightAreas`. But instead [it seems to just be the last one](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/f0fc27f7f843095b0a086b0b747b2cf9685744c7/packages/highlight/src/Tracker.tsx#L200). This doesn't seem very useful, but the smallest bounding rectangle would be. I'm trying to represent a link to a PDF annotation as a Markdown link and including all the rectangles is too verbose.

**Comment by Braweria** [comment]
I believe the selectionRegion is used to detemine where the context menu should appear, which usually is where your mouse stops.

**Comment by justinmoon** [comment]
Ahh that makes sense. Closing this.
