### ISSUE TITLE
Toolbar in fullscreen

### ISSUE THREAD

**Issue by davidaronson13** [react-pdf-viewer/react-pdf-viewer#864]
Is there a way to keep the toolbar when going into FullScreen? I managed to zoom the document, but would be better to have a toobar.

**Comment by phuoc-ng** [comment]
I will support it in the next version.

**Comment by phuoc-ng** [comment]
Updated:
The feature was implemented in the latest code, and will be available in the next release.

_Demo_
In the full screen mode, the _Full screen_ button in the toolbar turns into the exit full screen mode button automatically.

![Screen Shot 2021-11-30 at 21 05 57](https://user-images.githubusercontent.com/57786711/144063864-09ad69fd-377c-4684-98c2-6ce68cfa65b7.png)

**Comment by amansani15** [comment]
I am looking for similar option, may I know when the next release is going to be?
Also, do we need to update the version at our end to get these changes?

Thank you.

**Comment by phuoc-ng** [comment]
@davidaronson13 @amansani15 
The feature was implemented in the [v3.0.0](https://react-pdf-viewer.dev/updates/). Please upgrade!

You can see that new feature in the following example
https://react-pdf-viewer.dev/examples/include-the-default-toolbar-in-the-full-screen-mode/
