### ISSUE TITLE
backend for some features

### ISSUE THREAD

**Issue by Proffett** [react-pdf-viewer/react-pdf-viewer#865]
Hello! Can I connect this product with our backend, I mean we want use some actions on demand (controlled by backend) and receive from backend , and receive byte stream with changes, such as rotate page, split/delete, create new PDF from selected pages

**Comment by phuoc-ng** [comment]
@Proffett 
Thanks for reaching out. The component hasn't provided any such actions (rotate, split, delete a particular page). 
How the interaction or UI does it look like?

**Comment by Proffett** [comment]
Maybe use thumbnail plugin for select pages and send to API, for some actions use Material UI

**Comment by phuoc-ng** [comment]
@Proffett In order to support selecting pages from the thumbnail plugin, I will need to add more APIs such as customizing the thumbnail item renderer.
I will support it in the next version.

**Comment by phuoc-ng** [comment]
@Proffett 
## Updated

The feature was implemented in the latest code, and will be available in the next release.

## API

```jsx
const renderThumbnailItem = (props: RenderThumbnailItemProps) => (
    ...
);

const thumbnailPluginInstance = thumbnailPlugin();
const { Thumbnails } = thumbnailPluginInstance;

<Thumbnails renderThumbnailItem={renderThumbnailItem} />;
```

## Demo

I created an [example](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/thumbnail-render-thumbnail-item/index.tsx) that works as following demo:

https://user-images.githubusercontent.com/57786711/144746210-cb0c1bb0-0b5f-4dcc-90a4-62d067b53c1f.mp4

**Comment by Proffett** [comment]
Thank you for feature, I will check it😉👍

**Comment by phuoc-ng** [comment]
@Proffett 
[v3.0.0](https://react-pdf-viewer.dev/updates/) was released. I also added a live example for your use case 
https://react-pdf-viewer.dev/examples/customize-thumbnail-items/

Let me know if you need anything else.
