### ISSUE TITLE
Add possibility to add "data-" attributes to react-pdf-viewer components

### ISSUE THREAD

**Issue by visuallization** [react-pdf-viewer/react-pdf-viewer#866]
Hey there,

I am currently trying out your tool and it works pretty good so far. Thank you for that! :)
I was wondering if you/we could add the possibility to add "data-" attributes to the react-pdf-viewer components?

use case:
We are writing unit tests with jest and we usually provide our components with a "data-test-id" prop.
So e.g I would like to write something like `<ZoomInButton data-test-id="zoom-in-button" />` to easily test against this component.

Any ideas on that?

Cheers & kind regards

**Comment by phuoc-ng** [comment]
@visuallization What exactly the components you want to add the `data-test-id` attributes?

**Comment by phuoc-ng** [comment]
Any update on this, @visuallization ?

**Comment by visuallization** [comment]
@phuoc-ng ZoomInButton, ZoomOutButton, ZoomPopover are the components I was trying to write tests for. But in general it would be great if every component which can be imported by a user of react-pdf-viewer has the possibility to add a data attribute. Furthermore it would be also great if every component has a className prop so they are more customisable.

**Comment by phuoc-ng** [comment]
_Updated_:
All buttons and menu items in the default toolbar/provided by plugins will have `data-testid` attributes. This request was implemented in the latest code, and will be available in the next release.

**Comment by visuallization** [comment]
> _Updated_: All buttons and menu items in the default toolbar/provided by plugins will have `data-testid` attributes. This request was implemented in the latest code, and will be available in the next release.

@phuoc-ng sweet that is great! :)

**Comment by phuoc-ng** [comment]
@visuallization 
Please upgrade to [v3.0.0](https://react-pdf-viewer.dev/updates/)!
