### ISSUE TITLE
Custom render functions for thumbnail plugin

### ISSUE THREAD

**Issue by robhung** [react-pdf-viewer/react-pdf-viewer#868]
Just wondering if it was possible to allow custom render / loader / error components for thumbnails as well?

We want to be able to replace the default spinners with our own custom components, similar to how `Viewer` allows.

Thanks!

**Comment by phuoc-ng** [comment]
@robhung That's good suggestion. I will support it in the next release.

**Comment by phuoc-ng** [comment]
Updated: The feature was implemented in the latest code.

## API

```js
const thumbnailPluginInstance = thumbnailPlugin({
    renderSpinner: () => <div className="square-spinner" />,
});
```

## Demo 

[Sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/thumbnail-render-spinner/index.tsx)

![Screen Shot 2021-11-19 at 21 51 14](https://user-images.githubusercontent.com/57786711/142645112-16b3e7ba-122e-4610-b59e-14f960070f81.png)

https://user-images.githubusercontent.com/57786711/142645082-56eee086-2e19-4f30-8024-096d2fd24164.mp4

**Comment by robhung** [comment]
Oh, that is nice! Thank you for the quick update.

Actually, we were hoping to replace the initial spinner of the thumbnail list as well, the one with className 'rpv-thumbnail__loader'?

**Comment by phuoc-ng** [comment]
Yes, it is. You can see the first screenshot in the previous comment.

**Comment by robhung** [comment]
Sorry, must have read through the PR too quickly - I see it uses the same spinner for both now. Thanks!

(_FYI: Our end goal is to actually use [skeleton placeholders](https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a) instead of the spinners. Our design team thinks having too many spinners on a page can be unpleasant to watch (eg. too many things changing at once). We plan to replace the first spinner with a skeleton placeholder of a dummy list of pages and titles and then when the PDF loads, we will inject global CSS to hide `rpv--thumbnail__cover-loader`. Just thought it might be useful for you to understand our use case and what our desired effect was._)

**Comment by phuoc-ng** [comment]
@robhung 
Please upgrade to v3.0.0 to use this new feature.

Here is the live example
https://react-pdf-viewer.dev/examples/customize-thumbnail-spinners/
