### ISSUE TITLE
onCanvasLayerRender only runs once

### ISSUE THREAD

**Issue by andywarrens** [react-pdf-viewer/react-pdf-viewer#869]
Hi,

I'm trying to add a Canvas layer over the PDF, so users can draw hand annotations.
After they are done drawing they click a Toggle button, which will:

1. hide my own `Canvas annotation layer`
2. the onCanvasLayerRender will then draw this `Canvas annotation layer `on the RPV Canvas: `e.ele.getContext('2d').drawImage(..)`
3. so automatically the Zoom / Panning will keep working

But of course, this should just be for the current page that's visible. Right now the `onCanvasLayerRender` runs only 
1. once per PDF page, so pages that have already been rendered will not show my hand annotations.
2. it should actually just render again for the page that the user had made his/her annotations on.

Is there a better way to handle this feature?

Thanks for taking your time to read our question. If this feature is not available, will it be on the roadmap? 

Kind regards, 

Andy

**Comment by andywarrens** [comment]
I'm now using the `renderPage` function to draw an extra `canvas` on top. It still needs a lot of tweaking but it automatically scrolls with the page and I can reuse the `zoomLevel` as a `canvas.scale`

**Comment by evliu** [comment]
Do you have an example of how you did this?

**Comment by andywarrens** [comment]
@evliu had to do some serious history digging, I no longer work on that project:
```
export const PdfViewport: React.FC<AnnotatePdfProps> = ({
  fileUrl,
  plugins,
  children,
}) => {
  const renderPage = renderPageAndAnnotations();

  return (
    <>
      <Viewer fileUrl={fileUrl} renderPage={renderPage} plugins={plugins} />
      {children !== undefined && children}
    </>
  );
};

const renderPageAndAnnotations = () =>
  function renderPage(props: RenderPageProps) {
    const { pageIndex, width, height } = props;

    return (
      <>
        {props.canvasLayer.children}
        {props.textLayer.children}
        {props.annotationLayer.children}
        <DrawpadLayer pageIndex={pageIndex} width={width} height={height} />
      </>
    );
  };
```

with DrawPadLayer rendering a `<canvas>` for the annotations:
```

export const DrawpadLayer = ({ pageIndex, width, height }: DrawpadLayerProps) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [canvas, setCanvas] = useState<Canvas | null>(null);

  useEffect(() => {
    const myCanvas = new fabric.Canvas(canvasRef.current);
    setCanvas(myCanvas);

    return () => {
      myCanvas.dispose();
    };
  }, [canvasRef]);

  useEffect(() => {
    resizeCanvas(canvas, width, height);
  }, [canvas, width, height]);

  useEffect(() => {
    if (canvas !== null) {
      canvas.on("mouse:down:before", () => {
          configureDrawingMode(canvas);
      });
    }
  }, [canvas, annotatorSettings]);

  return <canvas ref={canvasRef} id={"annotationDrawingPad-" + pageIndex} />;
};
```

I left out some code for brevity: but basically inside `configureDrawingMode` is where I use `fabric.js` to draw annotations on the canvas element
