### ISSUE TITLE
I cannot print a PDF with many pages

### ISSUE THREAD

**Issue by jonasmarco** [react-pdf-viewer/react-pdf-viewer#875]
Hello everybody,
I have a project with a PDF with many pages.
I can download and see all the pages.
However, when I want to print, it only shows one page.
See the photos below and my code.

Network when I click to print
![network](https://user-images.githubusercontent.com/19959770/142619784-048e2345-3480-41e2-bf86-071513d7d9f1.jpg)

Print preview (This shows 1 page only, but there are 6 in total)
![print-preview](https://user-images.githubusercontent.com/19959770/142619827-bd03550b-9449-414f-9f53-92014baaeba5.jpg)

package.json
"react": "^17.0.2",
"react-dom": "^17.0.2",
![image](https://user-images.githubusercontent.com/19959770/142622172-f835493c-8565-465c-ae94-e0855a4ec764.png)

code: https://pastebin.com/yxehuzDv

**Comment by phuoc-ng** [comment]
@jonasmarco Instead of posting the sample code on PasteBin, can you fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) which is able to reproduce the issue?

**Comment by jonasmarco** [comment]
@phuoc-ng 

here, these work very well for printing : ( could it be some css that is slamming this ?
https://codesandbox.io/s/react-pdf-viewer-sample-forked-xc84u?file=/src/App.tsx

**Comment by jonasmarco** [comment]
Dude I solved the problem,
my body had an overflow:hidden property
removed and now the printing is working

` body {
    min-height: 100vh;
    overflow: auto;
}`

to

` body {
    min-height: 100vh;
}`

**Comment by phuoc-ng** [comment]
Awesome, @jonasmarco 👍
