### ISSUE TITLE
Pdf search results in unpredicted behaviour

### ISSUE THREAD

**Issue by visuallization** [react-pdf-viewer/react-pdf-viewer#882]
Hey there,

We are experiencing an issue with the viewers pdf search.
In fact it can be even reproduced in the viewer on https://react-pdf-viewer.dev/.

If you search for a word it will get marked as expected and by clicking "next match" you jump from page to page.
However if this word occurs multiple times on one page and you click on "next match" the words are highlighted from bottom to top instead of the expected behaviour top to bottom.

Are you able to fix this or is there a setting for the expected behaviour?

You can see in the screenshot that the last occurrence of the word "PDF" is highlighted on the page even though I would expect the first occurrence to be highlighted on the page.

<img width="818" alt="Screenshot at Nov 22 14-16-06" src="https://user-images.githubusercontent.com/6199277/142868211-f69798f8-c6be-4d84-ab64-ebc4b83cd5fe.png">

**Comment by phuoc-ng** [comment]
_Updated_

The issue was fixed in the latest code, and will be included in the next release.

_Demo_

https://user-images.githubusercontent.com/57786711/143470302-83f56958-b53c-46d0-a40c-9f12742862db.mp4

**Comment by visuallization** [comment]
@phuoc-ng 

⚡ lightning fast!
Thank you very much

**Comment by phuoc-ng** [comment]
@visuallization @helianthuswhite @denisLoncaric @flipace
[v3.0.0](https://react-pdf-viewer.dev/updates/) was released. Please upgrade.
