### ISSUE TITLE
Thumbnail Plugin: Cover component wrong position

### ISSUE THREAD

**Issue by robhung** [react-pdf-viewer/react-pdf-viewer#883]
`Cover` component has the `canvas` out of position using Chrome / MacBook Pro 16".

I believe it has something to do with the logic with pixel density and supporting retina displays.

I was able to manually fix it by removing `transform-origin: left top;` via inspector.

| Before | After |
| --- | --- |
| <img width="415" src="https://user-images.githubusercontent.com/11624465/142961676-6fe9f293-b471-41eb-b713-649ef95aaa26.png" /> | <img width="415" src="https://user-images.githubusercontent.com/11624465/142961686-62cc3b08-1a6f-48be-8e71-345b0dce53bd.png" /> |

**Comment by phuoc-ng** [comment]
Updated:
The issue was fixed in the latest code.

**Comment by phuoc-ng** [comment]
@robhung The issue was fixed in [v3.0.0](https://react-pdf-viewer.dev/updates/). Please upgrade!
