### ISSUE TITLE
Download button cannot be customize from toolbarSlot

### ISSUE THREAD

**Issue by Nightbr** [react-pdf-viewer/react-pdf-viewer#886]
Hey,

I found in the documentation you can customize the download button from get-file: https://react-pdf-viewer.dev/examples/customize-the-download-button/

I tried to override the Download button but it doesn't work (I still have the old download button style), this method works for all other toolbar buttons:

```typescript
{(slots: ToolbarSlot) => {
        const {
          CurrentPageLabel,
          GoToNextPage,
          GoToPreviousPage,
          NumberOfPages,
          Zoom,
          ZoomIn,
          ZoomOut,
          EnterFullScreen,
          Download,
          Print,
          ShowSearchPopover,
        } = slots;
        return (
          <Flex
            justifyContent="center"
            alignItems="center"
            role="toolbar"
            aria-orientation="horizontal"
          >
            ...
            {/* Other controls */}
            <EnterFullScreen>
              {(props) => (
                <IconButton
                  ml="auto"
                  icon={<Icon as={Maximize2} h="5" w="5" />}
                  aria-label="Fullscreen"
                  variant="link"
                  color="black"
                  onClick={props.onClick}
                />
              )}
            </EnterFullScreen>

            <Download>
              {(props: RenderDownloadProps) => (
                <IconButton
                  mt="1"
                  icon={<Icon as={Download} h="5" w="5" />}
                  aria-label="Download"
                  variant="link"
                  color="black"
                  onClick={props.onClick}
                />
              )}
            </Download>

           ...
          </Flex>
        );
      }}
```

<img width="696" alt="image" src="https://user-images.githubusercontent.com/4228646/143042707-6135776f-1131-4c42-9781-77e0272705df.png">

Thanks for your help!

**Comment by phuoc-ng** [comment]
@Nightbr 
I can't reproduce the issue with this [sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/toolbar-get-file-slot/index.tsx).

Here is how the sample code above works

https://user-images.githubusercontent.com/57786711/143670023-f0200d9c-3253-4270-8bb2-4142259a8589.mp4

Can you try the sample example above to see if it works or not?
