### ISSUE TITLE
failed to fetch, cors error

### ISSUE THREAD

**Issue by prasagungg** [react-pdf-viewer/react-pdf-viewer#887]
i have error 

Access to fetch at 'https://ina-access-bucket.s3.ap-southeast-1.amazonaws.com/others/1631094825030_1630566271882_FILE.pdf' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

this my code

`<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
        <Viewer
          fileUrl="https://ina-access-bucket.s3.ap-southeast-1.amazonaws.com/others/1631094825030_1630566271882_FILE.pdf"
          plugins={defaultLayoutPlugin}
        />
  </Worker>
`

what should i do to solve this problem ?

**Comment by phuoc-ng** [comment]
@prasagungg Please take a look at 
https://docs.sevenbridges.com/docs/enabling-cross-origin-resource-sharing-cors#how-to-enable-cors-on-your-amazon-s3-buckets
https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header
