### ISSUE TITLE
Thumbnail Plugin: Image for Cover

### ISSUE THREAD

**Issue by robhung** [react-pdf-viewer/react-pdf-viewer#892]
Hello!

Another feature request - we are trying to use the `Cover` component in the thumbnail plugin inside a dynamic parent container.

Because `canvas` is used instead of `image`, every time the parent container dynamically resizes, we've had to manually re-render the component (using [react-resize-detector](https://github.com/maslianok/react-resize-detector)) so the size displays correctly.

It's not a pretty fix because it creates a bunch of console errors for `ResizeObserver`, and also causes the loading spinner to appear, which can be very distracting to the user.

We've hidden the spinner using CSS, so it's now just a flash, but it would be great if we could just use an image and resize it.

I've noticed the `Thumbnails` component converts the `canvas` to `image` using `toDataUrl()`, could we do this for `Cover` as well?

Thanks!

**Comment by phuoc-ng** [comment]
@robhung 
Thanks a lot for the request. More requests you give us, more chances the library gets better ❤️ 
It was implemented in the latest code, and will be available in the next release.

![Screen Shot 2021-11-27 at 11 36 48](https://user-images.githubusercontent.com/57786711/143668138-35c9994c-dd16-4b06-9e49-d55871c4ce00.png)

**Comment by robhung** [comment]
Amazing, thank you so much. We appreciate the quick turnaround! Looking forward to the next release.

**Comment by phuoc-ng** [comment]
@robhung [v3.0.0](https://react-pdf-viewer.dev/updates/) was released. Please upgrade!

**Comment by robhung** [comment]
@phuoc-ng Thanks for the update! I've just tried to upgrade it locally and am running into an issue where if I have multiple different PDF Cover's on the same page, the first one to finish loading becomes the cover image for all PDF's.

We're using the exact same code from [this example](https://react-pdf-viewer.dev/examples/display-the-thumbnail-of-a-given-page/).

Thought I might quickly report it first in case it's easily reproducible, otherwise let me know if you need me to sandbox it!

**Comment by robhung** [comment]
I'm reading the source code and can see that `CoverInner` generates the `src` based on what `doc` is loaded from the `store`.

When a document is loaded, it runs `onDocumentLoad` to update the `store`. 

The behaviour I'm seeing is that all images get the same `src`, even if the `fileUrl` passed into each `Viewer` is different?

**Comment by phuoc-ng** [comment]
@robhung Can you open a new issue for me? (You can copy-paste the previous comments).
