### ISSUE TITLE
Override fileNameGenerator for getFilePlugin not used if Download in Toolbar

### ISSUE THREAD

**Issue by Nightbr** [react-pdf-viewer/react-pdf-viewer#897]
Hey, 

I think I have found a tricky behavior.

If you want to override fileNameGenerator in getFilePlugin:

```TypeScript
  // Download plugin
  const getFilePluginInstance = getFilePlugin({
    fileNameGenerator: (file: OpenFile) => {
      console.log(file, props.media.name);
      return props.media.name ? props.media.name : 'document.pdf';
    },
  });
```

And use the Download button in the Toolbar:

```TypeScript
<Toolbar>
      {(slots: ToolbarSlot) => {
        const {
         Download
        } = slots;
  <Download>
    {(props: RenderDownloadProps) => (
      <IconButton
        mt="1"
        icon={<Icon as={IconDownload} h="5" w="5" />}
        aria-label="Download"
        variant="link"
        color="black"
        onClick={props.onClick}
      />
    )}
  </Download>
</Toolbar>
```

We don't pass in my fileNameGenerator function.

I have create a codesandbox where you can reproduce the issue (note: need to open in a new window the browser part to be able to see the download button working.

https://codesandbox.io/s/compassionate-murdock-631uf?file=/src/components/DocumentContainer/DocumentContainer.tsx

Thanks in advance!

**Comment by phuoc-ng** [comment]
@Nightbr @rbideau
It is actually not a bug. By default, the toolbar plugin also registers the `get-file` (and some other plugins) automatically to build up the toolbar.

So, instead of creating two plugins as

```tsx
const toolbarPluginInstance = toolbarPlugin();

// Download plugin
const getFilePluginInstance = getFilePlugin({
  fileNameGenerator: (file: OpenFile) => {
    console.log(file);
    return "customName.pdf";
  }
});
```

We just pass the `fileNameGenerator` option:

```tsx
const toolbarPluginInstance = toolbarPlugin({
  getFilePlugin: {
    fileNameGenerator: (file: OpenFile) => {
      console.log(file);
      return "customName.pdf";
    }
  }
});
```

Here is the [working project](https://codesandbox.io/s/react-pdf-viewer-issue-897-orb5tf).
