### ISSUE TITLE
Highlight disappears on text when zoom value is changed in toolbar

### ISSUE THREAD

**Issue by amansani15** [react-pdf-viewer/react-pdf-viewer#900]
Hello, 

In the initial load of pdf, I can see the highlight text. But if I change the zoom level, then the highlight is disappeared. This problem exists in the toolbar zoom options. The same thing is working fine with the zoomplugininstance. 

Is there anything I need to enable or do to make this work with the toolbar zoom? 

Any inputs are highly appreciated. Thanks for the nice library.

**Comment by phuoc-ng** [comment]
@amansani15 Can you create a sample project based on [this one](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut)?
It is useful for me to see the issue.

**Comment by amansani15** [comment]
Hello @phuoc-ng, I have updated the code in the sample project. 
**Here is the link**: [https://codesandbox.io/s/react-pdf-viewer-sample-forked-t9twn?file=/src/pdfviewer.tsx](url)

In this my search text is "parameters". Initially it highlights the parameter text, once we change the zoom level it is not highlighting.

**Comment by amansani15** [comment]
Hello @phuoc-ng , any update on this?

**Comment by phuoc-ng** [comment]
@amansani15 It's not a bug. Basically the toolbar plugin also uses the search plugin, so you don't have to declare a new instance of the search plugin.

Replace the old code

```js
const searchPluginInstance = searchPlugin({
  keyword: [textSearch]
});
const toolbarPluginInstance = toolbarPlugin();
```

with new one

```js
const toolbarPluginInstance = toolbarPlugin({
    searchPlugin: {
      keyword: [textSearch]
    }
  });
```

Here is the working demo: https://codesandbox.io/s/react-pdf-viewer-sample-forked-t9twn?file=/src/pdfviewer.tsx
