### ISSUE TITLE
canvas `transform-origin` rule incorrectly set at smaller viewport sizes and zoom levels

### ISSUE THREAD

**Issue by scottwhudson** [react-pdf-viewer/react-pdf-viewer#901]
The canvas element incorrectly has the `transform-origin` CSS rule set to `left top` when zoomed out, which causes white space to appear on the left side of the render window:

ex 1: behaves as expected at a standard zoom level (~100%)
<img width="636" alt="Screen Shot 2021-12-01 at 5 06 11 PM" src="https://user-images.githubusercontent.com/6406203/144322030-5a87c1f6-c3e0-466c-8d75-4caabe0e3661.png">

ex 2: pushes the canvas to the right, creating white space on the left when zoomed out 
<img width="206" alt="Screen Shot 2021-12-01 at 5 06 19 PM" src="https://user-images.githubusercontent.com/6406203/144322032-aa3aa4c3-923d-425a-9085-f9c0144da733.png">

[This](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/70db41e883cb97aabdbfd48cb78cd3369c57883b/packages/core/src/layers/CanvasLayer.tsx#L113) appears to be the offending line, but I have not been successful in correcting this behavior across all zoom levels. Fixing the error case on low zoom levels breaks the larger views and vice-versa.

**Comment by phuoc-ng** [comment]
Can you give me the same document, @scottwhudson?

**Comment by phuoc-ng** [comment]
@scottwhudson 
This should be fixed in [v3.1.0](https://react-pdf-viewer.dev/updates/). Please upgrade.
There is no `transform-origin` property used for the canvases.
