### ISSUE TITLE
Hide toolbar plugin options

### ISSUE THREAD

**Issue by amansani15** [react-pdf-viewer/react-pdf-viewer#903]
Hello, I don't want all the available options in the toolbar plugin. how to hide few options in the toolbar plugin?

For example, if I don't want full screen mode option and need rest of the other options in the toolbar. How to hide just full screen mode and leave the rest in the toolbar.

Also, does the react-pdf-viewer supports all the platforms like windows, mac, ios, android etc?

Thank you.

**Comment by phuoc-ng** [comment]
@amansani15 Please take a look at these examples

https://react-pdf-viewer.dev/examples/toolbar-slot/
https://react-pdf-viewer.dev/examples/customize-the-default-toolbar/

**Comment by amansani15** [comment]
Okay, will look into it. Thank you

**Comment by ZinkNotTheMetal** [comment]
I have the same issue, is there an easy example on just hiding one button (theme switch) from the toolbar?

I see that I can customize the entire toolbar but that seems like overkill for hiding a single button.

**Comment by phuoc-ng** [comment]
@ZinkNotTheMetal You probably don't have to use the `toolbarPlugin` when you have the `defaultLayoutPlugin`.
Here is an example of hiding toolbar items
https://codesandbox.io/s/react-pdf-viewer-sample-forked-0fsod?file=/src/App.tsx

**Comment by ZinkNotTheMetal** [comment]
@phuoc-ng Thanks for the response, but on your example you are getting an error on where you are defining it. As I am using typescript and airbnb linting. This is not compiling for me. Do you have another example without an error?

**Comment by phuoc-ng** [comment]
@ZinkNotTheMetal 
You can disable the warning. I updated the [sample project](https://codesandbox.io/s/react-pdf-viewer-sample-forked-0fsod?file=/src/App.tsx).

**Comment by phuoc-ng** [comment]
Can you create a live project based on https://codesandbox.io/s/react-pdf-viewer-sample-forked-0fsod, so I can take a look?

**Comment by phuoc-ng** [comment]
I added a new live example [here](https://react-pdf-viewer.dev/examples/remove-some-parts-from-the-default-toolbar/), so it might be useful for other one.
