### ISSUE TITLE
Error: Page dictionary kid reference points to wrong type of object.

### ISSUE THREAD

**Issue by Kliton** [react-pdf-viewer/react-pdf-viewer#915]
Hi, i can see the pdf with chrome or Preview ( mac os ).
But when i render with react-pdf-viewer i got this error:

![image](https://user-images.githubusercontent.com/10452377/145426801-84a476e5-f892-4392-8817-38e6917649db.png)

Worker url: https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js

packge.json
```
    "@react-pdf-viewer/core": "2.11.0",
    "@react-pdf-viewer/core": "2.11.0",
    "@react-pdf-viewer/default-layout": "^2.11.0",
    "@react-pdf-viewer/locales": "^1.0.0",
    "@react-pdf/renderer": "^2.0.21",
    "pdfjs-dist": "2.6.347"
``` 

Why this happens?

**Comment by phuoc-ng** [comment]
Can you give me the sample document?

**Comment by Kliton** [comment]
Is a private document. I can see that doc with google chrome, mac preview etc but is not working with the lib

**Comment by phuoc-ng** [comment]
@Kliton Does the issue happen with the [pdfjs's viewer](https://mozilla.github.io/pdf.js/web/viewer.html)?

**Comment by Kliton** [comment]
@phuoc-ng Idk, how i can test it?

**Comment by phuoc-ng** [comment]
@Kliton You can click the _Open_ button from the toolbar.

![Screen Shot 2021-12-21 at 22 10 59](https://user-images.githubusercontent.com/57786711/146952989-c78af6a1-fdb1-41b9-8064-8fae1e6f9320.png)

**Comment by Kliton** [comment]
@phuoc-ng  Ok i've tried: the issue is not happening with the pdfjs viewer

**Comment by phuoc-ng** [comment]
The exception comes from `src/shared/utils.js` which is a file in the pdf-js library. Can you upgrade your pdfjs-dist from `2.6.347` to the latest version? (`2.11.338`)
