### ISSUE TITLE
Copy paste without space in between words

### ISSUE THREAD

**Issue by nouredine** [react-pdf-viewer/react-pdf-viewer#923]
Hi @phuoc-ng ,

First of all, Thank You for your great work!
I have encountering an issue when i Copy Paste text from pdf area
this is how, i select text and hit CTRL+C and CTRL+V
![image](https://user-images.githubusercontent.com/6216737/145829774-362ef896-8866-4105-8489-501a1403f23f.png)
this is the result

![image](https://user-images.githubusercontent.com/6216737/145829996-e81c0cff-5752-4775-83f4-f84d1c7dfdd0.png)
that occur when we have every word in a span html tag
![image](https://user-images.githubusercontent.com/6216737/145830237-89574c54-efa8-47a1-ba8e-6e4ba3469561.png)

I have added **Selection Mode plugin** and I still get the same issue
![image](https://user-images.githubusercontent.com/6216737/145830432-1bbffe7f-18d0-4bd6-b844-2d90a6b6cc3f.png)

i appreciate any advice or solution

**Comment by nouredine** [comment]
my goal is to add an html tag as a child to the generated spans like so
![image](https://user-images.githubusercontent.com/6216737/145968847-74957049-eb68-4ac9-be18-e1423978c935.png)
that solution will work only for first three pages
`document.querySelectorAll('.rpv-core__text-layer-text').forEach(textEle => {
				const em = document.createElement('em');
				em.innerHTML = ' ';
				console.log('textEle', textEle);
				textEle.appendChild(em);
			});`

**Comment by nouredine** [comment]
Hi @phuoc-ng 

I have readapted **findLinksPlugin** to customize spans, and that have resolved my issue
thanks

**Comment by timnlupo** [comment]
I am having this same issue, this seems like a workaround. Is there a better solution?
