### ISSUE TITLE
Navigation Plugin: CurrentPageLabel becomes null when changing state on Parent

### ISSUE THREAD

**Issue by andywarrens** [react-pdf-viewer/react-pdf-viewer#925]
Hi,

I've created a simple [code sandbox](https://codesandbox.io/s/react-pdf-viewer-with-custom-toolbar-ohl3r?file=/src/MyViewer.tsx) to show what I mean.

To reproduce:
1. Go to sandbox
2. Use Zoom buttons and/or page navigation buttons: they work as expected
3. Click 1 of 2 buttons to change state

Expected:
- The state changes, and nothing else

Actual:
- The state changes, but the CurrentPage and TotalPage labels disappear in the toolbar

Is this a bug? What is wrong?

I wish there was a different way of working with the plugins. Maybe directly subscribing to the internal store, and use e.g. a redux-pattern.

**Comment by phuoc-ng** [comment]
(Similar to #904)

@andywarrens 
The issue was fixed in the [v3.0.0](https://react-pdf-viewer.dev/updates/). Please upgrade.
Here is the [working demo](https://codesandbox.io/s/react-pdf-viewer-with-custom-toolbar-forked-p49ft).
