### ISSUE TITLE
How to add exit full screen mode to the toolbar plugin and show the toolbar plugin in the full screen mode

### ISSUE THREAD

**Issue by amansani15** [react-pdf-viewer/react-pdf-viewer#945]
My issue is same as [https://github.com/react-pdf-viewer/react-pdf-viewer/issues/864](url). I want to show the toolbar in the full screen mode and exit the full screen mode with a button. I have upgraded to v3.0.0 but I still don't see the toolbar in the full screen mode. 

I followed the sample code in the below link, but I want to add it to the toolbar plugin, not to the default layout.
[https://react-pdf-viewer.dev/examples/include-the-default-toolbar-in-the-full-screen-mode/](url)

`const toolbarPluginInstance = toolbarPlugin({
        searchPlugin: {
          keyword: [textSearch]
        },
        fullScreenPlugin: {
            getFullScreenTarget: (pagesContainer) => pagesContainer.closest('[data-testid="default-layout__body"]'),
            renderExitFullScreenButton: (props) => <></>,
        },
      });
    `

**I am getting the below error at getFullScreenTarget:**

Type '(pagesContainer: HTMLElement) => HTMLElement | null' is not assignable to type '(pagesContainer: HTMLElement) => HTMLElement'.
  Type 'HTMLElement | null' is not assignable to type 'HTMLElement'.
    Type 'null' is not assignable to type 'HTMLElement'.  TS2322

    51 |         },
    52 |         fullScreenPlugin: {
  > 53 |             getFullScreenTarget: (pagesContainer) => pagesContainer.closest('[data-testid="default-layout__body"]'),
       |             ^
    54 |             renderExitFullScreenButton: (props) => <></>,
    55 |         },
    56 |       });

Any inputs or solutions are highly appreciated. Thank you

**Comment by phuoc-ng** [comment]
@amansani15 Can you fork this [sample](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) project and update your code there?

**Comment by phuoc-ng** [comment]
@amansani15 
Here is the working [project](https://codesandbox.io/s/react-pdf-viewer-sample-forked-4ph1h?file=/src/App.tsx), Live demo: https://4ph1h.csb.app/

Important notes:

1. You have to use the latest versions. See the [package.json](https://codesandbox.io/s/react-pdf-viewer-sample-forked-4ph1h?file=/package.json):

```
"@react-pdf-viewer/core": "3.0.0",
"@react-pdf-viewer/toolbar": "3.0.0",
```

2. Indicate the element that will be used in the full screen mode:

```tsx
<div className="... js-viewer-container">
  <Toolbar />
  <Viewer />
</div>
```

3. Query the element in the `getFullScreenTarget` option:

```tsx
const toolbarPluginInstance = toolbarPlugin({
  searchPlugin: {
    keyword: ["Parameters"]
  },
  fullScreenPlugin: {
    getFullScreenTarget: (pagesContainer) =>
      pagesContainer.closest(".js-viewer-container"),
    renderExitFullScreenButton: (props) => <></>
  }
});
```

**Comment by phuoc-ng** [comment]
I also added this example to the [official guide](https://react-pdf-viewer.dev/examples/include-the-default-toolbar-in-the-full-screen-mode/).
Take a look at the last demo in the page above.

**Comment by amansani15** [comment]
Hello, 

I am getting error at getFullScreenTarget. Below are the details of the error:

(method) FullScreenPluginProps.getFullScreenTarget?(pagesContainer: HTMLElement): HTMLElement
Type '(pagesContainer: HTMLElement) => HTMLElement | null' is not assignable to type '(pagesContainer: HTMLElement) => HTMLElement'.
  Type 'HTMLElement | null' is not assignable to type 'HTMLElement'.
    Type 'null' is not assignable to type 'HTMLElement'.ts(2322)
No quick fixes available



I made sure the versions I am using are 3.0.0 in my system. May I know how to fix this error?

**Comment by amansani15** [comment]
It worked on code sandbox after adding right version dependencies.
[https://codesandbox.io/s/react-pdf-viewer-sample-forked-d1zgr?file=/src/App.tsx](url)

However, the issue got fixed in my project after setting strict to false in tsconfig.json file.
[https://stackoverflow.com/questions/48488701/type-null-is-not-assignable-to-type-htmlinputelement-reactjs](url)

I can see the exit full screen button when I run the app in the browser. I still see the same full screen button(instead of exit full screen button) when I run the application in desktop version. It's a Microsoft Teams app. I cannot able to take sample picture in the full screen mode or create a sample project. Please let me know if you have any suggestions on this. TIA

**Comment by phuoc-ng** [comment]
Close this issue as it's not possible for me to see the sample code that can reproduce the issue.
