### ISSUE TITLE
Failed to compile. on yarn start

### ISSUE THREAD

**Issue by ayseboogie** [react-pdf-viewer/react-pdf-viewer#956]
Using react-pdf-viewer with:
"@react-pdf-viewer/core": "^3.0.0",
"@react-pdf-viewer/default-layout": "^3.0.0",
"pdfjs-dist": "2.11.338",
Node: v17.0.1
npm: 8.3.0

I used the example from https://github.com/react-pdf-viewer/starter/blob/main/webpack-typescript/src/App.tsx in my Typescript project. I changed line 12 `pdfjs-dist@2.9.359` to `pdfjs-dist@2.11.338`. If I run yarn build, it works as expected; however, when I run `yarn start`, I get the error: 
./node_modules/pdfjs-dist/build/pdf.js 2356:44
Module parse failed: Unexpected token (2356:44)
File was processed with these loaders:
  ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
  getJSActions() {
             return this._jsActionsPromise ||= this._transport.getPageJSActions(this._pageIndex);
           }

**Comment by phuoc-ng** [comment]
@ayseboogie Try to downgrade NodeJS to a stable version (v16.13.1, for example).

**Comment by ayseboogie** [comment]
I am still getting the same error after downgrading Node to v16.13.1

**Comment by ayseboogie** [comment]
I downgraded pdfjs to `"pdfjs-dist": "^2.6.347",` and it is now working

**Comment by phuoc-ng** [comment]
@ayseboogie If you use Create React App v4, then you can use the latest version of pdf.js with additional settings.
See this starter https://github.com/react-pdf-viewer/starter/tree/main/create-react-app
