### ISSUE TITLE
The library does not work in Safari (react-pdf-viewer.dev breaks on load)

### ISSUE THREAD

**Issue by irudyi-carecloud** [react-pdf-viewer/react-pdf-viewer#957]
When open` react-pdf-viewer.dev` in Safari it crushes with the error `Application error: a client-side exception has occurred (see the browser console for more information).`
The same issue happens when use own instance of React PDF Viewer, it crushes with the error `ReferenceError: Can't find variable: IntersectionObserver`

**Comment by phuoc-ng** [comment]
What's the version of Safari?
[IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) is supported from [Safari v12.1]. So if you're using the older versions, maybe you need to insert a polyfill.

```html
<html>
    <head>
        <!-- Polyfills for IntersectionObserver -->
        <script src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver"></script>
    </head>
    <body>
        ...
    </body>
</html>
```

**Comment by irudyi-carecloud** [comment]
@phuoc-ng thank you for the recommendation of polyfill. Regarding the version, the above error happens in the latest version `Version 15.1 (17612.2.9.1.20)`

![image](https://user-images.githubusercontent.com/33758106/149738075-09daf54f-80da-48bf-85b8-706df31e8eb5.png)

**Comment by phuoc-ng** [comment]
There is no issue from my side

![Screen Shot 2022-01-17 at 15 57 13](https://user-images.githubusercontent.com/57786711/149738653-4b1f33ac-33d2-428f-93da-c72299c83927.png)
