### ISSUE TITLE
When rotate all pages it is not reflected in thumbnails

### ISSUE THREAD

**Issue by irudyi-carecloud** [react-pdf-viewer/react-pdf-viewer#958]
The pages are displayed vertically in thumbnails when the pages are rotated horizontally in the right side view
![image](https://user-images.githubusercontent.com/33758106/149117499-1ff07d70-e503-4066-bbab-ca7c50eda042.png)

**Comment by phuoc-ng** [comment]
Thanks for reporting the issue. It will be fixed in v3.2.0

**Comment by phuoc-ng** [comment]
Update: The bug was fixed in the latest code, and will be included in the next version (v3.2.0).

**Comment by irudyi-carecloud** [comment]
@phuoc-ng thank you a lot, appreciate it!
