### ISSUE TITLE
Question: Dual page viewmode

### ISSUE THREAD

**Issue by PaoloKa** [react-pdf-viewer/react-pdf-viewer#984]
Hi, we've been using your library for creating an online e-learning platform. Now we have the requirement to add a dual page viewmode, and we are wondering if this is something on your roadmap for the future and if so is there a ETA? 
Currently we accomplished this with the horizontal viewmode and only rendering the active page, but it seems not the correct way and included a lot CSS which can break with every upcoming update...

Also currently we are not able to navigate multiple page at once, since we want to see the next 2 pages. Is it possible to expose the useCurrentPage hook or add the currentPage &  numberOfPages to the previous & next page render props? so we can do something like this
` 
<GoToPreviousPage>
        {({  currentPage }) => (
          <IconButton
            onClick={() => {
              jumpToPage(currentPage + 2);
            }}
          >
            <KeyboardArrowUpIcon />
          </IconButton>
        )}
      </GoToPreviousPage>
`

example of the dual page:
![image](https://user-images.githubusercontent.com/30302837/150809524-a41f1354-85bf-4a71-af86-63332a688115.png)

**Comment by phuoc-ng** [comment]
Yes, it's on the roadmap. I already had a similar request in https://github.com/react-pdf-viewer/react-pdf-viewer/issues/291#issuecomment-706706691

**Comment by phuocng** [comment]
@PaoloKa This is now supported in [v3.10.0](https://react-pdf-viewer.dev/updates/).
