### ISSUE TITLE
pdfjs-dist-signature outdated

### ISSUE THREAD

**Issue by Hatzl** [react-pdf-viewer/react-pdf-viewer#985]
Hi, your PDF viewer is awesome! But I have some strange behavior with displaying signature with your pdf viewer.

Can you provide the actual version (2.12.313) with signature support? (  @react-pdf-viewer/pdfjs-dist-signature )

Maybe updating fixes my problems.

**Comment by phuoc-ng** [comment]
pdf-js 2.12.313 supports the signature, so you don't need to use the `@react-pdf-viewer/pdfjs-dist-signature` package anymore.

**Comment by Hatzl** [comment]
Thank you for your help.
