### ISSUE TITLE
v3.1.0: document content is hidden

### ISSUE THREAD

**Issue by MPuida** [react-pdf-viewer/react-pdf-viewer#988]
Hello,

The issue occurred after `react-pdf-viewer` version update from `3.0.0` to `3.1.0`. Document content is hidden on initial load however, the viewer displays the content as expected after actions such as mouse hover on one of the toolbar elements or navigation with a keyboard. For reference, I'm providing your own sample with updated `react-pdf-viewer` versions to `3.1.0`.

https://codesandbox.io/s/react-pdf-viewer-sample-forked-xhvqm

**Comment by Dmo16** [comment]
We are also experiencing same after upgrading to 3.1.0

Bug behaves exactly as described above, and as is demonstrated in the codesandbox link.

**Comment by marinater** [comment]
Happening on multi-page PDFs as well. Happens on chrome but not firefox.

**Comment by phuoc-ng** [comment]
@MPuida I can't reproduce the issue with the [link](https://codesandbox.io/s/react-pdf-viewer-sample-forked-xhvqm) you gave me.
I always see the content displayed properly there.

Do I miss something? My Chrome is `Version 98.0.4758.80 (Official Build) (x86_64)`

**Comment by flowsni** [comment]
I have the same problem, content appears when I start to scroll the page or hover over any action button(Toolbar).

**Comment by MPuida** [comment]
> @MPuida I can't reproduce the issue with the [link](https://codesandbox.io/s/react-pdf-viewer-sample-forked-xhvqm) you gave me. I always see the content displayed properly there.
> 
> Do I miss something? My Chrome is `Version 98.0.4758.80 (Official Build) (x86_64)`

My chrome version is `Version 98.0.4758.82 (Official Build) (64-bit)` so it is pretty much the same. As for reproduction, I reload the inbuilt browser and the content of the pdf is not appearing.

**Comment by Dmo16** [comment]
@phuoc-ng I just double checked to see if an update somewhere fixed the issue, but it's still present for me, with the same codesandbox link.

Chrome: Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by 321ckatz123** [comment]
@phuoc-ng this is strictly a guess as I don't exactly know how you are doing the virtualization, but you are on a 32-bit version of Chrome and everyone who has the issue so far who has reported browser is on a 64-bit version of Chrome.

Could it be related to that?

**Comment by phuoc-ng** [comment]
@321ckatz123 Thanks for the suggestion. However, I can't see the issue when trying on the following browsers

![Screen Shot 2022-02-22 at 14 20 47](https://user-images.githubusercontent.com/57786711/155461041-65c8b1b1-994b-4ffc-9a60-b6344b6a2b1f.png)

![Screen Shot 2022-02-22 at 15 32 43](https://user-images.githubusercontent.com/57786711/155461057-ff936236-e558-43a8-b814-cfe17d575fb4.png)

(both run on Windows 11)

I still don't know the way/environment to reproduce the issue :(

**Comment by ZinkNotTheMetal** [comment]
Seems related to my issuse, should have done more research before I created a bug
#1010

**Comment by phuoc-ng** [comment]
@MPuida @Dmo16 @lexie-gainessmith @marinater @321ckatz123 @ZinkNotTheMetal 
[v3.1.1](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.

**Comment by Dmo16** [comment]
@phuoc-ng after upgrading in our main application, the issue is a little better, but still present.

I've been able to reproduce this bug with a minimal CRA app located here:

[https://github.com/Dmo16/react-pdf-viewer-988](url)

It contains 2 static files that you can toggle between.

This bug seems to be more prominent in image heavy PDF files.

Here's a video of the above app demonstrating the bug: 

[https://www.loom.com/share/a82604ff4d9d4749b4b87fb03e06bd14](url)

**Comment by 321ckatz123** [comment]
@phuoc-ng can this please be reopened? We are seeing the same thing as @Dmo16 is seeing.
