### ISSUE TITLE
Academic License

### ISSUE THREAD

**Issue by floschne** [react-pdf-viewer/react-pdf-viewer#989]
Hi,

I didn't find another way to contact you, so I'm writing here.

I really like this project and we would like to use it for an academic tool my research group is building. Is there anyway to get this with a license for academic use?

**Comment by floschne** [comment]
@phuoc-ng

**Comment by phuoc-ng** [comment]
I am sorry for the late reply. You can send me an email at me@phuoc.ng to get a discount for your use case.
