### ISSUE TITLE
defaultScale={SpecialZoomLevel.PageWidth} sometimes does not render the Viewer

### ISSUE THREAD

**Issue by JoostDeCupere** [react-pdf-viewer/react-pdf-viewer#991]
Hi,

Opening a new issue related to this one: https://github.com/react-pdf-viewer/react-pdf-viewer/issues/884
A solution was provided there but it does not seem to fix the issue yet as can be seen in this video (Also see the last comment on issue 884)

https://drive.google.com/file/d/1Mgmqu5d8U2k5ddZOND3xwzQbie8-l7rd/view?usp=sharing

Kind regards,
Joost

**Comment by meseven** [comment]
Same issue
