### ISSUE TITLE
Bug in defaultLayoutPlugin

### ISSUE THREAD

**Issue by js-chris** [react-pdf-viewer/react-pdf-viewer#993]
Hi,

I found an bug in the defaultLayout Plugin. I used this example to see, if I can reproduce it also on your site:
https://react-pdf-viewer.dev/examples/add-a-new-tab-to-the-sidebar/

All you have to do is:

- click on zoom and choose "Page Fit" (or use defaultScale={SpecialZoomLevel.PageWidth} in viewer)
- navigate to the next page
- open the bookmarks

You will see, that the page navigation textfield shows page 1 instead of page 2. If you start scrolling, everything is fine again, but before you are also not able to click on next page anymore.

**Comment by phuoc-ng** [comment]
@js-chris The issue was fixed in the latest code and will be included in the next release.

**Comment by phuoc-ng** [comment]
Same as #990

**Comment by phuoc-ng** [comment]
[v3.2.0](https://react-pdf-viewer.dev/updates/) fixes the issue. Please upgrade.
