### ISSUE TITLE
Problem with clearKeyword function in Search component

### ISSUE THREAD

**Issue by js-chris** [react-pdf-viewer/react-pdf-viewer#994]
Hi,

I would like to use a custom search layout like you did here:
https://github.com/react-pdf-viewer/examples/blob/main/search/CustomizeSearchControlExample.tsx

But you can also see my problem in the search popover:

- search for something
- delete everything in the textfield
- close the search popover (or use clearKeyword)

You will see, that the search highlights in the document are not removed. So it is not possible to clearHighlight when keyword is empty.

**Comment by phuoc-ng** [comment]
@js-chris 
The issue was fixed in [v3.1.2](https://react-pdf-viewer.dev/updates/). Please upgrade.
